### PR TITLE
I have added help message to the Controls.

### PR DESCRIPTION
**Pull request by Sindorman**
Also added 'q' and 'e' as pitch. Ctrl+A and Ctrl+D as rotation. Pressing '?' will bring help.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/241)

### CODE REVIEW

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-:-KhiKstXJmBCPbCOrsP6:bnfp4nl)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiPT7orCOrFwq2Q5mp:-KhiPT7orCOrFwq2Q5mq:b-hcwb9w) (no related file):*
Can we add a case for 'r' to zero out the pitch and roll?
Also, instead of using ctrl-wasdf, let's just use the jkl; for roll and pitch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/controllers/keyboard_control.cpp, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiL6K6KC8mXX2DA0wa:-KhiL6K6KC8mXX2DA0wb:b-y3vnp0) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L29)):*
> ```cpp
> void PrintHelp()
> {
>     std::cout << "There are two ways of control\n";
> ```

Don't use \n use std::endl;
Also instead of calling std::cout add `using std::cout` with the `using std::vector` above (Same with std::endl).

---

*[src/controllers/keyboard_control.cpp, line 49 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiPjnsPvRb7c-hQjzL:-KhiPjnsPvRb7c-hQjzM:b-2c6h69) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L49)):*
> ```cpp
>     std::cout << "PageUp -> dive up\n";
>     std::cout << "Holding ctr and pressing arrow keys would control pitch.\n";
>     std::cout << "Press ? to see help message again";
> ```

Add an endl here so that the prompt ends up on a new line upon termination

---

*[src/controllers/keyboard_control.cpp, line 76 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiLUXDxWwje6Pb4q0P:-KhiLUXDxWwje6Pb4q0Q:b-fnps75) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L76)):*
> ```cpp
>     struct termios attr_new;
>     memcpy(&attr_new, &attr_backup, sizeof(struct termios));
>     attr_new.c_lflag &= ~(ECHO|ICANON|IXOFF);
> ```

Why add remove IXOFF?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/controllers/keyboard_control.cpp, line 49 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiPjnsPvRb7c-hQjzL:-KhiR7QD95c4-UUd15mo:b4d4v7o) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L49)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Add an endl here so that the prompt ends up on a new line upon termination
</blockquote></details>

Yeah, probably a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/controllers/keyboard_control.cpp, line 31 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiSZbO3iYT9a9IOcHm:-KhiSZbO3iYT9a9IOcHn:b-inmdms) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L31)):*
> ```cpp
>     std::cout << "There are two ways of control\n";
>     std::cout << "First way is:\n";
>     std::cout << "W -> forwardS\n";
> ```

These should just be forward and backward same below

---

*[src/controllers/keyboard_control.cpp, line 39 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiSxSkpEOBDXfMIDgi:-KhiSxSkpEOBDXfMIDgj:b-2ujo30) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L39)):*
> ```cpp
>     std::cout << "Q -> Pitch up\n";
>     std::cout << "E -> Pitch Down\n";
>     std::cout << "Ctrl + A -> rotate to the left\n";
> ```

Notation for key combinations is `Ctrl-[KEY]`

---

*[src/controllers/keyboard_control.cpp, line 48 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiT5LJxNXKwuoX3SJx:-KhiT5LJxNXKwuoX3SJy:b-8nolzk) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L48)):*
> ```cpp
>     std::cout << "PageDown -> dive down\n";
>     std::cout << "PageUp -> dive up\n";
>     std::cout << "Holding ctr and pressing arrow keys would control pitch.\n";
> ```

*ctrl

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by Sindorman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiL6K6KC8mXX2DA0wa:-KhicKNpYm3BmGF15iAj:bhqnpiy) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L29)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Don't use \n use std::endl;
Also instead of calling std::cout add `using std::cout` with the `using std::vector` above (Same with std::endl).
</blockquote></details>

I have added endl; at the end of the cout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by Sindorman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiL6K6KC8mXX2DA0wa:-KhicVnPavEYtF0zm-Pv:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L29)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

I have added endl; at the end of the cout.
</blockquote></details>

Done.

---

*[src/controllers/keyboard_control.cpp, line 31 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiSZbO3iYT9a9IOcHm:-KhicYHi2kSd0cSVqOZj:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L31)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

These should just be forward and backward same below
</blockquote></details>

Done.

---

*[src/controllers/keyboard_control.cpp, line 49 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiPjnsPvRb7c-hQjzL:-KhiccT19MG3PwCcUd4j:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L49)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Yeah, probably a good idea.
</blockquote></details>

Done.

---

*[src/controllers/keyboard_control.cpp, line 76 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiLUXDxWwje6Pb4q0P:-KhiceQi_mm6yfQjIwTh:brn4xej) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L76)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Why add remove IXOFF?
</blockquote></details>

removed IXOFF

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by Sindorman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiPT7orCOrFwq2Q5mp:-Khicn1bPSK9862edAU4:b-896fja) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Can we add a case for 'r' to zero out the pitch and roll?
Also, instead of using ctrl-wasdf, let's just use the jkl; for roll and pitch
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by bkallaher** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 31 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiSZbO3iYT9a9IOcHm:-Khn7nBmV_0M08Jg5bjR:bfhqml6) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L31)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-:-Khs72D3R0Eyu-NjdAMU:bnfp4nl)*

**Comment by Sindorman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 31 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiSZbO3iYT9a9IOcHm:-KhsImo6qk7T4gZJ1ik9:b-5r3s3l) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L31)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

I have changed that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by Sindorman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 39 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhiSxSkpEOBDXfMIDgi:-KhsIubyJ6y_afpLRnhi:bko5cv5) ([raw file](https://github.com/palouserobosub/robosub/blob/341d70e15094c99c282c202e4a1f41248e41988e/src/controllers/keyboard_control.cpp#L39)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Notation for key combinations is `Ctrl-[KEY]`
</blockquote></details>

We switched from ctrl for wasd to a regular keys.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by bkallaher** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 29 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxZNCbG4Lg2D7uCXev:-KhxZNCbG4Lg2D7uCXew:b-iy2moe) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L29)):*
> ```cpp
> void PrintHelp()
> {
>     std::cout << "There are two ways of control\n"
> ```

'methods' not 'ways'

---

*[src/controllers/keyboard_control.cpp, line 40 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxYd0bfAUc4mnS2dQm:-KhxYd0bfAUc4mnS2dQn:bwewndl) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L40)):*
> ```cpp
>                  "K -> Pitch Down\n"
>                  "Q -> rotate to the left\n"
>                  "E -> rotate to the right\n"
> ```

What kind of rotation is this?

---

*[src/controllers/keyboard_control.cpp, line 43 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-Khx__dJOb5nhMQhN6yr:-Khx__dJOb5nhMQhN6ys:b-pjma9w) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L43)):*
> ```cpp
>                  "L -> roll to the left\n"
>                  "; -> roll to the right"
>                  "\n\n\nAlternative is to with arrow keys:\n"
> ```

remove 'to'

---

*[src/controllers/keyboard_control.cpp, line 50 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxYQGIX9jcJEivxr9K:-KhxYQGJUbcZoSGX66zH:bbe5qc4) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L50)):*
> ```cpp
>                  "PageDown -> dive down\n"
>                  "PageUp -> dive up\n"
>                  "Holding ctr and pressing arrow keys would control pitch.\n"
> ```

What is 'ctr'? Also should be 'will' not 'would'

---

*[src/controllers/keyboard_control.cpp, line 50 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-Khxa0rdGdl4DClzGz4J:-Khxa0rdGdl4DClzGz4K:b-e5z94i) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L50)):*
> ```cpp
>                  "PageDown -> dive down\n"
>                  "PageUp -> dive up\n"
>                  "Holding ctr and pressing arrow keys would control pitch.\n"
> ```

Pitch is not the only thing controlled with the arrow keys when ctrl is pressed.

---

*[src/controllers/keyboard_control.cpp, line 51 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-Khx_FVfabomrHppofCc:-Khx_FVfabomrHppofCd:bvltdmu) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L51)):*
> ```cpp
>                  "PageUp -> dive up\n"
>                  "Holding ctr and pressing arrow keys would control pitch.\n"
>                  "Press ? to see help message again" << std::endl;
> ```

say 'this' instead of 'help'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by Sindorman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 40 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxYd0bfAUc4mnS2dQm:-KhxgVrAUKaHh_-3L-a2:bpkyubo) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L40)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

What kind of rotation is this?
</blockquote></details>

rotation on xy plane if we consider 3D.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by Sindorman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 40 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxYd0bfAUc4mnS2dQm:-KhziTxIrBwMz65NLhRV:bf14tim) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L40)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

rotation on xy plane if we consider 3D.
</blockquote></details>

Isn't it called yaw? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by Sindorman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 29 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxZNCbG4Lg2D7uCXev:-Ki1uhgHy3bgKQITLmi0:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L29)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

'methods' not 'ways'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/controllers/keyboard_control.cpp, line 40 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxYd0bfAUc4mnS2dQm:-Ki7wDfi3O8T7GzQzOVN:b-rzyzi5) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L40)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Isn't it called yaw? 
</blockquote></details>

yeah, yaw

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-:-Ki7wMNGDLkZ42B4bZi7:bnfp4nl)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/controllers/keyboard_control.cpp, line 40 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxYd0bfAUc4mnS2dQm:-Ki8Q8TdVU8egbm9O4kn:b7n3yam) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L40)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

yeah, yaw
</blockquote></details>

You changed the wrong lines. Q and E control Yaw. L and ; control Roll.

---

*[src/controllers/keyboard_control.cpp, line 50 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxYQGIX9jcJEivxr9K:-Ki8R4YGkIARKPEmG-IK:b5rvb2k) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L50)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

What is 'ctr'? Also should be 'will' not 'would'
</blockquote></details>

Should be [ctr**l**]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by Sindorman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controllers/keyboard_control.cpp, line 50 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-KhxYQGIX9jcJEivxr9K:-KiMIom4zyzKYTboKVVn:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/60a9b0c82001257f97de65c12d3318fc0338432e/src/controllers/keyboard_control.cpp#L50)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Should be [ctr**l**]
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241)*

**Comment by irwineffect** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-:-KiMLL12TzNtrPNGeodf:bnfp4nl)*

**Comment by bkallaher** [comment]
Are you sure James? :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/241#-:-KiMLQ-PDj4ajwuTTqEH:b-17lbce)*

**Pull request merged**
