### PR TITLE
Added initial Rviz work

### PR DESCRIPTION
**Pull request by irwineffect**
Running rviz.launch will bring up Rviz and display the orientation and depth of the sub, and also draws an arrow pointing at the pinger.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/303)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 4 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[launch/rviz.launch, line 13 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/303#-KvLSlEANvWpVSJXbcI6:-KvLSlEANvWpVSJXbcI7:b53h0yc) ([raw file](https://github.com/palouserobosub/robosub/blob/35441b669816a454230c8fdd8ec1c840cb777617/launch/rviz.launch#L13)):*
> ```XML
> 	</node>
> 	<node name="rviz" pkg="rviz" type="rviz" args="-d $(find robosub)/rviz/basic.rviz" required="true" />
> </launch>
> ```

TABS??!?!?!? What?!?!?

---

*[src/sensors/tf_broadcaster.py, line 36 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/303#-KvLVWq3zP8uk814ctBZ:-KvLVWq3zP8uk814ctB_:byrnzrh) ([raw file](https://github.com/palouserobosub/robosub/blob/35441b669816a454230c8fdd8ec1c840cb777617/src/sensors/tf_broadcaster.py#L36)):*
> ```Python
> 
> if __name__ == "__main__":
>     rospy.init_node('example_broadcaster')
> ```

We should probably rename this to `sub_tf_broadcaster` or so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/303)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[launch/rviz.launch, line 13 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/303#-KvLSlEANvWpVSJXbcI6:-KvZQhr-H0WwCGPMZB9c:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/35441b669816a454230c8fdd8ec1c840cb777617/launch/rviz.launch#L13)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

TABS??!?!?!? What?!?!?
</blockquote></details>

Done.

---

*[src/sensors/tf_broadcaster.py, line 36 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/303#-KvLVWq3zP8uk814ctBZ:-KvZQtjp7SGH7SqPWP2-:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/35441b669816a454230c8fdd8ec1c840cb777617/src/sensors/tf_broadcaster.py#L36)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

We should probably rename this to `sub_tf_broadcaster` or so.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/303)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/303#-:-Kv_wIzP5dfYo8nvBFM6:bnfp4nl)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/303#-:-KvcofmrI1bCepvLUzWb:bnfp4nl)*

**Pull request merged**
