### PR TITLE
Added support for the PS controller

### PR DESCRIPTION
**Pull request by bkallaher**
There are some design choices that I made that could be changed to support future features but for now this gets the PS3 controller working.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/137)

### CODE REVIEW

**Comment by irwineffect** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[msg/gamepad.msg, line 14 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaPKswr-K4rFYtfA4c2:-KaPKswsWwu6t85IJlIf:b5ccnk5) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/msg/gamepad.msg#L14)):*
> ```
> bool[19] buttons
> 
> bool type
> ```

Using a bool here isn't very explicit. We should probably use an integer with an enum (see https://github.com/PalouseRobosub/robosub/blob/dev/msg/control.msg#L65 for an example of enums)

---

*[src/controllers/gamepad_driver.cpp, line 68 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaPLhzQIfXQzAiwy7O0:-KaPLhzQIfXQzAiwy7O1:byx8fw0) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_driver.cpp#L68)):*
> ```cpp
> 
>     // get all the buttons. PlayStation has 8 more possible buttons
>     for(int i = 0; i < 11 + 8*gamepad_data.type; ++i)
> ```

This is very breakable (imagine somebody swapped xbox=1 and ps3=0 for the gamepad_data.type), I would rewrite to be something like 
```c
int num_buttons;
if (gamepad_data.type == xbox)
{
    num_buttons = 11;
}
else (gamepad_data.type == ps3)
{
    num_buttons = 19;
}
else //unrecognized
{
    ROS_ERROR(blahblahblah);
}
for(int i = 0; i < num_buttons; ++i)
```

---

*[src/controllers/gamepad_driver.hpp, line 42 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaPN4bFKe4k9n0Fag1m:-KaPN4bGIlbSTjHpo0KM:b-xfp03x) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_driver.hpp#L42)):*
> ```cpp
>     int AXIS_MAX;
>     int fd;
>     char name[128];
> ```

should use std::string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/137)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[msg/gamepad.msg, line 14 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaPKswr-K4rFYtfA4c2:-KaPPbtksfOErMJTnCTY:bx7zcpe) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/msg/gamepad.msg#L14)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Using a bool here isn't very explicit. We should probably use an integer with an enum (see https://github.com/PalouseRobosub/robosub/blob/dev/msg/control.msg#L65 for an example of enums)
</blockquote></details>

that's part of the future features i was talking about.

---

*[src/controllers/gamepad_driver.cpp, line 68 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaPLhzQIfXQzAiwy7O0:-KaPQ5Zapwr1TfywMf3p:b83ppnz) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_driver.cpp#L68)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

This is very breakable (imagine somebody swapped xbox=1 and ps3=0 for the gamepad_data.type), I would rewrite to be something like 
```c
int num_buttons;
if (gamepad_data.type == xbox)
{
    num_buttons = 11;
}
else (gamepad_data.type == ps3)
{
    num_buttons = 19;
}
else //unrecognized
{
    ROS_ERROR(blahblahblah);
}
for(int i = 0; i < num_buttons; ++i)
```
</blockquote></details>

again future feat.ures

---

*[src/controllers/gamepad_driver.hpp, line 42 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaPN4bFKe4k9n0Fag1m:-KaPPB0iaD6JMOeWoX_5:b-t5jfsk) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_driver.hpp#L42)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

should use std::string
</blockquote></details>

the function that writes to it expects a char buffer so that would not work as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/137)*

**Comment by dcrossman** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controllers/gamepad_control.cpp, line 61 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaUOlmSexg7ly4AdYyd:-KaUOlmSexg7ly4AdYye:b2nhqzo) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_control.cpp#L61)):*
> ```cpp
> 
>     // Using Xbox controller
>     if (!msg.type && !msg.buttons[0])
> ```

WTF

---

*[src/controllers/gamepad_driver.cpp, line 37 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaUP37i8Vs8rZpp6dda:-KaUP37i8Vs8rZpp6ddb:b-46usuk) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_driver.cpp#L37)):*
> ```cpp
>     // 0: XBOX controller
>     // 1: PlayStation controller
>     gamepad_data.type = (name[0] != 'M');
> ```

You should actually check if the name matches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/137)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controllers/gamepad_driver.cpp, line 68 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaPLhzQIfXQzAiwy7O0:-KaVEWs8piclEFTcb-wQ:b2tdtib) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_driver.cpp#L68)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

again future feat.ures
</blockquote></details>

I actually found a better way to do this by querying the driver.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/137)*

**Comment by skallaher** [comment]
Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/controllers/gamepad_driver.cpp, line 68 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaPLhzQIfXQzAiwy7O0:-KaVzldFsuVwCgvfzxrm:b-7nss9y) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_driver.cpp#L68)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

I actually found a better way to do this by querying the driver.
</blockquote></details>

I enjoyed the `blahblahblah` output. Really defines the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/137)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-:-KaYaKVr1JaytkeUjpb2:bnfp4nl)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/controllers/gamepad_control.cpp, line 61 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaUOlmSexg7ly4AdYyd:-KaZ1AfeQjvs3NkI4LF6:b-wz6jsg) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_control.cpp#L61)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

WTF
</blockquote></details>

Updated with enumerated definitions

---

*[src/controllers/gamepad_driver.cpp, line 37 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/137#-KaUP37i8Vs8rZpp6dda:-KaZ1H-Xl-sPti_XGWZa:bf2wn9f) ([raw file](https://github.com/palouserobosub/robosub/blob/42c9da8a98d3c098afade6872c5e6ffabd4e52e9/src/controllers/gamepad_driver.cpp#L37)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

You should actually check if the name matches.
</blockquote></details>

For now I'm going to compare vendor,  later if there is more controllers  that we want to use this can be updated. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/137)*

**Pull request merged**
