### PR TITLE
Filter Modularizing

### PR DESCRIPTION
**Pull request by skallaher**
This removes the hard coded filters from the VisionProcessor and moves them to a new filter system consisting of a Filter base class. This structure is similar to the legacy filter system, though not identical.

I don't know if I should keep the classes in the same .cpp file. Having all of the header information in one keeps include requirements to a minimum, however the only benefit to having the classes in the same source file is simplicity in the CMakeLists file. The downside to this is a loss in readability.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/230)

### CODE REVIEW

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Reviewed 26 of 26 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[src/vision/Vision.cpp, line 77 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgbirIjF8v96Hgs21NA:-KgbirIjF8v96Hgs21NB:b-cpoeus) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/Vision.cpp#L77)):*
> ```cpp
>     {
>         //No need to do anything here except destroy any open windows
>         destroyAllWindows();
> ```

What does this do if no windows are open? The highgui docs don't really say.

---

*[src/vision/Vision.cpp, line 102 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-Kgbj9Q9AEuVrwinrOZe:-Kgbj9Q9AEuVrwinrOZf:b4g9nwj) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/Vision.cpp#L102)):*
> ```cpp
>                         << " with normalized: [" << point.xPos <<
>                         ", " << point.yPos << "]. Image Size: "
>                         << finalImg.size());
> ```

Do you really need to print the image size here when you do it in the previous DEBUG_STREAM? Nothing prior to this point modifies the image size.

---

*[src/vision/filters/Filter.cpp, line 79 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgblDnt49VZOA-Nrb8b:-KgblDnupnHhvO4lrekS:b-clcv6g) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.cpp#L79)):*
> ```cpp
>         strCode = static_cast<string>(xrv);
>     }
>     catch (XmlRpc::XmlRpcException e)
> ```

Does e.what() not give any indication of what the error actually is?

---

*[src/vision/filters/Filter.cpp, line 139 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-Kgblnj3S4BuLRk3bdxn:-Kgblnj3S4BuLRk3bdxo:bmubpu3) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.cpp#L139)):*
> ```cpp
>                                          i->first << ": " << it->first);
>                         return;
>                         break;
> ```

This break isn't needed with the return right before it.

---

*[src/vision/filters/Filter.cpp, line 143 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgblxrAFML5IHjc9EMe:-KgblxrAFML5IHjc9EMf:b-2o5hsk) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.cpp#L143)):*
> ```cpp
> 
>                 //Values must be between 0 and 255
>                 if (value < 0)
> ```

Maybe think about adding a debug message that the value was initially invalid and was set to 0 or 255

---

*[src/vision/filters/Filter.hpp, line 28 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgboKGLM2FmJ7mLgtkQ:-KgboKGLM2FmJ7mLgtkR:b-4vvhyw) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.hpp#L28)):*
> ```cpp
> using XmlRpc::XmlRpcValue;
> 
> class Filter
> ```

Add a comment that this is the base class for all of the other filters

---

*[src/vision/filters/Filter.hpp, line 85 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-Kgbo_mprSXiNpXbIN5V:-Kgbo_mprSXiNpXbIN5W:b-8rh9iu) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.hpp#L85)):*
> ```cpp
>         int code;
> 
>         const std::map<string, int> paramList
> ```

Are these all of the supported OpenCV conversions or just the ones that you are supporting?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/230)*

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[src/vision/Vision.cpp, line 77 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgbirIjF8v96Hgs21NA:-Kgbs9N-bbZO6dKfBGs0:b526ayo) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/Vision.cpp#L77)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

What does this do if no windows are open? The highgui docs don't really say.
</blockquote></details>

As far as I know, nothing. All it should do is close any open windows.

---

*[src/vision/Vision.cpp, line 102 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-Kgbj9Q9AEuVrwinrOZe:-KgbsNkIB-2DlY0_5Uz0:bso856g) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/Vision.cpp#L102)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Do you really need to print the image size here when you do it in the previous DEBUG_STREAM? Nothing prior to this point modifies the image size.
</blockquote></details>

Will remove. I was debugging and checking to make sure that nothing modified it.

---

*[src/vision/filters/Filter.cpp, line 79 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgblDnt49VZOA-Nrb8b:-KgbsY8kavTlaZTm5NPA:b-ihsfxh) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.cpp#L79)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Does e.what() not give any indication of what the error actually is?
</blockquote></details>

Yes and no. XmlRpcExceptions are not very verbose. The best I could get out of it is possibly the error code. In my experience, even this isn't very helpful.

---

*[src/vision/filters/Filter.cpp, line 139 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-Kgblnj3S4BuLRk3bdxn:-Kgbt2njh0_dz6FlcUHu:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.cpp#L139)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

This break isn't needed with the return right before it.
</blockquote></details>

Done.

---

*[src/vision/filters/Filter.cpp, line 143 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgblxrAFML5IHjc9EMe:-Kgbv-yI60aYHE54rXYz:b-if40q0) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.cpp#L143)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Maybe think about adding a debug message that the value was initially invalid and was set to 0 or 255
</blockquote></details>

Done. I have updated all of the setParams for each filter to have a warning output if it changes the param in any way.

---

*[src/vision/filters/Filter.hpp, line 28 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgboKGLM2FmJ7mLgtkQ:-KgbvCbwRo-57WxOP31-:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.hpp#L28)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Add a comment that this is the base class for all of the other filters
</blockquote></details>

Done.

---

*[src/vision/filters/Filter.hpp, line 85 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-Kgbo_mprSXiNpXbIN5V:-KgbvDgQwfHx7tSrJpKC:bfj7kzq) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.hpp#L85)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Are these all of the supported OpenCV conversions or just the ones that you are supporting?
</blockquote></details>

These are a small subset. There are far more supported by OpenCV. If any are needed, adding them to this list will make them supported.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/230)*

**Comment by bkallaher** [comment]
Review status: 23 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vision/filters/Filter.cpp, line 79 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgblDnt49VZOA-Nrb8b:-Kgbvc9yaHh-YMM9FzHq:b-1ht3m5) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.cpp#L79)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Yes and no. XmlRpcExceptions are not very verbose. The best I could get out of it is possibly the error code. In my experience, even this isn't very helpful.
</blockquote></details>

In other sections you print the error code. could you ensure consistency for your catch statements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/230)*

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by skallaher** [comment]
Review status: 23 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vision/filters/Filter.cpp, line 79 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-KgblDnt49VZOA-Nrb8b:-KgbzUuwvMg7Hx-1btUM:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/d409f1d8b241c9a37777a76862703b7526bd6ec9/src/vision/filters/Filter.cpp#L79)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

In other sections you print the error code. could you ensure consistency for your catch statements.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/230)*

**Comment by bkallaher** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/230)*

**Comment by bkallaher** [comment]
Waiting for discussion on the single file full of classes to complete.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-:-Kgc-f32QTPfdSLTXn7D:b-uqirmz)*

**Comment by skallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Reviewed 6 of 8 files at r4.
Review status: 30 of 31 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/230)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/230)*

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by irwineffect** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/230#-:-KgplLEYRtDHSBzwaTt4:bnfp4nl)*

**Pull request merged**
