### PR TITLE
Made the joystick depth parameters reload on every joystick message f…

### LINKED ISSUE #178: joystick dynamic reload parameters
Right now the joystick node loads up its min and max depth settings only on bootup, we need the ability to modify the parameters while the node is running and have the node update its internal settings.

### PR DESCRIPTION
**Pull request by bkallaher**
…rom the driver
fixes #178

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/197)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/joystick_control.cpp, line 8 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/197#-KeHSj5-P_I_3RGwM1H5:-KeHSj50_j3BYL3ps9hG:b-9mclhf) ([raw file](https://github.com/palouserobosub/robosub/blob/f7b5e037619989b0f3d61684987dba30d4f5a091/src/controllers/joystick_control.cpp#L8)):*
> ```cpp
> 
> ros::Publisher pub;
> ros::NodeHandle nh;
> ```

Why did this move? I don't see anywhere you're using it outside of the main function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/197)*

**Comment by bkallaher** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/joystick_control.cpp, line 8 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/197#-KeHSj5-P_I_3RGwM1H5:-KeHWSHL7XaEyMIIc3mh:b-jd9vj2) ([raw file](https://github.com/palouserobosub/robosub/blob/f7b5e037619989b0f3d61684987dba30d4f5a091/src/controllers/joystick_control.cpp#L8)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why did this move? I don't see anywhere you're using it outside of the main function.
</blockquote></details>

I was using it before I switched to cached parameters. I've moved it back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/197)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/197#-:-KeHXFDOoM-hpjAZt13d:bnfp4nl)*

**Comment by dcrossman** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/197#-:-KeLGKOcLGvQ7RDI3weN:bnfp4nl)*

**Comment by irwineffect** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/197)*

**Comment by irwineffect** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/197#-:-KeQ2IuqF6Gti7DDuflA:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/197)*

**Comment by irwineffect** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/197)*

**Pull request merged**
