### PR TITLE
Modifies MaestroDriver to map input normalized force commands to output PWM signals

### PR DESCRIPTION
**Pull request by ryan-summers**
Please refer to https://github.com/PalouseRobosub/robosub/issues/163 for information, data, and scripts relating to this pull request.

This fix should not be implemented until https://github.com/PalouseRobosub/robosub_simulator/issues/53 is properly implemented and also utilizes polynomial thrust instead of liner so that the change can be tested in simulation.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/167)

### CODE REVIEW

**Comment by irwineffect** [comment]
Something to keep in mind:
It's difficult to review changes when you also change the filename in the same commit/PR because it looks like the entire file has changed, so I can't easily determine the changes that were made.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-:-KbDSLE1PoJDow90YXUS:bpfyz3g)*

**Comment by irwineffect** [comment]
Actually, it looks like reviewable was able to catch the rename on the header file, but not on the source file. The source file must've had too many changes for their algorithm to detect it was the same file. But for the future it would be a good policy to separate changes from file renames.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/movement/CMakeLists.txt, line 3 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbC90RR5_Cs5Vpknutl:-KbC90RV2h9Ole-MZ86j:b-cdfkz5) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/CMakeLists.txt#L3)):*
> ```CMake
> 
> #thruster nodes
> add_ros_node(thruster_maestro thruster_maestro.cpp MaestroThrusterDriver.cpp)
> ```

we're using a lowercase, '_' separated filename format. Please rename to maestro_thruster_driver.cpp

---

*[src/movement/MaestroThrusterDriver.cpp, line 15 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDWRrn0wnHAcE-a7M-:-KbDWRrn0wnHAcE-a7M0:b83vtmg) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L15)):*
> ```cpp
>         _post_reset_delay_ms(185),
>         _next_reset(),
>         _max_thrust_kgf(0)
> ```

The only thing that should be in this constructor is _is_initialized(false), everything else should go in the init() function

---

*[src/movement/MaestroThrusterDriver.cpp, line 54 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDYwQNNzIjWHmYKbu6:-KbDYwQNNzIjWHmYKbu7:be9j3yo) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L54)):*
> ```cpp
>         double max_thrust_newtons = 0;
>         double back_thrust_ratio = 0;
>         if (ros::param::getCached("control/max_thrust", max_thrust_newtons) ==
> ```

You don't want to use the cached version here since you are only calling init() once. When you use getCached()  it instructs the parameter server to notify the node every time the parameter changes, which causes a (small) load on the server, so you don't want to use it if you don't need it. 

---

*[src/movement/MaestroThrusterDriver.cpp, line 203 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDilPxpZ8AJTnAjmpU:-KbDilPxpZ8AJTnAjmpV:bfmrjnb) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L203)):*
> ```cpp
>             ROS_INFO("Software-limiting thruster speed.");
>             speed = _max_speed[channel] * ((speed < 0)? -1 : 1);
>         }
> ```

Should we still be using this method to limit the thrusters? If so, let's change the ROS_INFO to a ROS_DEBUG_THROTTLE

---

*[src/movement/MaestroThrusterDriver.cpp, line 205 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDiymuEsJsnaiTjpuC:-KbDiymvGHL7gL-Zni80:by92q0c) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L205)):*
> ```cpp
>         }
> 
>         const int signal = parseNormalized(speed, command[3], command[2]);
> ```

we should probably use a fixed-width datatype here, since we're dealing so close to the hardware

---

*[src/movement/MaestroThrusterDriver.cpp, line 221 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDkf7QQ3mUBsaRW-hh:-KbDkf7R8YBOKjkac1AD:b-vn66kb) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L221)):*
> ```cpp
>         if (abs(signal - 1500) < 25)
>         {
>             ROS_INFO("Parsed signal is in thruster dead-band.");
> ```

Shouldn't the parseNormalized() function result in us never getting values in the deadband unless we mean to send 0? Unless we are sending 0, then getting something in the deadband is an error. If we are sending zero, we don't care about getting this info message. Might want to rethink the logic of this check.

---

*[src/movement/MaestroThrusterDriver.cpp, line 249 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDlLtyLzVYjmiP1gJv:-KbDlLtyLzVYjmiP1gJw:b-dxahmj) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L249)):*
> ```cpp
>                                                     uint8_t &msb, uint8_t &lsb)
>      {
>          if (normalized_force < -1 || normalized_force > 1)
> ```

This check already occurs in the set() function. Pick one or the other. I recommend keeping the one in the set() function and cutting this one, it makes sense to have the public interface do bounds checking, the private functions should be able to assume good inputs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-:-KbDtEBj8IdLhP-wYqIR:biqdrhw)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/movement/CMakeLists.txt, line 3 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbC90RR5_Cs5Vpknutl:-KbGkgvAK_5MOV0fsLXW:bkehzln) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/CMakeLists.txt#L3)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

we're using a lowercase, '_' separated filename format. Please rename to maestro_thruster_driver.cpp
</blockquote></details>

Will update as final revision so as to keep change history consistent.

---

*[src/movement/MaestroThrusterDriver.cpp, line 15 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDWRrn0wnHAcE-a7M-:-KbGkuCfdjT_WSIjdbIF:bg009qc) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L15)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

The only thing that should be in this constructor is _is_initialized(false), everything else should go in the init() function
</blockquote></details>

Out of curiosity, is there any reason you are opposed to constructing the objects here as well? Essentially, the same thing is being done, this just makes it explicitly completed. I can understand if you would like it removed for clarity.

---

*[src/movement/MaestroThrusterDriver.cpp, line 54 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDYwQNNzIjWHmYKbu6:-KbGlQE0wJIX394hiXkw:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L54)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

You don't want to use the cached version here since you are only calling init() once. When you use getCached()  it instructs the parameter server to notify the node every time the parameter changes, which causes a (small) load on the server, so you don't want to use it if you don't need it. 
</blockquote></details>

Done.

---

*[src/movement/MaestroThrusterDriver.cpp, line 203 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDilPxpZ8AJTnAjmpU:-KbGmP62YBh2wKaxyYzU:bih74ca) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L203)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Should we still be using this method to limit the thrusters? If so, let's change the ROS_INFO to a ROS_DEBUG_THROTTLE
</blockquote></details>

Limitting thrusters was not in the scope of this pull request. I would be happy to incorporate it if we see fit. These lines of code were not changed with this revision.

---

*[src/movement/MaestroThrusterDriver.cpp, line 205 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDiymuEsJsnaiTjpuC:-KbGl_YQ1XmMStVoK9nT:b-s9bzqk) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L205)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

we should probably use a fixed-width datatype here, since we're dealing so close to the hardware
</blockquote></details>

the specific int signal is not used on the hardware level, it is only used for detection of a dead-band signal. The variable 'signal' is used only in conditional checking.

---

*[src/movement/MaestroThrusterDriver.cpp, line 221 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDkf7QQ3mUBsaRW-hh:-KbGljahi7Sni0HjHQXZ:b-lhj8ld) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L221)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Shouldn't the parseNormalized() function result in us never getting values in the deadband unless we mean to send 0? Unless we are sending 0, then getting something in the deadband is an error. If we are sending zero, we don't care about getting this info message. Might want to rethink the logic of this check.
</blockquote></details>

No, we can still potentially get dead-band values out of the characterized polynomials (look at the coefficients and assume lim x-> 0). I haven't added code into parseNormalized that will bump the signal out of dead-band.

---

*[src/movement/MaestroThrusterDriver.cpp, line 249 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDlLtyLzVYjmiP1gJv:-KbGm-Nel4VxuuEabUUl:b-dgudd6) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L249)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

This check already occurs in the set() function. Pick one or the other. I recommend keeping the one in the set() function and cutting this one, it makes sense to have the public interface do bounds checking, the private functions should be able to assume good inputs.
</blockquote></details>

I would argue it's never okay for a function to assume good input. That is the fundamental principle of a function failing. There could be a function added in the future that calls parseNormalized that is unaware of the bounds checking. Because the bound check is conducted in parseNormalized, which is called within set, I would imagine that it should be okay to remove it from set(). The only worry is that if parseNormalized were removed in the future, bounds checking would need to be re-added, but I would say that is justifiable.

Aside from that, they are actually not the same bound check. The check within set() verifies that the signal received is in a normalized format and errors out based on non-normalized input. However, the input is then further modified by the bounds-checking and then passed into parseNormalized. Inside of parse normalized, the bound-checked modified input is then verified to still be within valid ranges.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by ryan-summers** [comment]
Will do in the future! I was actually doing this to test if reviewable could catch it well or not.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-:-KbGoA11BQCYTAEa14a7:b-bqbyqn)*

**Comment by bkallaher** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/movement/MaestroThrusterDriver.cpp, line 54 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDYwQNNzIjWHmYKbu6:-KbHx50I_r8WqZduzn3D:bh0j1l2) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L54)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You only changed one of the two.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by ryan-summers** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/movement/MaestroThrusterDriver.cpp, line 54 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDYwQNNzIjWHmYKbu6:-KbLDLzr0xWY1GM7YT-b:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L54)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

You only changed one of the two.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by ryan-summers** [comment]
Simulator pull request for the complement implementation on the simulator: https://github.com/PalouseRobosub/robosub_simulator/pull/59

**Comment by irwineffect** [comment]
Reviewed 1 of 6 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/movement/MaestroThrusterDriver.cpp, line 15 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDWRrn0wnHAcE-a7M-:-KbasFVNdfOaRZwfZ4oy:bfi4xwt) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L15)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Out of curiosity, is there any reason you are opposed to constructing the objects here as well? Essentially, the same thing is being done, this just makes it explicitly completed. I can understand if you would like it removed for clarity.
</blockquote></details>

Yeah, having it set in two places can cause confusion, and having this be the one place limits us.

---

*[src/movement/MaestroThrusterDriver.cpp, line 203 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDilPxpZ8AJTnAjmpU:-KbassstKhPXjxYOeIK-:b-56kf1u) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L203)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Limitting thrusters was not in the scope of this pull request. I would be happy to incorporate it if we see fit. These lines of code were not changed with this revision.
</blockquote></details>

Yes, the control system sending +1 should map to the thruster outputting 100% of the allowed thrust.

---

*[src/movement/MaestroThrusterDriver.cpp, line 221 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDkf7QQ3mUBsaRW-hh:-KbatK7TShu_CvlwKKGh:b-eyrcyv) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L221)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

No, we can still potentially get dead-band values out of the characterized polynomials (look at the coefficients and assume lim x-> 0). I haven't added code into parseNormalized that will bump the signal out of dead-band.
</blockquote></details>

ok then. However it shouldn't happen very often, right? Let's turn this into a warning to make it more obvious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by ryan-summers** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/movement/MaestroThrusterDriver.cpp, line 15 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDWRrn0wnHAcE-a7M-:-KbmUV9i72oLkIV7wvcd:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L15)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Yeah, having it set in two places can cause confusion, and having this be the one place limits us.
</blockquote></details>

Done.

---

*[src/movement/MaestroThrusterDriver.cpp, line 203 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDilPxpZ8AJTnAjmpU:-KbmUgR5-MnDovJBFz64:b-h4v6ea) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L203)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Yes, the control system sending +1 should map to the thruster outputting 100% of the allowed thrust.
</blockquote></details>

So should I change 197 to use ROS_DEBUG_THROTTLE?

---

*[src/movement/MaestroThrusterDriver.cpp, line 221 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDkf7QQ3mUBsaRW-hh:-KbmUwlKBRqpm7lKBucj:bhx2wck) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L221)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

ok then. However it shouldn't happen very often, right? Let's turn this into a warning to make it more obvious.
</blockquote></details>

Alright. Yes, it shouldn't happen very often at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by irwineffect** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-Kbr1As2EBTqQmus2eMh:-Kbr1As2EBTqQmus2eMi:b-ut240x) (no related file):*
This causes the maestro unit test to fail, need to update the unit test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by irwineffect** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-Kbr1As2EBTqQmus2eMh:-Kbr5h3U_aFMVmppfNtd:bcvpdf3) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

This causes the maestro unit test to fail, need to update the unit test.
</blockquote></details>

Also need to update control system test to launch the thruster_maestro node. Note that this will temporarily cause the unit tests to fail until the simulator changes are also merged in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by irwineffect** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbrQFXEdhLnTGYnJ6b3:-KbrQFXEdhLnTGYnJ6b4:b4pu2i1) (no related file):*
Also need to to remove the redundant force parameters from the control section of parameters

---

*[src/movement/MaestroThrusterDriver.cpp, line 203 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDilPxpZ8AJTnAjmpU:-KbrPuHNdEC4liAc9Qb_:blkcyvu) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L203)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

So should I change 197 to use ROS_DEBUG_THROTTLE?
</blockquote></details>

Nah, move this to parse normalized and check the signal against 10amp points to ensure the thrusters never exceed 10 amps. max_thrust will be used for the soft software limit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by ryan-summers** [comment]
Review status: 2 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-Kbr1As2EBTqQmus2eMh:-Kbs4dEyHlxB-xXrAT6V:b-896fix) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Also need to update control system test to launch the thruster_maestro node. Note that this will temporarily cause the unit tests to fail until the simulator changes are also merged in.
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbrQFXEdhLnTGYnJ6b3:-Kbs4gE4JaGgXopHyY41:b-896fix) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Also need to to remove the redundant force parameters from the control section of parameters
</blockquote></details>

Done.

---

*[src/movement/MaestroThrusterDriver.cpp, line 203 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-KbDilPxpZ8AJTnAjmpU:-Kbs4hplZ1A3NQx8MauS:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/c0ef27021a5eafe5c763049ea0f5b68a73c26695/src/movement/MaestroThrusterDriver.cpp#L203)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Nah, move this to parse normalized and check the signal against 10amp points to ensure the thrusters never exceed 10 amps. max_thrust will be used for the soft software limit
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by dcrossman** [comment]
Reviewed 1 of 6 files at r1, 7 of 8 files at r5.
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/movement/thruster_maestro.cpp, line 3 at r5](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-Kc51HMo9ANLwbQuTcqz:-Kc51HMpIIreCC4Fxyo9:b-7zu4c2) ([raw file](https://github.com/palouserobosub/robosub/blob/76019dd929fc73bc663e2f2393be363b37a1dd74/src/movement/thruster_maestro.cpp#L3)):*
> ```cpp
> /*
>  * Michelle Farr - 10/25/2016
>  * I am working on this... Haven't tested it at all
> ```

Still accurate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by ryan-summers** [comment]
Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/movement/thruster_maestro.cpp, line 3 at r5](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-Kc51HMo9ANLwbQuTcqz:-Kc5zFR6DvU-SclzMSub:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/76019dd929fc73bc663e2f2393be363b37a1dd74/src/movement/thruster_maestro.cpp#L3)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

Still accurate?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by dcrossman** [comment]
Reviewed 1 of 8 files at r1, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 5 of 10 files at r5, 6 of 6 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/167#-:-KcAINUgy0nrYsMVNUjr:bnfp4nl)*

**Pull request merged**
