### PR TITLE
Adds in LED glow microcontroller code

### PR DESCRIPTION
**Pull request by ryan-summers**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/252)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[firmware/led/src/led.ino, line 73 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq15-xjQAH7lbCF2BZ:-Kjq15-ylQJqqoPezr6V:b-vebyq1) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L73)):*
> ```Arduino
> 
>     current_duty = static_cast<float>(current_percentage) / 100.0;
>     if (current_duty > 1)
> ```

This could never happen if `current_percentage` is always bounded to 100.0.

---

*[firmware/led/src/led.ino, line 98 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq2Pe7Rmi3Dax9bXg_:-Kjq2Pe8wd_CKcKvZnfv:b-9ubsvu) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L98)):*
> ```Arduino
>     if (duty > 1.0 || duty < 0)
>     {
>         return;
> ```

Is there an easy way to report this error of an invalid duty cycle?

---

*[firmware/led/src/led.ino, line 145 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq4JdpX-Cx1--VJSst:-Kjq4JdpX-Cx1--VJSsu:b-z620st) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L145)):*
> ```Arduino
>          */
>         const float duty = (cos(3.14159 * static_cast<float>(i)/100.0) * -1.0 +
>                 1.0) / 2.0;
> ```

Here, you're going from 1 to -1 within the cosine call then multiplying by -1, instead, if you decrement from 100 to 0, you would go from -1 to 1 which achieves the same thing with one less operation every loop. 

---

*[firmware/led/src/led.ino, line 150 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq5GpRgmA4CLLRqlu3:-Kjq5GpRgmA4CLLRqlu4:b6u8xni) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L150)):*
> ```Arduino
> 
>     /*
>      * Leave the LEDs on at full intensity for 500ms to show power-on.
> ```

Now all we need is a jaunty tone from a small speaker!

---

*[msg/PositionsStamped.msg, line 3 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq63ntkc73hecY6Zx6:-Kjq63ntkc73hecY6Zx7:b7m0mn) ([raw file](https://github.com/palouserobosub/robosub/blob/7b42431f63ba69560e3efcb817ec64f915347430/msg/PositionsStamped.msg#L3)):*
> ```
> std_msgs/Header header
> float32[] distances
> geometry_msgs/Vector3[] positions
> ```

Why is this change in this PR?

---

*[msg/thruster.msg, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq6GygahjbeW3tMyO2:-Kjq6GygahjbeW3tMyO3:b-uzshfb) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/msg/thruster.msg#L1)):*
> ```
> float32[] data
> ```

Why is this changing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[firmware/led/src/led.ino, line 73 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq15-xjQAH7lbCF2BZ:-KjuFdnMA67CjWb1SNqm:bsovrzh) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L73)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This could never happen if `current_percentage` is always bounded to 100.0.
</blockquote></details>

Correct, but if the above calculation of current_duty changed (which it has within my development), the check is still helpful.

---

*[firmware/led/src/led.ino, line 98 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq2Pe7Rmi3Dax9bXg_:-KjuFmPTkQb88UFPyChj:b-x5q87u) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L98)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Is there an easy way to report this error of an invalid duty cycle?
</blockquote></details>

Not particularly, and it's not necessarily meaningful. The main reason for this is to help deal with float comparisons. (e.g. very close to 1.0 and 0.0)

---

*[firmware/led/src/led.ino, line 145 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq4JdpX-Cx1--VJSst:-KjuG4YWZIfiC_XKndwf:b-cjiy87) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L145)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Here, you're going from 1 to -1 within the cosine call then multiplying by -1, instead, if you decrement from 100 to 0, you would go from -1 to 1 which achieves the same thing with one less operation every loop. 
</blockquote></details>

I'm really not concerned about saving a single instruction every loop. I think leaving the code like this makes it more understandable.

---

*[msg/PositionsStamped.msg, line 3 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq63ntkc73hecY6Zx6:-KjuGR06ySjrMEQ0khMy:b-wmzhqs) ([raw file](https://github.com/palouserobosub/robosub/blob/7b42431f63ba69560e3efcb817ec64f915347430/msg/PositionsStamped.msg#L3)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why is this change in this PR?
</blockquote></details>

This message type breaks the build for microcontroller messages and was not being used within the main repository.

---

*[msg/thruster.msg, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq6GygahjbeW3tMyO2:-KjuGHnE_vQJ4OaDoFcj:bqf4u1) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/msg/thruster.msg#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why is this changing?
</blockquote></details>

The ATMega1284P does not support 64-bit floating point numbers. All floats are 32-bit. As such, when it subscribes to the thruster topic, it gets a 64-bit float, which it is incapable of interpretting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by skallaher** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[firmware/led/src/led.ino, line 98 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq2Pe7Rmi3Dax9bXg_:-KjuYI3mGOxQeL1EQCmw:b-4p80i7) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L98)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Not particularly, and it's not necessarily meaningful. The main reason for this is to help deal with float comparisons. (e.g. very close to 1.0 and 0.0)
</blockquote></details>

This return is a failure state. The pwm won't be written and there is nothing that says that it has failed. For debugging purposes, if this is consistently happening, an error output would be important.

---

*[firmware/led/src/led.ino, line 145 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq4JdpX-Cx1--VJSst:-KjuYv8ePcovKaxXm6yi:b48i4rh) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L145)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I'm really not concerned about saving a single instruction every loop. I think leaving the code like this makes it more understandable.
</blockquote></details>

This line is not very easily understandable either way.

---

*[msg/PositionsStamped.msg, line 3 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq63ntkc73hecY6Zx6:-KjuZLvozFUkeT4qVdic:b6w9abv) ([raw file](https://github.com/palouserobosub/robosub/blob/7b42431f63ba69560e3efcb817ec64f915347430/msg/PositionsStamped.msg#L3)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

This message type breaks the build for microcontroller messages and was not being used within the main repository.
</blockquote></details>

What was it originally for and why does it break the microcontroller message builds? This may be a symptom of a larger underlying problem.

---

*[msg/thruster.msg, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq6GygahjbeW3tMyO2:-KjuZvGXaxSpgKE377Bz:b8l26hh) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/msg/thruster.msg#L1)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

The ATMega1284P does not support 64-bit floating point numbers. All floats are 32-bit. As such, when it subscribes to the thruster topic, it gets a 64-bit float, which it is incapable of interpretting.
</blockquote></details>

This is removing precision from the thrusters, as the LEDs are a non-critical system, this shouldn't affect the rest of the systems. For instance, the thruster driver expects this to be a double precision value and this change could have unwanted side effects.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[firmware/led/src/led.ino, line 98 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq2Pe7Rmi3Dax9bXg_:-KjwvWb7Ru3c-xf4uZtL:bp8jr8z) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L98)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This return is a failure state. The pwm won't be written and there is nothing that says that it has failed. For debugging purposes, if this is consistently happening, an error output would be important.
</blockquote></details>

This is a microcontroller. There is no means of guarenteeing you have a communication channel to it, therefore there is no way to have output messages that are meaningful. The error feedback is that the LEDs don't turn on or flicker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[firmware/led/src/led.ino, line 145 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq4JdpX-Cx1--VJSst:-Kjww17hty1ehh_Y3Rfv:bvag2zv) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L145)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This line is not very easily understandable either way.
</blockquote></details>

I would argue it makes more sense in this sense because as i increases, so does the intensity. It seems very weird to have i decreasing resulting in higher LED intensities.

---

*[msg/PositionsStamped.msg, line 3 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq63ntkc73hecY6Zx6:-KjwwE5jyDQEESqVxN_L:b-b5kq3s) ([raw file](https://github.com/palouserobosub/robosub/blob/7b42431f63ba69560e3efcb817ec64f915347430/msg/PositionsStamped.msg#L3)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

What was it originally for and why does it break the microcontroller message builds? This may be a symptom of a larger underlying problem.
</blockquote></details>

Yes, and I'm assuming it was implemented with the localization system. What it actually breaks is a tool within rosserial_client that builds message types. Why it fails is beyond me, but it appears to only fail for this message.

---

*[msg/thruster.msg, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq6GygahjbeW3tMyO2:-KjwwPgCTcOuhhcppkUs:b8j2wqb) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/msg/thruster.msg#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This is removing precision from the thrusters, as the LEDs are a non-critical system, this shouldn't affect the rest of the systems. For instance, the thruster driver expects this to be a double precision value and this change could have unwanted side effects.
</blockquote></details>

It's not removing any actual precision from the thrusters. We don't need a 64-bit precision double for containing thruster messages, it just increases our transportation overhead. You will see no difference in thruster output because the float duty cycle is multiplied into an int and mapped. All precision differences are going to be heavily rounded off in integer truncation anyways.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[msg/thruster.msg, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq6GygahjbeW3tMyO2:-Kjwx3LBo0jSgKoK3m4t:boe92ki) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/msg/thruster.msg#L1)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

It's not removing any actual precision from the thrusters. We don't need a 64-bit precision double for containing thruster messages, it just increases our transportation overhead. You will see no difference in thruster output because the float duty cycle is multiplied into an int and mapped. All precision differences are going to be heavily rounded off in integer truncation anyways.
</blockquote></details>

Further comment, this won't cause any compatibility issues with the thruster driver. The message will contain a 32-bit precision float that will be casted to a double within the call to the setThrusterSpeed function. I don't see how that would cause any issues.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by irwineffect** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[firmware/led/src/led.ino, line 66 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-KjxlvGNKDl1AWNIbkj2:-KjxlvGNKDl1AWNIbkj3:bk5vr3y) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L66)):*
> ```Arduino
>      * percentage is capped at 100.
>      */
>     current_percentage = total / msg.data_length * 180.0 + min;
> ```

This is kinda a weird way to express this logic. Not necessary, but I'd prefer to have it broken up into multiple steps so it's more clear (i.e. separate the averaging logic from the scaling and the minimum).

---

*[firmware/led/src/led.ino, line 85 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-KjxkM1XI9tFXjbId2Gi:-KjxkM1XI9tFXjbId2Gj:bd2ubkc) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L85)):*
> ```Arduino
>  *       repeatedly to get a dimming effect. The arduino analogWrite() function
>  *       will not work because the specified LED_PIN is not compliant with the
>  *       output comparator pins.
> ```

Just commenting, for future revs of the board we should try to use the hardware PWM pins if possible, or at least have a separate PWM pin breakout for this use case.

---

*[firmware/led/src/led.ino, line 98 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq2Pe7Rmi3Dax9bXg_:-KjxjauP-LMqbQ57hcOP:b-n49tl4) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L98)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

This is a microcontroller. There is no means of guarenteeing you have a communication channel to it, therefore there is no way to have output messages that are meaningful. The error feedback is that the LEDs don't turn on or flicker.
</blockquote></details>

Why not use http://wiki.ros.org/rosserial/Overview/Logging? I understand that there's a not insignificant amount of overhead using rosserial logging, but it shouldn't matter here.  How often do you actually get inside this if statement?

---

*[msg/PositionsStamped.msg, line 3 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq63ntkc73hecY6Zx6:-KjxfQFBl-nu1-A3FeQ9:bsle67y) ([raw file](https://github.com/palouserobosub/robosub/blob/7b42431f63ba69560e3efcb817ec64f915347430/msg/PositionsStamped.msg#L3)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Yes, and I'm assuming it was implemented with the localization system. What it actually breaks is a tool within rosserial_client that builds message types. Why it fails is beyond me, but it appears to only fail for this message.
</blockquote></details>

Looks like @ryan-summers added this when he was first working on the hydrophone trilateration: https://github.com/PalouseRobosub/robosub/blame/dev/msg/PositionsStamped.msg
Anyways, it's fine for this to be deleted, it got deprecated by [Position.msg](https://github.com/PalouseRobosub/robosub/blob/dev/msg/Position.msg) and [PositionArrayStamped.msg](https://github.com/PalouseRobosub/robosub/blob/dev/msg/PositionArrayStamped.msg). But for the future Ryan, please do cleanup like this in a separate PR, it's much easier for reviewers to process.

---

*[msg/thruster.msg, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq6GygahjbeW3tMyO2:-Kjxhumfn_dTuayiax0B:b-u6yev1) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/msg/thruster.msg#L1)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Further comment, this won't cause any compatibility issues with the thruster driver. The message will contain a 32-bit precision float that will be casted to a double within the call to the setThrusterSpeed function. I don't see how that would cause any issues.
</blockquote></details>

Given that the values are indeed mapped to ints later, we really won't suffer from the loss in precision. :lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[firmware/led/src/led.ino, line 98 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq2Pe7Rmi3Dax9bXg_:-KjyS3dZP3xGuHvZ-5Hp:b-3uy4kk) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L98)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Why not use http://wiki.ros.org/rosserial/Overview/Logging? I understand that there's a not insignificant amount of overhead using rosserial logging, but it shouldn't matter here.  How often do you actually get inside this if statement?
</blockquote></details>

Pretty much never. If you guys really want it, I'll throw a log statement in here :P (There's no guarantee that the node will be connected though.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[firmware/led/src/led.ino, line 98 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq2Pe7Rmi3Dax9bXg_:-Kjyst3pMiUigEhIblIA:bgdws1l) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L98)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Pretty much never. If you guys really want it, I'll throw a log statement in here :P (There's no guarantee that the node will be connected though.)
</blockquote></details>

ok thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[firmware/led/src/led.ino, line 66 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-KjxlvGNKDl1AWNIbkj2:-Kk8arJxsTvkUNTx78qJ:b-15s1le) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L66)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

This is kinda a weird way to express this logic. Not necessary, but I'd prefer to have it broken up into multiple steps so it's more clear (i.e. separate the averaging logic from the scaling and the minimum).
</blockquote></details>

Would it be better to just add a parenthesis so it read
(total / msg.data_length) * 180.0 + min

---

*[firmware/led/src/led.ino, line 85 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-KjxkM1XI9tFXjbId2Gi:-Kk8b-WNrniZoDvwmU_C:b-nxochf) ([raw file](https://github.com/palouserobosub/robosub/blob/798c6f8192d93c16df923f3fde8635ba4e3941b7/firmware/led/src/led.ino#L85)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Just commenting, for future revs of the board we should try to use the hardware PWM pins if possible, or at least have a separate PWM pin breakout for this use case.
</blockquote></details>

Agreed. I didn't plan on actually using a PWM on these. It is supposed to be for neopixel control. This was mainly a hack.

---

*[msg/PositionsStamped.msg, line 3 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq63ntkc73hecY6Zx6:-Kk8bAL239B7SJVVffd4:b-4gor3o) ([raw file](https://github.com/palouserobosub/robosub/blob/7b42431f63ba69560e3efcb817ec64f915347430/msg/PositionsStamped.msg#L3)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Looks like @ryan-summers added this when he was first working on the hydrophone trilateration: https://github.com/PalouseRobosub/robosub/blame/dev/msg/PositionsStamped.msg
Anyways, it's fine for this to be deleted, it got deprecated by [Position.msg](https://github.com/PalouseRobosub/robosub/blob/dev/msg/Position.msg) and [PositionArrayStamped.msg](https://github.com/PalouseRobosub/robosub/blob/dev/msg/PositionArrayStamped.msg). But for the future Ryan, please do cleanup like this in a separate PR, it's much easier for reviewers to process.
</blockquote></details>

Gotcha!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[msg/PositionsStamped.msg, line 3 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Kjq63ntkc73hecY6Zx6:-KnQa1i5qlksaRZ9ypE0:bocnbsv) ([raw file](https://github.com/palouserobosub/robosub/blob/7b42431f63ba69560e3efcb817ec64f915347430/msg/PositionsStamped.msg#L3)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Gotcha!
</blockquote></details>

Mind marking this as done so that we can merge in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-KnugIApiWxS7S4DJlvQ:-KnugIApiWxS7S4DJlvR:bbgmq13) (no related file):*
This PR seems to undo the thruster channel tweaks made in 2e427426ad356ccde64946d843a61c5cf0523558, need to test on hardware to see if this is ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-KnugIApiWxS7S4DJlvQ:-KoSezHvEJh_e8E84Tso:b-kvlhd4) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

This PR seems to undo the thruster channel tweaks made in 2e427426ad356ccde64946d843a61c5cf0523558, need to test on hardware to see if this is ok.
</blockquote></details>

Why is this modifying thrusters at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-KnugIApiWxS7S4DJlvQ:-KoSs2_SdffAA_VzMtJC:b620aw6) (no related file):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why is this modifying thrusters at all?
</blockquote></details>

Looks like some thruster changes got added to this branch unintentionally (or the thruster mappins changed in a different PR and I messed something up? :P) I'll revert them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-KnugIApiWxS7S4DJlvQ:-Kq1jBgrJc79mOCSGdIQ:b-44rmpg) (no related file):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Looks like some thruster changes got added to this branch unintentionally (or the thruster mappins changed in a different PR and I messed something up? :P) I'll revert them
</blockquote></details>

Changes still persist as of r3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by irwineffect** [comment]
reopening on master base

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Ku_redSdNcrO-wd2QkW:-Ku_redTBfsez0FIyfUW:btukh8t) (no related file):*
@ryan-summers per our converstation yesterday, can we cut out the thruster message logic and instead have the node just take a pwm percentage from 0-100% duty cycle?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by irwineffect** [comment]
I've just rebased the LED code onto the latest version of master, squashed/modified @ryan-summers's commits affecting yaml and msg files. Also modified firmware to listen to generic `/led` topic instead of the `/thruster` topic

**Comment by skallaher** [comment]
Reviewed 1 of 4 files at r1, 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-Ku_redSdNcrO-wd2QkW:-L5-hi-4gGcNaDCT3EVI:brxp9sq) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

@ryan-summers per our converstation yesterday, can we cut out the thruster message logic and instead have the node just take a pwm percentage from 0-100% duty cycle?
</blockquote></details>

Sounds good.

---

*[firmware/led/src/led.ino, line 67 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-L4S28y02fuFupOod6z6:-L4S28y02fuFupOod6z7:body3r3) ([raw file](https://github.com/palouserobosub/robosub/blob/23b6bfa7b56167ec730fcde3fcaa02b45df2b07a/firmware/led/src/led.ino#L67)):*
> ```cpp
>      * Calculate the pwm duty cycle.
>      */
> ```

Extra newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by irwineffect** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[firmware/led/src/led.ino, line 67 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-L4S28y02fuFupOod6z6:-L5-uHayuyShRNOjJCkW:bb7f2mf) ([raw file](https://github.com/palouserobosub/robosub/blob/23b6bfa7b56167ec730fcde3fcaa02b45df2b07a/firmware/led/src/led.ino#L67)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Extra newline
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by ryan-summers** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252#-:-L5-v8HIuMoHcTuozsZJ:bnfp4nl)*

**Comment by ryan-summers** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/252)*

**Pull request merged**
