### PR TITLE
Mike/nav channel task

### PR DESCRIPTION
**Pull request by Sindorman**
Solves issue PalouseRobosub/robosub#305
- Modified `Subscribestate.py`, changed it so it passes `userdata`. Got rid of old way - it was accessing private data of super class. Changed `start_switch.py` accordingly to accept `userdata`;

- In `Smach_buoy` Start Switch was moved into main, so it no longer requires it to run as part of High State machine;

- Added Start Switch to `smach_gate.py `and `smach_nav_channel.py`;

- Renamed `util_states.py` into `gate_util.py`;

- Modified `gate_util.py` to make it more generic for labels, and changed use of `userdata`;

- Modified `smach_buoy.py` to accept `userdata`(required!). 
  Note - now every state that inherits from `SubscribeState.py` **MUST** accept `userdata` in it's callback.

- Deleted old AI files such as `buoy_task.py`.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/309)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[param/ai.yaml, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJFQXqaMWCnUcd3Xii:-KwJFQXqaMWCnUcd3Xij:bhr0civ) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/param/ai.yaml#L16)):*
> ```YAML
>         errorGoal: 0.1
>         yaw_speed_factor: -25.0
> # contains variables for blind_movement.py
> ```

This comment is misleading

---

*[src/ai/gate_util.py, line 18 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJH0NNJaIxuZgu2WBy:-KwJH0NNJaIxuZgu2WBz:bm4c12j) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L18)):*
> ```Python
>         self.vision_label = vision_label
>         self._poll_rate = rospy.Rate(poll_rate)
>         self.forward_error = rospy.get_param("ai/move_to_gate/forward_error")
> ```

This parameter is not usefully named for anyone who doesn't know what it is doing. I would say use `ai/move_to_gate/forward_speed`.

---

*[src/ai/gate_util.py, line 27 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJHHuZy-MQ4fhkQe0k:-KwJHHuZy-MQ4fhkQe0l:bgnk10z) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L27)):*
> ```Python
> 
>         detections = filterByLabel(detectionArray.detections,
>             self.vision_label)
> ```

Please line this line up with the previous line's `(`. Also check the rest of the code for these.

---

*[src/ai/gate_util.py, line 64 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJImnkp2D0d015V4WO:-KwJImnkp2D0d015V4WP:b-7ryjgs) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L64)):*
> ```Python
> 
>         c.yawLeftRelative(currentYaw)
>         rospy.loginfo("objects detected: {}".format(len(vision_result)))
> ```

This is more of a debug message. Same for the following output.

---

*[src/ai/gate_util.py, line 75 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJJ-TGUvoCrGoF21C1:-KwJJ-TGUvoCrGoF21C2:b-571ygi) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L75)):*
> ```Python
>             self.exit('1 post')
>         elif len(vision_result) == 2:
>             self.exit('2 posts')
> ```

What about if it is not of length 0, 1, or 2? I would recommend to either add a default case or make the last `elif` clause an `else` clause.

---

*[src/ai/gate_util.py, line 142 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJK7C3uLiwQ__TkPUF:-KwJK7C3uLiwQ__TkPUG:bejqw3t) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L142)):*
> ```Python
>             smach.StateMachine.add("LOST", lost(label),
>                 transitions={'1 post': 'SEARCH', 'none': 'LOST',
>                 '2 posts': 'SEARCH'},
> ```

Please line these lines up based upon their scope, as the `FLIP` state is below. This should be consistently done throughout the code.

---

*[src/ai/gate_util.py, line 180 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJL17xAjQq-KIBlsJo:-KwJL17xAjQq-KIBlsJp:b-ks70lu) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L180)):*
> ```Python
>         gateYPos = (vision_result[0].y + vision_result[1].y) / 2
> 
>         rospy.loginfo(("Gate X: {}\tGate Y: {}".format(gateXPos, gateYPos)))
> ```

Again, these are better suited as debug output.

---

*[src/ai/gate_util.py, line 237 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJMGRT8jeLGDNw2Jhm:-KwJMGRT8jeLGDNw2Jhn:bdfnp3l) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L237)):*
> ```Python
>         c.publish()
> 
> if __name__ == "__main__":
> ```

If you're just going to pass in main, you don't need it. Please remove these two lines.

---

*[src/ai/smach_nav_channel.py, line 35 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJO9IcaD4pdOAZNxJH:-KwJO9IcaD4pdOAZNxJI:bgcxhqf) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/smach_nav_channel.py#L35)):*
> ```Python
>                                   'lost': 'SEARCH_FOR_POSTS'})
> ```

There's an extra whitespace line here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/309)*

**Comment by Sindorman** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[param/ai.yaml, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJFQXqaMWCnUcd3Xii:-KwJVhxx0stQTth-Jz2j:b-ptxi4k) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/param/ai.yaml#L16)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This comment is misleading
</blockquote></details>

Changed it

---

*[src/ai/gate_util.py, line 64 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJImnkp2D0d015V4WO:-KwJS8RigDDVu-rQH0Ov:b-svdh3e) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L64)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This is more of a debug message. Same for the following output.
</blockquote></details>

Changed them as debug.

---

*[src/ai/gate_util.py, line 75 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJJ-TGUvoCrGoF21C1:-KwJRm9lGhl3RAvdRGmO:bjkdlrh) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L75)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

What about if it is not of length 0, 1, or 2? I would recommend to either add a default case or make the last `elif` clause an `else` clause.
</blockquote></details>

Agreed, but that would NEVER happen, as the logic above filters them just by 2 max! Changed to else

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/309)*

**Comment by Sindorman** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/ai/gate_util.py, line 18 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJH0NNJaIxuZgu2WBy:-KwJVlVyvXBkXVpsspbj:b-b9owae) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L18)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This parameter is not usefully named for anyone who doesn't know what it is doing. I would say use `ai/move_to_gate/forward_speed`.
</blockquote></details>

Renamed it

---

*[src/ai/gate_util.py, line 27 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJHHuZy-MQ4fhkQe0k:-KwJVmi3KxOmZL5AJhVm:b-orcnpi) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L27)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Please line this line up with the previous line's `(`. Also check the rest of the code for these.
</blockquote></details>

Fixed lining in every file, including smach_buoy.py

---

*[src/ai/gate_util.py, line 142 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJK7C3uLiwQ__TkPUF:-KwJVrLbecO0q3nM2Uap:bb6un1j) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L142)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Please line these lines up based upon their scope, as the `FLIP` state is below. This should be consistently done throughout the code.
</blockquote></details>

Done

---

*[src/ai/gate_util.py, line 180 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJL17xAjQq-KIBlsJo:-KwJVsmqkVLLmn9-3YhK:bb6cepr) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L180)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Again, these are better suited as debug output.
</blockquote></details>

Changed to debug

---

*[src/ai/gate_util.py, line 237 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJMGRT8jeLGDNw2Jhm:-KwJVuqo7uq8JPsQ9ONi:ba3dfob) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/gate_util.py#L237)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

If you're just going to pass in main, you don't need it. Please remove these two lines.
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/309)*

**Comment by Sindorman** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/ai/smach_nav_channel.py, line 35 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-KwJO9IcaD4pdOAZNxJH:-KwJW6_Xs8QcmgMQlUuW:ba3dfob) ([raw file](https://github.com/palouserobosub/robosub/blob/5b0ca69f41999cb69598e52e29e5fa4a6ac261ac/src/ai/smach_nav_channel.py#L35)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

There's an extra whitespace line here.
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/309)*

**Comment by skallaher** [comment]
You've performed a merge. Please undo this and perform a rebase instead.

---

Review status: 5 of 11 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-:-KwJ_YSwTPJQ-3TT1Rp3:bc3nong)*

**Comment by Sindorman** [comment]
That was accidental from other branch. Let med redo.

---

Review status: 5 of 11 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/309#-:-KwJa4RyFQQhCa-EmSkH:bqkqi48)*

**Pull request closed without merging**
