### PR TITLE
Pool Test (2/12/17) changes

### PR DESCRIPTION
**Pull request by bkallaher**
Thruster Ramp Script and buoyancy update

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/186)

### CODE REVIEW

**Comment by skallaher** [comment]
Everything is failing on Travis.

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/ramp_test.sh, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/186#-KcpR4oy-iigBSZkhhZl:-KcpR4oy-iigBSZkhhZm:b-sue627) ([raw file](https://github.com/palouserobosub/robosub/blob/06fa35f3a0731dce48c91c782a677b7e763582f7/scripts/ramp_test.sh#L1)):*
> ```Shell
> 
> ```

Comments please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/186)*

**Comment by irwineffect** [comment]
:lgtm:w

---

Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/186#-:-KcsjgHCPjEx3hEIbabg:bg7igna)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/186)*

**Comment by irwineffect** [comment]
@ryan-summers we need you on this PR

**Comment by ryan-summers** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/186#-:-KctzhkAqYru33UrDgsT:bnfp4nl)*

**Comment by irwineffect** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/186#-:-Kcu7ncAxamyvB3zYCD1:bnfp4nl)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/186#-:-Kd3C5Tc5fFhhAv_8XP5:bnfp4nl)*

**Pull request merged**
