### PR TITLE
Added macros and build requirements to build on kinetic

### PR DESCRIPTION
**Pull request by bkallaher**
Support for kinetic has been added for the vision code. It's just a few extra lines. This should be tested on a Ubuntu 16.04 or Mint 18 OS on top of the usual tests.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/135)

### CODE REVIEW

**Comment by irwineffect** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-KaEAOgnb9JUmSJbsWra:-KaEAOgnb9JUmSJbsWrb:bcw9r9p) ([raw file](https://github.com/palouserobosub/robosub/blob/4a0c2f8e7fc8a8364f24a93ece47e89788197c8b/CMakeLists.txt#L15)):*
> ```CMake
> ## if COMPONENTS list like find_package(catkin REQUIRED COMPONENTS xyz)
> ## is used, also find other catkin packages
> if ("$ENV{ROS_DISTRO}" STRGREATER "indigo")
> ```

can we have comments saying which part of this if/else block is for kinetic and which is for indigo?

---

*[src/vision/image_publisher.cpp, line 5 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-KaEA7MvWXBs7c54eCGW:-KaEA7MvWXBs7c54eCGX:bgv60b5) ([raw file](https://github.com/palouserobosub/robosub/blob/4a0c2f8e7fc8a8364f24a93ece47e89788197c8b/src/vision/image_publisher.cpp#L5)):*
> ```cpp
> #include <image_transport/image_transport.h>
> #include <opencv2/highgui/highgui.hpp>
> #if ROS_VERSION_MINIMUM(1, 12, 0)
> ```

can we add comments describing what exactly is going on here? Does 1.12.0 correspond to kinetic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/135)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-KaEAOgnb9JUmSJbsWra:-KaECdzX1vI_tiVDWU83:bazyd9d) ([raw file](https://github.com/palouserobosub/robosub/blob/4a0c2f8e7fc8a8364f24a93ece47e89788197c8b/CMakeLists.txt#L15)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

can we have comments saying which part of this if/else block is for kinetic and which is for indigo?
</blockquote></details>

Yeah I can do that.

---

*[src/vision/image_publisher.cpp, line 5 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-KaEA7MvWXBs7c54eCGW:-KaECjR5Wkn5_7Di_AmF:badjtm1) ([raw file](https://github.com/palouserobosub/robosub/blob/4a0c2f8e7fc8a8364f24a93ece47e89788197c8b/src/vision/image_publisher.cpp#L5)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

can we add comments describing what exactly is going on here? Does 1.12.0 correspond to kinetic?
</blockquote></details>

That is correct. Should I add a comment to every instance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/135)*

**Comment by skallaher** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-KaEAOgnb9JUmSJbsWra:-KaEg7nPKbmEBPzYpqmu:b-gn9ss2) ([raw file](https://github.com/palouserobosub/robosub/blob/4a0c2f8e7fc8a8364f24a93ece47e89788197c8b/CMakeLists.txt#L15)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Yeah I can do that.
</blockquote></details>

Would you not be able to just have the `cv_bridge` and `cv3_bridge` in their own `find_packages`? This would greatly reduce redundancy here.

---

*[src/vision/image_publisher.cpp, line 5 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-KaEA7MvWXBs7c54eCGW:-KaEfo0hInaFUDKiX1FK:b-bbuwqm) ([raw file](https://github.com/palouserobosub/robosub/blob/4a0c2f8e7fc8a8364f24a93ece47e89788197c8b/src/vision/image_publisher.cpp#L5)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

That is correct. Should I add a comment to every instance?
</blockquote></details>

Also, "Followin"and "#f"... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/135)*

**Comment by bkallaher** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 15 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-KaEAOgnb9JUmSJbsWra:-KaEiKhqKzJLzYgXGYCw:b-apf48y) ([raw file](https://github.com/palouserobosub/robosub/blob/4a0c2f8e7fc8a8364f24a93ece47e89788197c8b/CMakeLists.txt#L15)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Would you not be able to just have the `cv_bridge` and `cv3_bridge` in their own `find_packages`? This would greatly reduce redundancy here.
</blockquote></details>

They cannot be moved out of this find_package as this defines the components that are required by catkin. This can only be in one location in the CMakeLists file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/135)*

**Comment by bkallaher** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vision/image_publisher.cpp, line 5 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-KaEA7MvWXBs7c54eCGW:-KaEiYE1cZLNewsBfeXY:b-886gsx) ([raw file](https://github.com/palouserobosub/robosub/blob/4a0c2f8e7fc8a8364f24a93ece47e89788197c8b/src/vision/image_publisher.cpp#L5)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Also, "Followin"and "#f"... 
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/135)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-:-KaEuD-mEcvKgTgOtuLF:bnfp4nl)*

**Comment by irwineffect** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/135#-:-KaEug0aKVY3BzsnDPHQ:bnfp4nl)*

**Comment by irwineffect** [comment]
Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/135)*

**Pull request merged**
