### PR TITLE
Updates the depth sensor firmware

### PR DESCRIPTION
**Pull request by ryan-summers**
This brings the repository in line with what is actually programmed onto the depth sensor.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/206)

### CODE REVIEW

**Comment by bkallaher** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/make, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/206#-KeRIRSozNXgQrdKVujx:-KeRIRSp2WSBk9BDDCce:b-3r73y2) ([raw file](https://github.com/palouserobosub/robosub/blob/6626acc699c4d80af79abfa40b3e9cf0d378c944/tools/make#L16)):*
> ```
>         echo -e "[\033[0;32mFound\033[0m]"
>         cd $i/..
>         
> ```

Why is this back in make?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/206)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/206#-:-KeRkNewbsnJkmNy4nfU:bnfp4nl)*

**Comment by irwineffect** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/206)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/make, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/206#-KeRIRSozNXgQrdKVujx:-KeRp9907mq0Lxt5UY05:bewmd6w) ([raw file](https://github.com/palouserobosub/robosub/blob/6626acc699c4d80af79abfa40b3e9cf0d378c944/tools/make#L16)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Why is this back in make?
</blockquote></details>

What specifically are you referring to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/206)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/make, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/206#-KeRIRSozNXgQrdKVujx:-KeRpMiGXP1Q4XdCIpOC:b-l5332) ([raw file](https://github.com/palouserobosub/robosub/blob/6626acc699c4d80af79abfa40b3e9cf0d378c944/tools/make#L16)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

What specifically are you referring to?
</blockquote></details>

All the changes. This is all covered by the changes you made in the CMakeLists a while ago to build the firmware. i.e these changes aren't needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/206)*

**Comment by ryan-summers** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/make, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/206#-KeRIRSozNXgQrdKVujx:-KeUINDbHfhk78P40PEf:b-yffct6) ([raw file](https://github.com/palouserobosub/robosub/blob/6626acc699c4d80af79abfa40b3e9cf0d378c944/tools/make#L16)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

All the changes. This is all covered by the changes you made in the CMakeLists a while ago to build the firmware. i.e these changes aren't needed.
</blockquote></details>

Ah good point, I had forgotten I'd done that honestly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/206)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/206)*

**Pull request merged**
