### PR TITLE
math header file

### PR DESCRIPTION
**Pull request by lucy9tran**
Need to know if I need to add or remove anything.
I will create a .cpp file and edit other files once I have feedback.
Issue #228 

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/235)

### CODE REVIEW

**Comment by bkallaher** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLK_H06Qfiwg681Xcp:-KhLK_H06Qfiwg681Xcq:b-k445wb) (no related file):*
This really shouldn't be in a pull request yet...

---

*[src/utility/math.hpp, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLJ1n4JRcnMY1ELK7g:-KhLJ1n4JRcnMY1ELK7h:b-mwrq71) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L1)):*
> ```cpp
> #ifndef MATH_HPP
> ```

Trailing whitespace every where!

---

*[src/utility/math.hpp, line 11 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLJ85VC6IRJWmJ5Rno:-KhLJ85VC6IRJWmJ5Rnp:b-3lw10a) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L11)):*
> ```cpp
> #include <limits>
> 
> //Not sure which are exactly needed. 
> ```

These types of comments should not be in source code

---

*[src/utility/math.hpp, line 15 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLItSwd-c0GCQRCsKa:-KhLItSxq7cLrucVTf9p:besjjab) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L15)):*
> ```cpp
> 
> //Control System: control_system.h
> #include "geometry_msgs/Quaternion.h" 
> ```

Message types should not be in here

---

*[src/utility/math.hpp, line 25 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLJi_GbkKfen8NHS0A:-KhLJi_H6fY4oidD0K0g:b-udjkhe) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L25)):*
> ```cpp
> using namespace Eigen; //linear algebra
> 
> namespace rs::math 
> ```

should be robosub::math and should encapsulate the entire file.

---

*[src/utility/math.hpp, line 27 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLIzxni0whKrEq5sS8:-KhLIzxni0whKrEq5sS9:be29abj) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L27)):*
> ```cpp
> namespace rs::math 
> {
> 		/*Defines conversion scale for converting between radians and degrees*/
> ```

Convert these tabs to spaces

---

*[src/utility/math.hpp, line 47 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLJIlnAJODnnQd5Wi9:-KhLJIlnAJODnnQd5WiA:b-vcsomk) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L47)):*
> ```cpp
> /*Define custom types for using Eigen*/
> //Control System: control_system.h : vectors 
> using Vector6d = Matrix<double, 6, 1>;
> ```

These should be typedef not using statements

---

*[src/utility/math.hpp, line 61 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLK4XH4WFHywdDANPF:-KhLK4XH4WFHywdDANPG:bgibghc) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L61)):*
> ```cpp
> 
> //Localization: control_system
> double ControlSystem::wraparound(double x, double min, double max);
> ```

You should not be namespacing into the control system

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/235)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLK_H06Qfiwg681Xcp:-KhOefHKMaJhcLn8U0ll:bfiq22d) (no related file):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

This really shouldn't be in a pull request yet...
</blockquote></details>

What Brandon means to say is that we are glad you are committing code and asking all these questions, but for organizational purposes, it would be better to place these discussions and questions on the issue itself. By convention, we like to create pull requests when the code is actually ready to be merged in.

No need to delete this pull request, but let's continue the discussion on #228. We can still see the code you are committing and pushing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/235)*

**Comment by skallaher** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[src/utility/math.cpp, line 5 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhPaGARhLAdKe4MsFCw:-KhPaGARhLAdKe4MsFCx:btj0iq7) ([raw file](https://github.com/palouserobosub/robosub/blob/5ea4b64f5deb12cc15b9e62d7918b2cd110d49b7/src/utility/math.cpp#L5)):*
> ```cpp
> namespace robosub::math
> {
>   //Localization: control_system
> ```

I don't think there is a reason to comment on where these came from as you should remove them from there and replace them with calls to this function instead.

---

*[src/utility/math.cpp, line 19 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhPa57bqlH3i6CZoodY:-KhPa57bqlH3i6CZoodZ:boi18pw) ([raw file](https://github.com/palouserobosub/robosub/blob/5ea4b64f5deb12cc15b9e62d7918b2cd110d49b7/src/utility/math.cpp#L19)):*
> ```cpp
>   
>   //Control System: rotation_engine
> 	double asind(double x)
> ```

You have a tab here. These should be spaces and we typically indent by 4 spaces. Talk to @irwineffect on how you can best fix this.

---

*[src/utility/math.cpp, line 174 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhPc-qsHayWu-1WkmRX:-KhPc-qsHayWu-1WkmRY:btbupuv) ([raw file](https://github.com/palouserobosub/robosub/blob/5ea4b64f5deb12cc15b9e62d7918b2cd110d49b7/src/utility/math.cpp#L174)):*
> ```cpp
>               * svd.matrixU().adjoint();
>   }
> }
> ```

Where are the declarations of the euclidian distance functions?

---

*[src/utility/math.hpp, line 19 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhPbIIi334u8iYCR5OA:-KhPbIIi334u8iYCR5OB:b-7a8715) ([raw file](https://github.com/palouserobosub/robosub/blob/5ea4b64f5deb12cc15b9e62d7918b2cd110d49b7/src/utility/math.hpp#L19)):*
> ```cpp
> 	/*Defines conversion scale for converting between radians and degrees*/
> 	//Control System: control_system.h ; vectors, rotation_engine.h
> 	static constexpr double pi = 3.1415;
> ```

`pi` should be in all caps as it's a constant.

---

*[src/utility/math.hpp, line 28 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhPb2Yv1GueTftUulH3:-KhPb2Ywhv6fjWZBNX4s:b-peivez) ([raw file](https://github.com/palouserobosub/robosub/blob/5ea4b64f5deb12cc15b9e62d7918b2cd110d49b7/src/utility/math.hpp#L28)):*
> ```cpp
> 	typedef Vector6 = Matrix<int, 6, 1>;
> 	typedef Vector12d = Matrix<double, 12, 1>;
> 	typedef Matrix6d = Matrix<double, 6, 6>;
> ```

I believe that the localization system also uses Vector7d and possibly Vector9d as well. Take a look at #226 and some of the typedefs used by @BigDCross.

---

*[src/utility/math.hpp, line 44 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhPamgIR37YhRAZEsXW:-KhPamgIR37YhRAZEsXX:bpzac8s) ([raw file](https://github.com/palouserobosub/robosub/blob/5ea4b64f5deb12cc15b9e62d7918b2cd110d49b7/src/utility/math.hpp#L44)):*
> ```cpp
> 	Vector3d ir3D(Matrix3d R);
> 	MatrixXd pinv(const MatrixXd &a,
> 	double epsilon = std::numeric_limits<double>::epsilon());
> ```

Moving these four functions makes the rotation engine obsolete, may want to ask @irwineffect about that one. In addition, line 44 should be indented as it is a continuation of line 43.

---

*[src/utility/math.hpp, line 49 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhPbQtNW5DmpJH2Gcc0:-KhPbQtNW5DmpJH2Gcc1:bxex3c9) ([raw file](https://github.com/palouserobosub/robosub/blob/5ea4b64f5deb12cc15b9e62d7918b2cd110d49b7/src/utility/math.hpp#L49)):*
> ```cpp
> 	double euclidian_distance(double x, double y, double z);
> }
> ```

This new line is not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/235)*

**Comment by skallaher** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[src/utility/math.cpp, line 5 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhPaGARhLAdKe4MsFCw:-Kh_kZ7T6L12stpUyubd:b-4qhbll) ([raw file](https://github.com/palouserobosub/robosub/blob/5ea4b64f5deb12cc15b9e62d7918b2cd110d49b7/src/utility/math.cpp#L5)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I don't think there is a reason to comment on where these came from as you should remove them from there and replace them with calls to this function instead.
</blockquote></details>

Note these in the header file as well.

---

*[src/utility/math.cpp, line 3 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-Kh_gPMFb1Xp68QzKwic:-Kh_gPMGWzuAGYrFkriJ:b-qja3qx) ([raw file](https://github.com/palouserobosub/robosub/blob/30412ecc35b26a6be1364eb37bbf9b13f6d0fed6/src/utility/math.cpp#L3)):*
> ```cpp
> #include "math.hpp"
> 
> #include <cmath>;
> ```

There is an unnecessary semicolon here.

---

*[src/utility/math.cpp, line 38 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-Kh_i8ih9sLovXW1BMZw:-Kh_i8iiFhLpBCir4ydU:b-7r5xuy) ([raw file](https://github.com/palouserobosub/robosub/blob/30412ecc35b26a6be1364eb37bbf9b13f6d0fed6/src/utility/math.cpp#L38)):*
> ```cpp
>     return sin(x * _PI_OVER_180);
>   }
>   
> ```

Some trailing whitespace here

---

*[src/utility/math.hpp, line 47 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLJIlnAJODnnQd5Wi9:-Kh_jpcGC68vW285iI-0:b6ecyrz) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L47)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

These should be typedef not using statements
</blockquote></details>

In regards to this, I found [this reference](http://en.cppreference.com/w/cpp/language/typedef) specifying that the usage of typedef is of the form of `typedef [type] [new type name];`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/235)*

**Comment by ryan-summers** [comment]
Review status: 0 of 5 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[src/utility/math.hpp, line 25 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLJi_GbkKfen8NHS0A:-KiwlySdtDZNxK3j0KtL:b-pc08c1) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L25)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

should be robosub::math and should encapsulate the entire file.
</blockquote></details>

Actually, according to serial.hpp, we're using rs, not robosub

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/235)*

**Comment by skallaher** [comment]
Review status: 0 of 5 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[src/utility/math.hpp, line 25 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/235#-KhLJi_GbkKfen8NHS0A:-KiwqCtSa5R3iIBf0RYQ:b-z72wr1) ([raw file](https://github.com/palouserobosub/robosub/blob/6fd9e45c3b507b487fb12c336bca28d3d69d85e7/src/utility/math.hpp#L25)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Actually, according to serial.hpp, we're using rs, not robosub
</blockquote></details>

The control_system.h file conflicts with this claim. There is no current standard and `robosub` is more explicit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/235)*

**Pull request closed without merging**
