### PR TITLE
Hydrophone Bridge Multitracking + Status Update

### PR DESCRIPTION
**Pull request by ryan-summers**
Updates the hydrophone bridge to support new firmware for multi frequency tracking and status output.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/412)

### CODE REVIEW

**Comment by ryan-summers** [comment]
Note this needs https://github.com/PalouseRobosub/robosub_msgs/pull/1

**Review by daymare — APPROVED** [review]
What happens if we reconfigure the zybo to look at different frequencies? We would have to change the list of allowed frequencies here too right?

Besides my comments in the other hydrophone_bridge PR this looks good to me.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/412#-:-LGvc6_h6IAH8WOfFYaX:b-gct3bi)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by daymare — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/412#-:-LGvczb2CAtY4P46X-0A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Sindorman — CHANGES_REQUESTED** [review]
There are few Linter changes that you need to fix. Please fix them and we can merge it!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/412#-:-LHfS16HAizEYOL5l-Jn:bup4chu)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Sindorman — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/412#-:-LHgi7-M4eaao2geyn9l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
