### PR TITLE
Stereo Calibration Update

### PR DESCRIPTION
**Pull request by skallaher**
Adds in circular cropping of the input images to generate better calibration data as well as a launch file to quickly start up the undistortion node for ease of use. There may still need to be changes to this, but as it stands everything seems to be doing well.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/245)

### CODE REVIEW

**Comment by bkallaher** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/245#-:-KiBmLHufPbA2Dyes-Kq:bnfp4nl)*

**Comment by irwineffect** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[launch/undistortion.launch, line 6 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/245#-KjxtFnoyF7A7YCPzjob:-KjxtFnoyF7A7YCPzjoc:b3owzj3) ([raw file](https://github.com/palouserobosub/robosub/blob/4a84b23611f9eeedf34de20cf3262513f49da478/launch/undistortion.launch#L6)):*
> ```XML
> 	<param name="stereo_calib_file" value="$(find robosub)/src/vision/calib/stereo_out_camera_data.xml"/>
> 	<param name="bottom_calib_file" value="$(find robosub)/src/vision/calib/out_camera_data.xml"/>
> 	<node pkg="robosub" type="undistortion" name="undistortion" required="True"/>
> ```

These should be spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/245)*

**Comment by irwineffect** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/245#-:-KjxujaBnZzjvrMVnZhn:bnfp4nl)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/245)*

**Pull request merged**
