### PR TITLE
Update to Depth Sensor firmware

### PR DESCRIPTION
**Pull request by ryan-summers**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/174)

### CODE REVIEW

**Comment by skallaher** [comment]
It looks like the linter isn't properly ignoring the Float32Stamped header.

**Comment by irwineffect** [comment]
Reviewed 7 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[firmware/depth/src/depth.ino, line 2 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-Kbr5KiaE3wlmaOpPPac:-Kbr5KiaE3wlmaOpPPad:bno2cmj) ([raw file](https://github.com/palouserobosub/robosub/blob/0c2ff008b27a80649f36705d7f66d1575e5600ba/firmware/depth/src/depth.ino#L2)):*
> ```Arduino
> /*
>  * Author: Zachary Pratt
> ```

can you remove the author line?

---

*[firmware/depth/src/depth.ino, line 78 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-Kbr4odsFTNjmp2o6XM9:-Kbr4odtAPGxihhBA6BD:bx7hdtb) ([raw file](https://github.com/palouserobosub/robosub/blob/0c2ff008b27a80649f36705d7f66d1575e5600ba/firmware/depth/src/depth.ino#L78)):*
> ```Arduino
>     {
>         rate = 10;
>         n.loginfo("Failed to load depth rate. Defaulting to 10Hz.");
> ```

can we make this a warning?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174)*

**Comment by ryan-summers** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[firmware/depth/src/depth.ino, line 2 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-Kbr5KiaE3wlmaOpPPac:-Kbs6CfOcoWgfX5xmTh1:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/0c2ff008b27a80649f36705d7f66d1575e5600ba/firmware/depth/src/depth.ino#L2)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

can you remove the author line?
</blockquote></details>

Done.

---

*[firmware/depth/src/depth.ino, line 78 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-Kbr4odsFTNjmp2o6XM9:-Kbs6BONedwZHWbAP997:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/0c2ff008b27a80649f36705d7f66d1575e5600ba/firmware/depth/src/depth.ino#L78)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

can we make this a warning?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-:-KbwB_hD1Bj1iZZZQmJf:bnfp4nl)*

**Comment by dcrossman** [comment]
Reviewed 4 of 9 files at r1, 1 of 2 files at r2, 6 of 308 files at r4.
Review status: 9 of 310 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-Kc591ybhm6rfiIWa56R:-Kc591yc3D2ndZ9dPm3j:borfq8w) (no related file):*
I'm seeing a lot of binaries in here. Are they necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174)*

**Comment by bkallaher** [comment]
Review status: 9 of 310 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-Kc591ybhm6rfiIWa56R:-Kc5SOqXTpA1Ocq-5GBG:bk9nx41) (no related file):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

I'm seeing a lot of binaries in here. Are they necessary?
</blockquote></details>

There must be a way to write a script  that will generate all of these files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174)*

**Comment by ryan-summers** [comment]
Review status: 9 of 310 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-Kc591ybhm6rfiIWa56R:-Kc5zQvaNoz7CdKGlfMu:b-no44fi) (no related file):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

There must be a way to write a script  that will generate all of these files.
</blockquote></details>

So I think I'm going to revert this commit because I don't like the structure of it. How could we make it so that the supplemental libraries can be built without storing them in the repos? I'll look into some other options.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174)*

**Comment by bkallaher** [comment]
Review status: 9 of 310 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-Kc591ybhm6rfiIWa56R:-Kc62mY0og9_k6x-x0kw:b-35weiu) (no related file):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

So I think I'm going to revert this commit because I don't like the structure of it. How could we make it so that the supplemental libraries can be built without storing them in the repos? I'll look into some other options.
</blockquote></details>

I was thinking just write a script to run that will build them. I.e. put the commands that you ran to build them in a script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174)*

**Comment by bkallaher** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 3 of 308 files at r4, 2 of 300 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-:-KcdHe1GVTibK4tw1Qdm:bnfp4nl)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-Kcu1662k04rN_4GdNrh:-Kcu1663PKsOufPU0WiS:b3q68q9) (no related file):*
Need to figure out how to make platformio search for the arduino generated ros headers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174)*

**Comment by dcrossman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/174#-:-Kdy8hYLxKIUGQrJ3v4t:bnfp4nl)*

**Pull request merged**
