### PR TITLE
Addition of depth sensor code

### PR DESCRIPTION
**Pull request by ryan-summers**
Adds in the Depth Sensor code to the repository.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/159)

### CODE REVIEW

**Comment by dcrossman** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[firmware/sensor/src/depth.ino, line 9 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2EQtE-jqOt-sMQh0P:-Kb2EQtE-jqOt-sMQh0Q:b-m9746v) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L9)):*
> ```Arduino
>  * Originally created to test effects of outside magnetic fields on
>  * the orientation data out BNO055.
>  */
> ```

This whole comment is wrong. The curse of copy paste strikes.

---

*[firmware/sensor/src/depth.ino, line 18 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2Ei4lbaFNL4Xnb14E:-Kb2Ei4lbaFNL4Xnb14F:bb7i4vh) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L18)):*
> ```Arduino
> #include <Wire.h>
> 
> MS5837 ds;
> ```

How about depth_sensor instead of ds? Even if it's pretty clear already it's best to be totally clear.

---

*[firmware/sensor/src/depth.ino, line 26 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2FtSOTiYb6AI40jjy:-Kb2FtSPVlGhJr0oYAu2:b-is56m4) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L26)):*
> ```Arduino
> ros::Publisher depth_data_pub("depth", &depth_msg);
> 
> void setup() {
> ```

Move { to new line.

---

*[firmware/sensor/src/depth.ino, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2F347fDptwRlfkD2w:-Kb2F347fDptwRlfkD2x:b-3353su) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L33)):*
> ```Arduino
>     ds.init();
>     ds.setFluidDensity(997.0f); // fluid density of freshwater
>     delay(1000);
> ```

Could you make a quick comment explaining why these delays are necessary?

---

*[firmware/sensor/src/depth.ino, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2F9o2iGA4xR9c_W3I:-Kb2F9o2iGA4xR9c_W3J:b-i485s8) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L40)):*
> ```Arduino
> {
>     n.loginfo("Reading Depth Sensor.");
>     ds.read();
> ```

You should probably check if this read has failed or not.

---

*[firmware/sensor/src/depth.ino, line 48 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2FvVM97F-eVBJD_Of:-Kb2FvVNQB8v91ct79uN:b7yp9ag) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L48)):*
> ```Arduino
>     n.spinOnce();
> 
>     delay(100);
> ```

I don't know if rosserial supports ros::Rate but it would be best to use that instead of a raw delay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by bkallaher** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[firmware/sensor/src/depth.ino, line 9 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2EQtE-jqOt-sMQh0P:-Kb2GWo90NfpKO40_Uxi:b-6a4c8a) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L9)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

This whole comment is wrong. The curse of copy paste strikes.
</blockquote></details>

:knife: 

---

*[firmware/sensor/src/depth.ino, line 26 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2FtSOTiYb6AI40jjy:-Kb2HKHyxWM2MJ98cZB8:b-wf0mzx) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L26)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

Move { to new line.
</blockquote></details>

:arrow_down: 

---

*[firmware/sensor/src/depth.ino, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2F347fDptwRlfkD2w:-Kb2HMajlaGfECvfvD2U:b-3an9yw) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L33)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

Could you make a quick comment explaining why these delays are necessary?
</blockquote></details>

More :information_source: 

---

*[firmware/sensor/src/depth.ino, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2F9o2iGA4xR9c_W3I:-Kb2Hbl8gZGaZsKjpjTL:b-e2p2wu) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L40)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

You should probably check if this read has failed or not.
</blockquote></details>

:interrobang: 

---

*[firmware/sensor/src/depth.ino, line 48 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2FvVM97F-eVBJD_Of:-Kb2HkECl1GfiHm43DAU:bi8066z) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L48)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

I don't know if rosserial supports ros::Rate but it would be best to use that instead of a raw delay.
</blockquote></details>

:poop: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by irwineffect** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[firmware/sensor/src/depth.ino, line 44 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2IPDbVLLVid-zBzkY:-Kb2IPDbVLLVid-zBzkZ:bqro9lm) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L44)):*
> ```Arduino
>     depth_data_pub.publish(&depth_msg);
> 
>     n.loginfo("Spinning.");
> ```

This should be a debug message, we don't want to spam the logs (also logging messages is relatively expensive on arduino)

---

*[firmware/sensor/src/depth.ino, line 48 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2HkybtVhsKAgHxEM4:-Kb2HkybtVhsKAgHxEM5:bzclo1g) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L48)):*
> ```Arduino
>     n.spinOnce();
> 
>     delay(100);
> ```

we should load up the parameter "rates/depth" and make the delay configurable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by irwineffect** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by bkallaher** [comment]
Reviewed 1 of 3 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[firmware/sensor/src/depth_stamped.h, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb32cWDnaDmfLx0ru3z:-Kb32cWEwp2R4jhHT1pp:b-y49x0i) ([raw file](https://github.com/palouserobosub/robosub/blob/7f92fd148418d94f8b595254a0199fb8694af56b/firmware/sensor/src/depth_stamped.h#L1)):*
> ```objc
> #ifndef _ROS_robosub_depth_stamped_h
> ```

Was there no better way to get the message type on the arduino?

---

*[msg/depth_stamped.msg, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb31d4TFImds_mPWCyr:-Kb31d4TFImds_mPWCys:bhe80r1) ([raw file](https://github.com/palouserobosub/robosub/blob/7f92fd148418d94f8b595254a0199fb8694af56b/msg/depth_stamped.msg#L1)):*
> ```
> Header header
> ```

This message should probably be renamed to Float32Stamped with the float32 value changed to be named data

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by bkallaher** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by bkallaher** [comment]
Check the Linter.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-:-Kb33030ajS6miehQAHC:b-qooqi6)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[firmware/sensor/src/depth.ino, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2F347fDptwRlfkD2w:-Kb30a8JfZMIV9w1nITS:bne2l0c) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L33)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

More :information_source: 
</blockquote></details>

But I don't know why these delays are necessary...

---

*[firmware/sensor/src/depth.ino, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2F9o2iGA4xR9c_W3I:-Kb30lRvQHK9Pk3Guzt0:bupg2ad) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L40)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

:interrobang: 
</blockquote></details>

Read does not fail. It has a void return type.

---

*[firmware/sensor/src/depth.ino, line 48 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2FvVM97F-eVBJD_Of:-Kb31R2BiKUL48AUppY2:by8sxiz) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L48)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

:poop: 
</blockquote></details>

It doesn't compile properly for the arduino. I've updated it to use some constant definitions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by ryan-summers** [comment]
Review status: 1 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[firmware/sensor/src/depth.ino, line 9 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2EQtE-jqOt-sMQh0P:-Kb35ZA1EHZrdKP_F_o1:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L9)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

:knife: 
</blockquote></details>

Done.

---

*[firmware/sensor/src/depth.ino, line 18 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2Ei4lbaFNL4Xnb14E:-Kb35Y6eVmDB8GiLKfPv:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L18)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

How about depth_sensor instead of ds? Even if it's pretty clear already it's best to be totally clear.
</blockquote></details>

Done.

---

*[firmware/sensor/src/depth.ino, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2F347fDptwRlfkD2w:-Kb35VysohoEWvf7YLkZ:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L33)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

But I don't know why these delays are necessary...
</blockquote></details>

Done.

---

*[firmware/sensor/src/depth.ino, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2F9o2iGA4xR9c_W3I:-Kb35Ti4kiOISBxXeCr6:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L40)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Read does not fail. It has a void return type.
</blockquote></details>

Done.

---

*[firmware/sensor/src/depth.ino, line 44 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2IPDbVLLVid-zBzkY:-Kb35SdsnMBWQHad-bu5:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L44)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

This should be a debug message, we don't want to spam the logs (also logging messages is relatively expensive on arduino)
</blockquote></details>

Done.

---

*[firmware/sensor/src/depth.ino, line 48 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2HkybtVhsKAgHxEM4:-Kb35QSDL59GO1k2YXin:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L48)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

we should load up the parameter "rates/depth" and make the delay configurable.
</blockquote></details>

Done.

---

*[firmware/sensor/src/depth.ino, line 48 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2FvVM97F-eVBJD_Of:-Kb35RPsJPefN1o31A2R:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L48)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

It doesn't compile properly for the arduino. I've updated it to use some constant definitions
</blockquote></details>

Done.

---

*[firmware/sensor/src/Float32Stamped.h, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb32cWDnaDmfLx0ru3z:-Kb35Eff7fBsvRQjdgqQ:b-7qvknh) ([raw file](https://github.com/palouserobosub/robosub/blob/7f92fd148418d94f8b595254a0199fb8694af56b/firmware/sensor/src/Float32Stamped.h#L1)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Was there no better way to get the message type on the arduino?
</blockquote></details>

Not particularly. You have to manually compile the headers with rosrun rosserial_client make_libraries <dir> and then copy the generated Float32Stamped.h into the directory. You can't use ones compiled from rsmake for the Arduino.

---

*[msg/depth_stamped.msg, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb31d4TFImds_mPWCyr:-Kb35AK4xmS3PEWjG-Ef:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/7f92fd148418d94f8b595254a0199fb8694af56b/msg/depth_stamped.msg#L1)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

This message should probably be renamed to Float32Stamped with the float32 value changed to be named data
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by ryan-summers** [comment]
How do I do that again?

---

Review status: 1 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[firmware/sensor/src/depth.ino, line 26 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb2FtSOTiYb6AI40jjy:-Kb35vcbSoLXW2H-uNMn:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/122d5d51b01d341e3fd0cf820855dcffb1438c02/firmware/sensor/src/depth.ino#L26)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

:arrow_down: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-:-Kb35xOA0xrwS-ALluf4:b7usosa)*

**Comment by bkallaher** [comment]
`rsmake roslint`. or just go to the Travis build

---

Review status: 1 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-:-Kb36m0hwmbJycOb_hZv:b-pqex1v)*

**Comment by bkallaher** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r1, 7 of 7 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[firmware/CPPLINT.cfg, line 4 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb3iDp_Oe3h2jbCqirP:-Kb3iDp_Oe3h2jbCqirQ:b-ghpkrx) ([raw file](https://github.com/palouserobosub/robosub/blob/03d0241b056e16b6271e4bc55721d88012535f20/firmware/CPPLINT.cfg#L4)):*
> ```INI
> linelength=80
> filter=-legal,-whitespace/comments,-whitespace/parens,-build/namespaces,-readability/namespace,-runtime/threadsafe_fn,-readability/todo,-runtime/references,-runtime/explicit
> exclude_files=.*
> ```

Do we want to exclude all files in the firmware directory from linting? This doesn't seem like the greatest plan.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[firmware/CPPLINT.cfg, line 4 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb3iDp_Oe3h2jbCqirP:-Kb6VgD0ZZ1Q3zwyxxu9:bom4lz1) ([raw file](https://github.com/palouserobosub/robosub/blob/03d0241b056e16b6271e4bc55721d88012535f20/firmware/CPPLINT.cfg#L4)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Do we want to exclude all files in the firmware directory from linting? This doesn't seem like the greatest plan.
</blockquote></details>

It's not, but there really aren't any sound ways to get the REGEX to properly ignore files. No matter what I do, it ends up parsing the whole folder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[firmware/CPPLINT.cfg, line 4 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-Kb3iDp_Oe3h2jbCqirP:-Kb6YXQlG5J-ksNKJf0W:b-ce8ezd) ([raw file](https://github.com/palouserobosub/robosub/blob/03d0241b056e16b6271e4bc55721d88012535f20/firmware/CPPLINT.cfg#L4)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

It's not, but there really aren't any sound ways to get the REGEX to properly ignore files. No matter what I do, it ends up parsing the whole folder.
</blockquote></details>

I checked through the source code for roslint, and it actually uses the regex against filenames in the current directory. Therefore, the regex can not be used to negate paths. Because of platformio, there's actually a number of hidden folders the cpplint is iterating through that cause thousands of errors. There's no real way that I can see to properly ignore that. However, for the repository (since platformio is not on the repo), it would be possible to simply change this to Float32Stamped.h. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by dcrossman** [comment]
Reviewed 1 of 2 files at r1, 7 of 7 files at r3, 3 of 4 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r3, 3 of 4 files at r4, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/159#-:-Kb6sOnAQGxLDY1WIrIi:bnfp4nl)*

**Pull request merged**
