### PR TITLE
Feature Processing

### PR DESCRIPTION
**Pull request by skallaher**
This updates the parameters of the vision system to use feature processors and changes the feature processing system to allow for different detection algorithms.

I have added unimplemented detectors for all tasks except for the path markers.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/239)

### CODE REVIEW

**Comment by bkallaher** [comment]
Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[param/vision/torpedoVis.yaml, line 9 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZYPGr863mb7LoHpiN:-KhZYPGr863mb7LoHpiO:b-z92gq9) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/param/vision/torpedoVis.yaml#L9)):*
> ```YAML
>     - Convert: {code: "BGR2HSV"}
>     - MedianBlur: {kernel_size: 3}
>     - Or: 
> ```

Space at the end of this line

---

*[src/vision/ColorProcessor.cpp, line 34 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZZbbUX9zG7AmKUrnB:-KhZZbbbJ8v_7PJBISOc:b-fm2o8r) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/src/vision/ColorProcessor.cpp#L34)):*
> ```cpp
>     if(!initialized)
>     {
>         ROS_FATAL_STREAM("Vision Processor process called before init.");
> ```

Thist should say Color not Vision

---

*[src/vision/calib/StereoCalibration.cpp, line 49 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZaC5xrgsNgO8LORPk:-KhZaC5xrgsNgO8LORPl:bhucqhf) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/src/vision/calib/StereoCalibration.cpp#L49)):*
> ```cpp
>     circle(cropMask, Point(rview.size().width / 2, rview.size().height),
>            cropRadius, Scalar(255, 255, 255), -1, 8, 0);
>     //Rect roi(100, 100, rview.size().width - 200, rview.size().width - 200);
> ```

Do you need the roi still?

---

*[src/vision/feature_processors/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZZFvP352WackhCuhX:-KhZZFvP352WackhCuhY:b-ghtxy0) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/src/vision/feature_processors/CMakeLists.txt#L1)):*
> ```CMake
> add_library(feature_processors CentroidDetector.cpp
> ```

Based on the files here the folder and library would be better named by feature_detectors

---

*[src/vision/feature_processors/ObstacleDetector.hpp, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZbRcJwyzmyBnZ53rM:-KhZbRcJwyzmyBnZ53rN:bmleci0) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/src/vision/feature_processors/ObstacleDetector.hpp#L1)):*
> ```cpp
> #ifndef OBSTACLEDETECTOR_HPP
> ```

Do we want to split this file into multiple headers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/239)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[param/vision/torpedoVis.yaml, line 9 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZYPGr863mb7LoHpiN:-KhZeOCNmrb-HqWqdQpo:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/param/vision/torpedoVis.yaml#L9)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Space at the end of this line
</blockquote></details>

Done.

---

*[src/vision/ColorProcessor.cpp, line 34 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZZbbUX9zG7AmKUrnB:-KhZeULdDa-c9BFeZM2E:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/src/vision/ColorProcessor.cpp#L34)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Thist should say Color not Vision
</blockquote></details>

Done.

---

*[src/vision/calib/StereoCalibration.cpp, line 49 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZaC5xrgsNgO8LORPk:-KhZedFp63MGGkW02nnv:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/src/vision/calib/StereoCalibration.cpp#L49)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Do you need the roi still?
</blockquote></details>

Done.

---

*[src/vision/feature_processors/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZZFvP352WackhCuhX:-KhZfLV-Xn_fFV1GMl0Y:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/src/vision/feature_processors/CMakeLists.txt#L1)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Based on the files here the folder and library would be better named by feature_detectors
</blockquote></details>

Done.

---

*[src/vision/feature_processors/ObstacleDetector.hpp, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-KhZbRcJwyzmyBnZ53rM:-KhZev4Oeu-KVxXeMOge:b-s3aeu4) ([raw file](https://github.com/palouserobosub/robosub/blob/645a100a29d7cbcd12387891a438337e9e6a7f34/src/vision/feature_processors/ObstacleDetector.hpp#L1)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Do we want to split this file into multiple headers?
</blockquote></details>

No. This prevents the need for multiple includes in the FeatureProcessor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/239)*

**Comment by bkallaher** [comment]
Reviewed 1 of 43 files at r1, 23 of 23 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/239)*

**Comment by bkallaher** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-:-KhcepIf3ogGN703EldL:bnfp4nl)*

**Comment by therobosub** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Reviewed 8 of 23 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/vision/Vision.cpp, line 137 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-Khn7A2sDz-ih_KipE4O:-Khn7A2sDz-ih_KipE4P:b9aacqx) ([raw file](https://github.com/palouserobosub/robosub/blob/98589939a890d3264e3833993d5a438c0cd19f4e/src/vision/Vision.cpp#L137)):*
> ```cpp
>                               messages);
> ```

Why'd you add this line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/239)*

**Comment by skallaher** [comment]
Review status: 31 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vision/Vision.cpp, line 137 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/239#-Khn7A2sDz-ih_KipE4O:-KhnFtAUfFy1u390Oho8:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/98589939a890d3264e3833993d5a438c0cd19f4e/src/vision/Vision.cpp#L137)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Why'd you add this line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/239)*

**Comment by skallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/239)*

**Pull request merged**
