### PR TITLE
System Check and Control RQt Plugins

### PR DESCRIPTION
**Pull request by bkallaher**
This PR adds in the RQt plugins to the repository. The work left to do with them is minimal (move logo to the background, documentation, etc.) and mostly cosmetic.

To run it may be required to run rsmake to tell RQt that the plugins exist in the repo. Also a possible need is to run `rqt --force-discover` which will force rqt to do a search for new plugins in the path. For a fresh clean RQt instance run `rqt --clear-config`. The plugins are located in a new RoboSub Folder in the RQt plugins menu.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/183)

### CODE REVIEW

**Comment by bkallaher** [comment]
The .ui files can mostly be ignored by reviewers as they are generated by Qt Designer to define the layout of the GUI.

**Comment by irwineffect** [comment]
Reviewed 6 of 10 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/183#-KcspomQ1SrLw1BMPmV8:-KcspomQ1SrLw1BMPmV9:b5vx8l7) (no related file):*
The control gui segfaults on me every once in a while. 

The following warning also spits out a lot, might be related:
```
QCoreApplication::sendPostedEvents: Cannot send posted events for objects in another thread
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/183)*

**Comment by bkallaher** [comment]
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/183#-KcspomQ1SrLw1BMPmV8:-KctIta2t18fynoMpgxm:b-8btg34) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

The control gui segfaults on me every once in a while. 

The following warning also spits out a lot, might be related:
```
QCoreApplication::sendPostedEvents: Cannot send posted events for objects in another thread
```

</blockquote></details>

We can ignore that warning. The segfault is within python itself...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/183)*

**Comment by irwineffect** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/183)*

**Pull request merged**
