### PR TITLE
Mike/nav channel task

### PR DESCRIPTION
**Pull request by Sindorman**
Solves issue PalouseRobosub/robosub#305
- In `Smach_buoy` Start Switch was moved into main, so it no longer requires it to run as part of High State machine;

- Added Start Switch to `smach_gate.py `and `smach_nav_channel.py`;

- Renamed `util_states.py` into `gate_util.py`;

- Modified `gate_util.py` to make it more generic for labels, and changed use of `userdata`;

- Modified `smach_buoy.py` to accept `userdata`(required!). 
  Note - now every state that inherits from `SubscribeState.py` **MUST** accept `userdata` in it's callback.

- Deleted old AI files such as `buoy_task.py`.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/313)

### CODE REVIEW

**Comment by skallaher** [comment]
BTW, I would like you to be thinking about how these tasks can be optimized. (e.g. using concurrent states)

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[param/ai.yaml, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJw20-EWLTN51XIgyZ:-KwJw20-EWLTN51XIgy_:b-dsdfk1) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/param/ai.yaml#L16)):*
> ```YAML
>         errorGoal: 0.1
>         yaw_speed_factor: -25.0
> # variables below contains values for gate/nav_channel tasks
> ```

Contain, not contains.

---

*[param/ai.yaml, line 25 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJwWnSvh7HlUCrST2o:-KwJwWnSvh7HlUCrST2p:b-j0zgn8) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/param/ai.yaml#L25)):*
> ```YAML
>         yaw_speed_factor: 2.0 # how fast to yaw while searching gate
>     center:
>         errorGoal: 0.02 # what is the error Goal, in precentage so 0.1 is 10%
> ```

Please be consistent with your variable naming style. I'm usually fine with either `camelCase` or `underscore_separated`, however, ROS conventions dictate parameters should follow the `underscore_separated` style.

---

*[src/ai/gate_util.py, line 130 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJwNAJGbSMTN-Ka1cC:-KwJwNAJGbSMTN-Ka1cD:btvk9ym) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/src/ai/gate_util.py#L130)):*
> ```Python
> 
> 
> # High level state machine for searching gate posts
> ```

This isn't really a "high-level" state machine, just a state machine.

---

*[src/ai/gate_util.py, line 139 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJx0S1MeSGqem68RGp:-KwJx0S1MeSGqem68RGq:bfho7gq) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/src/ai/gate_util.py#L139)):*
> ```Python
>             smach.StateMachine.add("LOST", lost(label),
>                                   transitions={'1 post': 'SEARCH',
>                                   'none': 'LOST', '2 posts': 'SEARCH'},
> ```

These transitions are within the scope of the `{` brace. Please indent it so that `'none'` is inline with `'1 post'`

---

*[src/ai/smach_buoy.py, line 191 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJxLCy7nOaw_wUqiCn:-KwJxLCy7nOaw_wUqiCo:bku7pvj) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/src/ai/smach_buoy.py#L191)):*
> ```Python
> 
> if __name__ == "__main__":
>     rospy.init_node('ai', log_level=rospy.DEBUG)
> ```

Does this make it so that DEBUG messages are output to the console? This is not the desired default behavior.

---

*[src/ai/smach_gate.py, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJxW6ZmtE-pkGUIW78:-KwJxW6ZmtE-pkGUIW79:bvjr9m2) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/src/ai/smach_gate.py#L33)):*
> ```Python
>                                   transitions={'ready': 'BLIND_FORWARD',
>                                   'not centered': 'CENTER',
>                                   'lost': 'SEARCH_FOR_GATES'})
> ```

These are similar to one of my earlier comments. Please check all of your code for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-:-KwJxxWadcQlW6e0KpEe:b8m0yuc)*

**Comment by Sindorman** [comment]
The only states that could be running in parallel would probably be center, and move while centered. But that could also do some harm in centering, testing is required.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[param/ai.yaml, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJw20-EWLTN51XIgyZ:-KwLWE4o0Pn-_8Kk3bgN:b499q7j) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/param/ai.yaml#L16)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Contain, not contains.
</blockquote></details>

Changed

---

*[param/ai.yaml, line 25 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJwWnSvh7HlUCrST2o:-KwLWSXDDDnVb3LVjrFd:b499q7j) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/param/ai.yaml#L25)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Please be consistent with your variable naming style. I'm usually fine with either `camelCase` or `underscore_separated`, however, ROS conventions dictate parameters should follow the `underscore_separated` style.
</blockquote></details>

Changed

---

*[src/ai/gate_util.py, line 130 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJwNAJGbSMTN-Ka1cC:-KwLWUES-vNbVS3QyQGi:ba3o3s1) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/src/ai/gate_util.py#L130)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This isn't really a "high-level" state machine, just a state machine.
</blockquote></details>

Renamed

---

*[src/ai/gate_util.py, line 139 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJx0S1MeSGqem68RGp:-KwLVh1Ey1Yq5Ho_24aG:b499q7j) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/src/ai/gate_util.py#L139)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

These transitions are within the scope of the `{` brace. Please indent it so that `'none'` is inline with `'1 post'`
</blockquote></details>

Changed

---

*[src/ai/smach_buoy.py, line 191 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJxLCy7nOaw_wUqiCn:-KwLX0CRVbi9MdA-ji7z:bc77zj3) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/src/ai/smach_buoy.py#L191)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Does this make it so that DEBUG messages are output to the console? This is not the desired default behavior.
</blockquote></details>

It does make it. Changed it.

---

*[src/ai/smach_gate.py, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwJxW6ZmtE-pkGUIW78:-KwLX7Lv6n0ezmCNGCQw:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/ebdd88596c2e65102fbb71a031270f78031e5e76/src/ai/smach_gate.py#L33)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

These are similar to one of my earlier comments. Please check all of your code for this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-:-KwLW-iMGoygfGMIiusx:b-vgkqv5)*

**Comment by skallaher** [comment]
Agreed, just something to be thinking about.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ai/start_switch.py, line 43 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwLs1DHTGLxPGIV2SGt:-KwLs1DHTGLxPGIV2SGu:b-cx93vy) ([raw file](https://github.com/palouserobosub/robosub/blob/aad8c94f578ad02430eb6a962b4b1781d9fab5da/src/ai/start_switch.py#L43)):*
> ```Python
> 
> if __name__ == "__main__":
>     rospy.init_node('start_switch_test', log_level=rospy.DEBUG)
> ```

Please fix this one as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-:-KwLqXMhNVR11wQgVK3b:b-wb4wog)*

**Comment by Sindorman** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ai/start_switch.py, line 43 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-KwLs1DHTGLxPGIV2SGt:-KwLu-944MNxRmLZVBZg:b-886gsx) ([raw file](https://github.com/palouserobosub/robosub/blob/aad8c94f578ad02430eb6a962b4b1781d9fab5da/src/ai/start_switch.py#L43)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Please fix this one as well.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/313)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/313#-:-KwLvJpjnbocKqhg8lx8:bnfp4nl)*

**Pull request merged**
