### PR TITLE
Darknet AI conversion

### PR DESCRIPTION
**Pull request by skallaher**
This converts the AI to be able to interpret the output of the YOLO network.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/276)

### CODE REVIEW

**Comment by daymare** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-:-Kq0ADQU3KcIQoXDsz7T:bg7igk9)*

**Comment by daymare** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-:-Kq0Mxeod_m2aEP1j56_:bnfp4nl)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-Kq0NA1JWnjw8bmz0q6l:-Kq0NA1JWnjw8bmz0q6m:b-a8lgv3) (no related file):*
Why haven't you started using the python control module?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276)*

**Comment by skallaher** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-Kq0NA1JWnjw8bmz0q6l:-Kq0RrexAURy3iykpBRG:b6x5wl1) (no related file):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Why haven't you started using the python control module?
</blockquote></details>

Because there's no reason right now to bother.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276)*

**Comment by bkallaher** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-Kq0NA1JWnjw8bmz0q6l:-Kq1m_pJ2ew2T8Uh6-C2:b-8fvsv5) (no related file):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Because there's no reason right now to bother.
</blockquote></details>

:-1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276)*

**Comment by bkallaher** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[param/ai_manager.yaml, line 15 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-Kq1msHRwaJRXUxdIxe-:-Kq1msHRwaJRXUxdIxe0:b-tis7zj) ([raw file](https://github.com/palouserobosub/robosub/blob/a9efd95eda357449e73b33663a159ba833d79d48/param/ai_manager.yaml#L15)):*
> ```YAML
>      node: "buoy_task.py"
>      args: "green_buoy"
>      remap_args: []
> ```

Do you still need `remap_args`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276)*

**Comment by skallaher** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[param/ai_manager.yaml, line 15 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-Kq1msHRwaJRXUxdIxe-:-Kq1oEXLKlnF22p608N2:b-b6tg9v) ([raw file](https://github.com/palouserobosub/robosub/blob/a9efd95eda357449e73b33663a159ba833d79d48/param/ai_manager.yaml#L15)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Do you still need `remap_args`?
</blockquote></details>

This is a future proofing thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276)*

**Comment by bkallaher** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-:-Kq1rQXBtBjPtXGImzwC:bnfp4nl)*

**Comment by skallaher** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ai/ai_manager.py, line 66 at r8](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-KqC6Atsx6bo5X0GVQLh:-KqC6Atsx6bo5X0GVQLi:b3dl1fw) ([raw file](https://github.com/palouserobosub/robosub/blob/5584345ee7c1e8c4185d9a88754c9ce62c88d2ce/src/ai/ai_manager.py#L66)):*
> ```Python
>         msg.roll_state = control.STATE_ERROR
> 
>         publisher.publish(msg)
> ```

BTW, once the control system gets a service call to set all relative zeros, #282, this will change to use that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r3, 1 of 5 files at r4, 1 of 2 files at r6, 2 of 5 files at r9, 3 of 4 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276)*

**Comment by dcrossman** [comment]
Reviewed 1 of 2 files at r3, 1 of 5 files at r4, 1 of 2 files at r6, 2 of 5 files at r9, 3 of 4 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276)*

**Comment by dcrossman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-:-KqCLNmBqD-nN6T3XNEO:bnfp4nl)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276)*

**Comment by bkallaher** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/276#-:-KqCNCvKspQ_ogPanSku:bnfp4nl)*

**Pull request merged**
