### PR TITLE
Updated rqt_syscheck to show the latest depth and RPY values

### PR DESCRIPTION
**Pull request by bkallaher**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/281)

### CODE REVIEW

**Comment by irwineffect** [comment]
reopening on master base

**Comment by Sindorman** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/281)*

**Comment by brennanpeter** [comment]
This pull request has been sitting here for a few months, any reason why this wasn't merged in earlier? and do we still want the changes? @skallaher @Sindorman @irwineffect @bkallaher

**Comment by Sindorman** [comment]
@brennanpeter I have checked the changes for rqt in that branch. It adds current depth, yaw, pitch, roll values. I have rebased it and pushed. Here is an example of what it adds 
screenshot from 2018-03-30 13-45-41

**Comment by bkallaher** [comment]
Instead of changing the box width change the maximum resolution of the text. This can be done by changing line 237 of `syscheck.py` to have the parameter to `setText` be `'{0:.2f}'.format(m.data)`

**Comment by bkallaher** [comment]
Then assume that the value will never be > 99m and adjust the width to fit the max value of 99.99

**Comment by Sindorman** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/281#-:-LAsHgqv4PvGh6k05525:bnfp4nl)*

**Comment by Sindorman** [comment]
@brennanpeter This is ready for merge

**Comment by brennanpeter** [comment]
Ok will do

Sent from my iPhone

On Apr 24, 2018, at 12:02 PM, Mykhailo Bykhovtsev <notifications@github.com<mailto:notifications@github.com>> wrote:


@brennanpeter<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_brennanpeter&d=DwMCaQ&c=C3yme8gMkxg_ihJNXS06ZyWk4EJm8LdrrvxQb-Je7sw&r=7kaAeZptj72hUN9FZR4Rb4UTOfEhNWKxs08emxz7fwU&m=54oVB_5g6wzXjOsGciaWtf4D-d-fhky-4yip4t31dKs&s=vB2zY_fTudDQA4yN4GG7Lg9TNEZ2yY_-zkLDqq6sTpo&e=> This is ready for merge

**Pull request merged**
