### PR TITLE
Python Control System Wrapper

### PR DESCRIPTION
**Pull request by bkallaher**
This allows a python script to easily use the control system without working directly with control system messages. Let me know if there is any useful functionality that I should add.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/265)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/ai/control_wrapper.py, line 23 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopReZ_grCsE6vVRY4a:-KopReZ_grCsE6vVRY4b:b-is75xt) ([raw file](https://github.com/palouserobosub/robosub/blob/cc6aa8c736e6e165e2bbfead2dd6ae6ca86e1216/src/ai/control_wrapper.py#L23)):*
> ```Python
>             return cls.__instance
> 
> class control_wrapper():
> ```

This class name doesn't follow PEP 8 convention.

---

*[src/ai/control_wrapper.py, line 49 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopTKcf4Zwbj7u1_CAZ:-KopTKcf4Zwbj7u1_CA_:b-69cb1s) ([raw file](https://github.com/palouserobosub/robosub/blob/cc6aa8c736e6e165e2bbfead2dd6ae6ca86e1216/src/ai/control_wrapper.py#L49)):*
> ```Python
> 
>     # Absolute Yaw method
>     def yawAbsolute(self, value):
> ```

Naming this way may be a little shorter, but `yawLeftAbsolute` reminds the user that left is positive. Especially if they don't use the `setYawLeft` method at all.

---

*[src/ai/control_wrapper.py, line 62 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopSiDeRQ5aQ-0GRNU6:-KopSiDeRQ5aQ-0GRNU7:bgskgmo) ([raw file](https://github.com/palouserobosub/robosub/blob/cc6aa8c736e6e165e2bbfead2dd6ae6ca86e1216/src/ai/control_wrapper.py#L62)):*
> ```Python
>     # Set the yaw state to none and clear out the value
>     def yawNone(self):
>         self.setYawLeft(control.STATE_NONE, 0)
> ```

You may not want to clear out the value here. Even though a NONE message doesn't change the goal, a program may still want to use the previous message's goal as a reference of some kind. Same with all others.

---

*[src/ai/control_wrapper.py, line 262 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopW3qrHX6drfg6fACy:-KopW3qrHX6drfg6fACz:bwmoqie) ([raw file](https://github.com/palouserobosub/robosub/blob/cc6aa8c736e6e165e2bbfead2dd6ae6ca86e1216/src/ai/control_wrapper.py#L262)):*
> ```Python
>     c.strafeError(145)
>     print d.getCurrentState()
>     d.publish()
> ```

Would this be better suited for a unit test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/ai/control_wrapper.py, line 23 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopReZ_grCsE6vVRY4a:-Koskna70YUtK_kRSk0p:bs5rgo1) ([raw file](https://github.com/palouserobosub/robosub/blob/cc6aa8c736e6e165e2bbfead2dd6ae6ca86e1216/src/ai/control_wrapper.py#L23)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This class name doesn't follow PEP 8 convention.
</blockquote></details>

OK. Apparently PEP 8 isn't strictly enforced by the linter. Though I prefer class names to be CapitalCamelCase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-Kot-ugqGMh5omahba5h:-Kot-ugqGMh5omahba5i:b-5rav1n) (no related file):*
I think it would be useful to have a function to set the roll and pitch to absolute zero.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-Kot09iLkRD9VYQ5Sav_:-Kot09iLkRD9VYQ5Sava:brtj2ow) (no related file):*
As we talked in person, it might be a good idea to setup a shutdown hook to send a message to zero out the control system. However, if we do decide to add this feature it will be in a separate PR.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-Kot0XIIzHICHsiuOzIm:-Kot0XIIzHICHsiuOzIn:bd83plh) (no related file):*
I'm somewhat worried about people getting confused by the singleton behavior, specifically that instantiating a new instance of the class will not zero out the internal message, which is the expected behavior for a normal class. I understand the convenience, but there's also something to say about classes behaving the way people are accustomed to. Is it possible to default to normal class behavior and have an optional flag in the constructor to enable singleton behavior?

---

*[src/ai/control_wrapper.py, line 23 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopReZ_grCsE6vVRY4a:-Koskqd2C9_RawPsQVSo:bx6dme8) ([raw file](https://github.com/palouserobosub/robosub/blob/cc6aa8c736e6e165e2bbfead2dd6ae6ca86e1216/src/ai/control_wrapper.py#L23)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This class name doesn't follow PEP 8 convention.
</blockquote></details>

You can change if you want, but we aren't following PEP8

---

*[src/ai/control_wrapper.py, line 49 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopTKcf4Zwbj7u1_CAZ:-KoskmPjSEvKwN5gUHs_:b-k2iab4) ([raw file](https://github.com/palouserobosub/robosub/blob/cc6aa8c736e6e165e2bbfead2dd6ae6ca86e1216/src/ai/control_wrapper.py#L49)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Naming this way may be a little shorter, but `yawLeftAbsolute` reminds the user that left is positive. Especially if they don't use the `setYawLeft` method at all.
</blockquote></details>

Agreed, good to be explicit.

---

*[src/ai/control_wrapper.py, line 62 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopSiDeRQ5aQ-0GRNU6:-Kosl0YoMSOsiZ3HsULA:bd1fexx) ([raw file](https://github.com/palouserobosub/robosub/blob/cc6aa8c736e6e165e2bbfead2dd6ae6ca86e1216/src/ai/control_wrapper.py#L62)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

You may not want to clear out the value here. Even though a NONE message doesn't change the goal, a program may still want to use the previous message's goal as a reference of some kind. Same with all others.
</blockquote></details>

Having multiple levels of stateful memory is confusing, ideally we want this class to have minimal memory. However, every other function overrides the value field, so it doesn't really matter anyways.

---

*[src/ai/control_wrapper.py, line 262 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopW3qrHX6drfg6fACy:-KosmC1TEkn-zDr4oJp9:b-y6it19) ([raw file](https://github.com/palouserobosub/robosub/blob/cc6aa8c736e6e165e2bbfead2dd6ae6ca86e1216/src/ai/control_wrapper.py#L262)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Would this be better suited for a unit test?
</blockquote></details>

Yeah, @bkallaher, can you remove this `__main__` code before we merge in? If you're feeling bored you can make a unit test for it, but not needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-Kot-ugqGMh5omahba5h:-KotetYCHo07nN2eihwX:b-896fix) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

I think it would be useful to have a function to set the roll and pitch to absolute zero.
</blockquote></details>

Done.

---

*[src/ai/control_wrapper.py, line 49 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopTKcf4Zwbj7u1_CAZ:-KotfOxYxJ_IwRQhcS_Z:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/df81a317240fc5de595b6913f7552a50a4a5ff90/src/ai/control_wrapper.py#L49)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Agreed, good to be explicit.
</blockquote></details>

Done.

---

*[src/ai/control_wrapper.py, line 262 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KopW3qrHX6drfg6fACy:-KotfUhy30dtD0PgKrc3:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/df81a317240fc5de595b6913f7552a50a4a5ff90/src/ai/control_wrapper.py#L262)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Yeah, @bkallaher, can you remove this `__main__` code before we merge in? If you're feeling bored you can make a unit test for it, but not needed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265)*

**Comment by bkallaher** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-Kot0XIIzHICHsiuOzIm:-Kou2urrXmLzCFrIWPyg:bo16916) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

I'm somewhat worried about people getting confused by the singleton behavior, specifically that instantiating a new instance of the class will not zero out the internal message, which is the expected behavior for a normal class. I understand the convenience, but there's also something to say about classes behaving the way people are accustomed to. Is it possible to default to normal class behavior and have an optional flag in the constructor to enable singleton behavior?
</blockquote></details>

I could do the opposite (make the Singleton the default) but I really don't see the issue. Singleton one of the most basic design patterns and would prevent multiple publishers from being instantiated by the same node.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-Kot0XIIzHICHsiuOzIm:-KoxSt5N7y12-snLaxiD:b-thbcjg) (no related file):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

I could do the opposite (make the Singleton the default) but I really don't see the issue. Singleton one of the most basic design patterns and would prevent multiple publishers from being instantiated by the same node.
</blockquote></details>

Just saying, I've never heard of it before now. I find it likely other people may not have encountered it before either. Multiple publishers actually isn't a problem I don't think. Could we just have the publisher be copied between classes and have the control message be reset to defaults? Would that be as simple as resetting it in the constructor?

---

*[src/ai/control_wrapper.py, line 43 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-KoxSYN0KMixOWTSVlaz:-KoxSYN0KMixOWTSVlb-:b9hqcho) ([raw file](https://github.com/palouserobosub/robosub/blob/96e19478140e5786fc441ce38cf97db9370c1338/src/ai/control_wrapper.py#L43)):*
> ```Python
>     # Set the yaw and pitch to absolute 0
>     def levelOut(self):
>         self.yawAbsolute(0)
> ```

Should be roll, not yaw

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-Kot0XIIzHICHsiuOzIm:-Koxb6TfE_DTzfRrkoYI:biebtwx) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Just saying, I've never heard of it before now. I find it likely other people may not have encountered it before either. Multiple publishers actually isn't a problem I don't think. Could we just have the publisher be copied between classes and have the control message be reset to defaults? Would that be as simple as resetting it in the constructor?
</blockquote></details>

There is no reason for this to be a Singleton. Assuming the Control goes out of scope, the publisher will be destructed and won't cause any collisions with other publishers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-:-KoxkK4fdMZoAub-MPg0:bnfp4nl)*

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/265#-:-KoxxJ6_aQ6FAxY1Jytq:bnfp4nl)*

**Pull request merged**
