### PR TITLE
Corrected channels for new hardware

### PR DESCRIPTION
**Pull request by ryan-summers**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/251)

### CODE REVIEW

**Comment by skallaher** [comment]
Could you give a short explanation for the changes made that require these channel updates? (Mostly for posterity)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/251#-:-Kjq7BrFNG6H0E5r6mg6:b-1fs5e0)*

**Comment by ryan-summers** [comment]
What do you mean? I cut the wires and crimped them back together. Except when I crimped them back, they were in a slightly different order. I don't see how that's useful information for posterity :P

**Comment by skallaher** [comment]
More of a note as to why this needed to happen. That's all I was looking for. Once this is tested, it should be good to go.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/251#-:-Kju_rFRvmqjbKCaDXOX:b-cv74te)*

**Comment by irwineffect** [comment]
Will test this today and confirm the fix is good.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/251#-:-KjxpzFY9oxsTWu114_C:bf9psq)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/251#-Kjxq7sAUoiwkxjlr5g7:-Kjxq7sAUoiwkxjlr5g8:bif4jlo) (no related file):*
Need to test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/251)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/251#-Kjxq7sAUoiwkxjlr5g7:-KjzeSsUw8bPoXVec8Hu:b-u4jdap) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Need to test.
</blockquote></details>

It works!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/251)*

**Pull request merged**
