### PR TITLE
Trice/localization point cloud histogram

### PR DESCRIPTION
**Pull request by trice9595**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/347)

### CODE REVIEW

**Comment by Sindorman** [comment]
Just some format changes that needs to be done. Check linter on travis, it will tell you what lines have what format issues. Also if you have ROS installed you can locally run linter as `rsmake roslint`

**Comment by Sindorman** [comment]
There are some of my commits that have been merged to master, make an interactive rebase and remove them.

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/ai/control_wrapper.py, line 88 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lYth8mtuDoZBg6DrY:-L2lYth8mtuDoZBg6DrZ:bio5lmk) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/ai/control_wrapper.py#L88)):*
> ```Python
>     # Set the pitch state to none and clear out the value
>     def pitchDownNone(self):
>         self.setPitchDown(control.STATE_NONE, 0)
> ```

Why are these commits included in this PR?

---

*[src/localization/particle_cloud_histogram.py, line 16 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lYwwkmpO1CdG1VnSz:-L2lYwwkmpO1CdG1VnT-:bc5lxgi) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L16)):*
> ```Python
>     
>     def callback(self, msg):
>         
> ```

You have trailing whitespace. Please check the linter.

---

*[src/localization/particle_cloud_histogram.py, line 17 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2l_3vKgsj_06FA6zs5:-L2l_3vKgsj_06FA6zs6:b7x0agw) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L17)):*
> ```Python
>     def callback(self, msg):
>         
>         rospy.loginfo("Plotting Update")
> ```

This kind of output is better suited as a logdebug message.

---

*[src/localization/particle_cloud_histogram.py, line 36 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lZ6j6RfeqIhltllN_:-L2lZ6j6RfeqIhltllNa:bx0mon9) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L36)):*
> ```Python
> 
>         # Subscribe to the topic
>         self.sub = rospy.Subscriber("/localization/particles", PointCloud, self.callback)
> ```

Using absolute topic namespaces is not typically done. Just remove the leading `/`. This allows for flexibility if someone wanted to push everything down into another namespace.

---

*[src/localization/particle_cloud_histogram.py, line 45 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lZKO_umyA557eBOPq:-L2lZKO_umyA557eBOPr:bn50nur) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L45)):*
> ```Python
> 
>     def __del__(self):
>         self.sub.unregister()
> ```

This should be done automatically on the deconstruction of the object.

---

*[src/localization/particle_cloud_histogram.py, line 49 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lZVmXekeH_FD11kS5:-L2lZVmXekeH_FD11kS6:bf5ovcv) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L49)):*
> ```Python
> 
> if __name__ == "__main__":
>     global h
> ```

Everything in "__main__" is inherently global. There is also no reason to declare something as global if you don't use it elsewhere.

---

*[src/localization/particle_cloud_histogram.py, line 55 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lZPDGyQXvbZa9M46J:-L2lZPDGyQXvbZa9M46K:bbkl3bn) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L55)):*
> ```Python
>     h = Histogram()
> 
>     rospy.spin()
> ```

You are missing an end of file or newline at end of file here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/347)*

**Comment by trice9595** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/localization/particle_cloud_histogram.py, line 16 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lYwwkmpO1CdG1VnSz:-L48QKA5LP7kK-xs-15u:bb7f2mf) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L16)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

You have trailing whitespace. Please check the linter.
</blockquote></details>

done

---

*[src/localization/particle_cloud_histogram.py, line 17 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2l_3vKgsj_06FA6zs5:-L48Pz0tJ0NYJ3tY1L9e:b-a99h39) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L17)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This kind of output is better suited as a logdebug message.
</blockquote></details>

yup I agree, I made the change

---

*[src/localization/particle_cloud_histogram.py, line 36 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lZ6j6RfeqIhltllN_:-L48QPxl1_hvDBJ8dChU:bb7f2mf) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L36)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Using absolute topic namespaces is not typically done. Just remove the leading `/`. This allows for flexibility if someone wanted to push everything down into another namespace.
</blockquote></details>

done

---

*[src/localization/particle_cloud_histogram.py, line 45 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lZKO_umyA557eBOPq:-L48QSua5ex3pCXJQ5Sp:b-5dfryo) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L45)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This should be done automatically on the deconstruction of the object.
</blockquote></details>

removed it

---

*[src/localization/particle_cloud_histogram.py, line 49 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lZVmXekeH_FD11kS5:-L48Q_ZYCexW6t5aaD5W:b-4d4izh) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L49)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Everything in "__main__" is inherently global. There is also no reason to declare something as global if you don't use it elsewhere.
</blockquote></details>

relic from a little bit of copy and paste. removed it.

---

*[src/localization/particle_cloud_histogram.py, line 55 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lZPDGyQXvbZa9M46J:-L48QfS-mJwV0ChtiHQb:bb7f2mf) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/localization/particle_cloud_histogram.py#L55)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

You are missing an end of file or newline at end of file here.
</blockquote></details>

done

---

*[src/ai/control_wrapper.py, line 88 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lYth8mtuDoZBg6DrY:-L48QkIsSqkWZTgBSEX3:b-pzhcpm) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/ai/control_wrapper.py#L88)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why are these commits included in this PR?
</blockquote></details>

I have no idea how this got here. I don't think I ever touched this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/347)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r5.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/localization/particle_cloud_histogram.py, line 35 at r5](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L48jBuX6dXxQRpBQQRB:-L48jBuX6dXxQRpBQQRC:b-ol1edd) ([raw file](https://github.com/palouserobosub/robosub/blob/8a6f776086ca59b9ac325620d67a941e7e9359cb/src/localization/particle_cloud_histogram.py#L35)):*
> ```Python
>         # Subscribe to the topic
>         self.sub = rospy.Subscriber("localization/particles", PointCloud,
> 					 self.callback)
> ```

This line contains tabs. You should both run the linter on your local machine and look at the output on Travis to make sure these things are rectified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/347)*

**Comment by trice9595** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/localization/particle_cloud_histogram.py, line 35 at r5](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L48jBuX6dXxQRpBQQRB:-L4I90HV4BPFK-ltG1Vd:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/8a6f776086ca59b9ac325620d67a941e7e9359cb/src/localization/particle_cloud_histogram.py#L35)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This line contains tabs. You should both run the linter on your local machine and look at the output on Travis to make sure these things are rectified.
</blockquote></details>

Done.

---

*[src/ai/control_wrapper.py, line 88 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/347#-L2lYth8mtuDoZBg6DrY:-L4I931AR4G_dnT2tfUP:b-heje32) ([raw file](https://github.com/palouserobosub/robosub/blob/a4952defce57bba878ea13b301505b84268efd09/src/ai/control_wrapper.py#L88)):*
<details><summary><i>Previously, trice9595 wrote…</i></summary><blockquote>

I have no idea how this got here. I don't think I ever touched this file.
</blockquote></details>

I did an interactive rebase, removing these commits from my branch and rebasing on top of the master branch which already included these commits.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/347)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/347)*

**Pull request merged**
