### PR TITLE
Chrisn/blind gate

### PR DESCRIPTION
**Pull request by chrisnathman**
adds a program to do the gate task without vision, values for time and speed need testing, need to use command rosparam load ai.yaml in order for some variables to be usable

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/415)

### CODE REVIEW

**Review by Sindorman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/415)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisnathman)

___
*[src/ai/smach_blind_gate.py, line 45 at r3](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNVjxmv5ibHYW6vG-tR:-LNVjxmv5ibHYW6vG-tS:bjwpwgl) ([raw file](https://github.com/palouserobosub/robosub/blob/89defaa732ed1aa5f0ca43602298593a6e087efb/src/ai/smach_blind_gate.py#L45)):*
> ```Python
>         euler = euler_from_quaternion(quaternion)
>         yaw = euler[2]*180/math.pi
>         if abs(yaw-userdata.heading_input) < 2:
> ```

We probably want 2 to be a parameter, something named like `yaw_error` which is saved in parameter files

**Review by chrisnathman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/415)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Sindorman)

___
*[src/ai/smach_blind_gate.py, line 45 at r3](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNVjxmv5ibHYW6vG-tR:-LNW7Lqh3wjTfNPpr3t_:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/89defaa732ed1aa5f0ca43602298593a6e087efb/src/ai/smach_blind_gate.py#L45)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

We probably want 2 to be a parameter, something named like `yaw_error` which is saved in parameter files
</blockquote></details>

Done.

**Review by Sindorman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/415)* status: all files reviewed, 5 unresolved discussions (waiting on @Sindorman and @chrisnathman)

___
*[src/ai/smach_blind_gate.py, line 31 at r4](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNWADgCE-DdwYdYN5GA:-LNWADgCE-DdwYdYN5GB:bjpf685) ([raw file](https://github.com/palouserobosub/robosub/blob/a9bed3d019914e61e72f1918559360db55fd8205/src/ai/smach_blind_gate.py#L31)):*
> ```Python
> 
> class rotate_to_heading(SubscribeState):
>     def __init__(self, yaw_error):
> ```

No need to pass it
___
*[src/ai/smach_blind_gate.py, line 35 at r4](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNWA9knBX1DIxov56cA:-LNWA9knBX1DIxov56cB:b2hvgi3) ([raw file](https://github.com/palouserobosub/robosub/blob/a9bed3d019914e61e72f1918559360db55fd8205/src/ai/smach_blind_gate.py#L35)):*
> ```Python
>                                 self.callback, outcomes=['success'],
>                                 input_keys=['heading_input'])
>         self.yaw_error = yaw_error
> ```

`self.yaw_error = rospy.get_param("ai/blind_gate_task/yaw_error")`
___
*[src/ai/smach_blind_gate.py, line 62 at r4](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNWA2i2DMZCDOsdaDKL:-LNWA2i2DMZCDOsdaDKM:bxp6hxs) ([raw file](https://github.com/palouserobosub/robosub/blob/a9bed3d019914e61e72f1918559360db55fd8205/src/ai/smach_blind_gate.py#L62)):*
> ```Python
>         self.time = rospy.get_param("ai/blind_gate_task/forward_time")
>         self.speed = rospy.get_param("ai/blind_gate_task/forward_speed")
>         self.yaw_error = rospy.get_param("ai/blind_gate_task/yaw_error")
> ```

This line needs to be inside of `rotate_to_heading() init.
___
*[src/ai/smach_blind_gate.py, line 73 at r4](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNWAG0E1tA2US4ApJIf:-LNWAG0E1tA2US4ApJIg:b-sdy4qf) ([raw file](https://github.com/palouserobosub/robosub/blob/a9bed3d019914e61e72f1918559360db55fd8205/src/ai/smach_blind_gate.py#L73)):*
> ```Python
> 
>             smach.StateMachine.add('ROTATE_TO_HEADING',
>                                    rotate_to_heading(self.yaw_error),
> ```

No need to pass it.

**Review by chrisnathman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/415)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @Sindorman)

___
*[src/ai/smach_blind_gate.py, line 31 at r4](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNWADgCE-DdwYdYN5GA:-LNWNWzF-jxZAL4lAuxR:bdz7g3q) ([raw file](https://github.com/palouserobosub/robosub/blob/a9bed3d019914e61e72f1918559360db55fd8205/src/ai/smach_blind_gate.py#L31)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

No need to pass it
</blockquote></details>

Completed all the changes so it is not passed in.
___
*[src/ai/smach_blind_gate.py, line 35 at r4](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNWA9knBX1DIxov56cA:-LNWNXmxENN-C3hTVLNr:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/a9bed3d019914e61e72f1918559360db55fd8205/src/ai/smach_blind_gate.py#L35)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

`self.yaw_error = rospy.get_param("ai/blind_gate_task/yaw_error")`
</blockquote></details>

Done.
___
*[src/ai/smach_blind_gate.py, line 62 at r4](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNWA2i2DMZCDOsdaDKL:-LNWNYYU8FDC270twRT8:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/a9bed3d019914e61e72f1918559360db55fd8205/src/ai/smach_blind_gate.py#L62)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

This line needs to be inside of `rotate_to_heading() init.
</blockquote></details>

Done.
___
*[src/ai/smach_blind_gate.py, line 73 at r4](https://reviewable.io/reviews/palouserobosub/robosub/415#-LNWAG0E1tA2US4ApJIf:-LNWNYttEcjgZBlccWXS:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/a9bed3d019914e61e72f1918559360db55fd8205/src/ai/smach_blind_gate.py#L73)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

No need to pass it.
</blockquote></details>

Done.

**Review by Sindorman — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/415#-:-LNWRpui2wveZ3iqiHh9:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
