### PR TITLE
Fixed case issue with detecting the PS3 controller

### PR DESCRIPTION
**Pull request by bkallaher**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/253)

### CODE REVIEW

**Comment by skallaher** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/gamepad_driver.cpp, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/253#-Kjucezfd1FP0aF77bDc:-Kjucezg7vZiCzk8eDOP:b-7h69h9) ([raw file](https://github.com/palouserobosub/robosub/blob/dc57f23a59386cf1b50e7ccb396ad33a453a75b9/src/controllers/gamepad_driver.cpp#L40)):*
> ```cpp
>     }
>     ROS_ERROR("Name: %s", name);
>     ROS_ERROR("Number of Buttons: %d", num_btns);
> ```

Why are these ERROR level now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/253)*

**Comment by bkallaher** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/gamepad_driver.cpp, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/253#-Kjucezfd1FP0aF77bDc:-KjufMq8TUcTdR1QUHrP:b9bhcg2) ([raw file](https://github.com/palouserobosub/robosub/blob/dc57f23a59386cf1b50e7ccb396ad33a453a75b9/src/controllers/gamepad_driver.cpp#L40)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why are these ERROR level now?
</blockquote></details>

Since this should only ever be run from the launch file this allows the output to be printed to the screen every time since rosinfos are cut out with roslaunch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/253)*

**Comment by skallaher** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/gamepad_driver.cpp, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/253#-Kjucezfd1FP0aF77bDc:-Kjug81bHFbJ2VbjjHUJ:bc14pm) ([raw file](https://github.com/palouserobosub/robosub/blob/dc57f23a59386cf1b50e7ccb396ad33a453a75b9/src/controllers/gamepad_driver.cpp#L40)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

Since this should only ever be run from the launch file this allows the output to be printed to the screen every time since rosinfos are cut out with roslaunch
</blockquote></details>

Rather than doing this, the launch file should be modified to add the `output="screen"` argument to the node tag. That will print INFO level output in the roslaunch terminal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/253)*

**Comment by bkallaher** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/gamepad_driver.cpp, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/253#-Kjucezfd1FP0aF77bDc:-KjxoGpI6YEjVVlaFgEo:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/dc57f23a59386cf1b50e7ccb396ad33a453a75b9/src/controllers/gamepad_driver.cpp#L40)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Rather than doing this, the launch file should be modified to add the `output="screen"` argument to the node tag. That will print INFO level output in the roslaunch terminal.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/253)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/253#-:-Kjxoh0p1OWRfwyqqJ-n:bnfp4nl)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/253#-:-KjxpMfqZg-AEabg9YIF:bnfp4nl)*

**Pull request merged**
