### PR TITLE
SMACH-based buoy AI

### PR DESCRIPTION
**Pull request by irwineffect**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/293)

### CODE REVIEW

**Comment by daymare** [comment]
Warning: Did not look through super thorough.
Did not see anything obviously painful.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ai/smach_buoy.py, line 138 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdWPs-Q--xfLpPdCyd:-KtdWPs-Q--xfLpPdCye:b-hfiph1) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L138)):*
> ```Python
> 
>         if vision_result is None:
>             # if we can't see the object in question, yaw by 15 degrees
> ```

Comment doesn't match code. Just bugs me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-:-KtdXQ2NknIB5vGiaMCt:b68iava)*

**Comment by daymare** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-:-KtdXjUfIgxB68QXuPCX:bnfp4nl)*

**Comment by skallaher** [comment]
Check the linter and test output.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[launch/record.launch, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-Ktdb_lYjGLwyl_j4Hvu:-Ktdb_lYjGLwyl_j4Hvv:b-pjbvl4) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/launch/record.launch#L33)):*
> ```XML
>     <node pkg="rosbag" type="record" name="rosout_bag" output="screen"
>         args="-o $(arg outdir)/rosout /rosout_agg" />
> ```

Should we also record the smach topics?

---

*[src/ai/smach_buoy.py, line 19 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdbyARjvhkra7xP30S:-KtdbyARjvhkra7xP30T:b-r8vj0s) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L19)):*
> ```Python
>         if msg.data == True:
>             self.start_counter += 1
>             if self.start_counter >= 3:
> ```

Can we make this a parameter of the state? (i.e. add it as an argument to the constructor)

---

*[src/ai/smach_buoy.py, line 21 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdbsI_G5LSkr7CG6ns:-KtdbsI_G5LSkr7CG6nt:bd7c3cd) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L21)):*
> ```Python
>             if self.start_counter >= 3:
>                 self.done = True
>         else: # i == False
> ```

This comment is out of date

---

*[src/ai/smach_buoy.py, line 24 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdcDjmHam67L5j03yo:-KtdcDjmHam67L5j03yp:b-ki9fd3) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L24)):*
> ```Python
>             self.start_counter = 0
> 
>     def execute(self, userdata):
> ```

Didn't you mention something about initializing done to False at the beginning of `execute`? I know that this state should only ever be executed once, however, just for consistency's sake.

---

*[src/ai/smach_buoy.py, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdcXypJb5h1aC1ey9m:-KtdcXypJb5h1aC1ey9n:b-p15cyc) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L29)):*
> ```Python
>         while not rospy.is_shutdown():
>             if self.done == True:
>                 rospy.loginfo('got here')
> ```

This seems like a debugging log, please remove or make it a useful logdebug.

---

*[src/ai/smach_buoy.py, line 58 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdcwKKgO63TuxWJu1t:-KtdcwKKgO63TuxWJu1u:b-nckakk) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L58)):*
> ```Python
>         detections = filterByLabel(msg.detections, self.vision_label)
> 
>         vision_result = getMostProbable(detections, thresh=0.5)
> ```

In future, this threshold should probably be more easily configurable.

---

*[src/ai/smach_buoy.py, line 89 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtddLnv6eB4zULEVG9g:-KtddLnv6eB4zULEVG9h:b6xavx) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L89)):*
> ```Python
>                  (abs(vision_result.y) < self.errorGoal):
> ```

Extra newline here.

---

*[src/ai/smach_buoy.py, line 155 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdeYkgzoo8PY4ONZHc:-KtdeYkgzoo8PY4ONZHd:b-gv5bit) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L155)):*
> ```Python
>                 self.done = True
> 
>         rospy.loginfo("find buoy publishing")
> ```

Looks like another debug output.

---

*[src/ai/smach_buoy.py, line 175 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdenXQxmZhUfm7OxcO:-KtdenXQxmZhUfm7OxcP:bdtmjwv) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L175)):*
> ```Python
>         c.levelOut()
>         c.forwardError(0.4)
>         exit_time = rospy.Time.now() + rospy.Duration(4)
> ```

This time should be made configurable at some point

---

*[src/ai/smach_buoy.py, line 202 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-Ktdf1Dfj0Kc7rl-oUWw:-Ktdf1Dfj0Kc7rl-oUWx:b-u0jt4b) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L202)):*
> ```Python
>         c.levelOut()
>         c.forwardError(-0.4)
>         exit_time = rospy.Time.now() + rospy.Duration(8)
> ```

Another candidate for configuring. I mention these because I know that a given amount of time in the simulator will probably not be enough in the real world and we'll be modifying these a lot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-:-KtdfKKrMg5LWwKjWf0-:b-5afs8k)*

**Comment by skallaher** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[src/ai/gate_task.py, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-Kth7hh-kzlrwBVXzAY6:-Kth7hh-kzlrwBVXzAY7:b-fh1ecs) ([raw file](https://github.com/palouserobosub/robosub/blob/917d20ddd6c6c019113c15487658c1840791d4ca/src/ai/gate_task.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

Could you fix the other two linter errors in this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/293)*

**Comment by skallaher** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/293)*

**Comment by irwineffect** [comment]
Review status: 3 of 4 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[launch/record.launch, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-Ktdb_lYjGLwyl_j4Hvu:-KthC3magyv9FC_U8vUd:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/launch/record.launch#L33)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Should we also record the smach topics?
</blockquote></details>

Done.

---

*[src/ai/gate_task.py, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-Kth7hh-kzlrwBVXzAY6:-KthCEmcJ6BvT3z66-b9:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/917d20ddd6c6c019113c15487658c1840791d4ca/src/ai/gate_task.py#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Could you fix the other two linter errors in this file?
</blockquote></details>

Done.

---

*[src/ai/smach_buoy.py, line 19 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdbyARjvhkra7xP30S:-KthCbhB5j3iLoRxTIID:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L19)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Can we make this a parameter of the state? (i.e. add it as an argument to the constructor)
</blockquote></details>

Done.

---

*[src/ai/smach_buoy.py, line 21 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdbsI_G5LSkr7CG6ns:-KthCk-SclZFm5D7XRau:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L21)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This comment is out of date
</blockquote></details>

Done.

---

*[src/ai/smach_buoy.py, line 24 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdcDjmHam67L5j03yo:-KthCsIXkCbs3Bu5CgZi:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L24)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Didn't you mention something about initializing done to False at the beginning of `execute`? I know that this state should only ever be executed once, however, just for consistency's sake.
</blockquote></details>

Done.

---

*[src/ai/smach_buoy.py, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdcXypJb5h1aC1ey9m:-KthCvJvy-53Fr9uHegD:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L29)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This seems like a debugging log, please remove or make it a useful logdebug.
</blockquote></details>

Done.

---

*[src/ai/smach_buoy.py, line 89 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtddLnv6eB4zULEVG9g:-KthD7jxKM2Zu-tQSpvF:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L89)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Extra newline here.
</blockquote></details>

Done.

---

*[src/ai/smach_buoy.py, line 138 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdWPs-Q--xfLpPdCyd:-KthDCjKsXmyXzOnipQb:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L138)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

Comment doesn't match code. Just bugs me.
</blockquote></details>

Done.

---

*[src/ai/smach_buoy.py, line 155 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdeYkgzoo8PY4ONZHc:-KthDESaOHW5IbqEy4r7:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L155)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Looks like another debug output.
</blockquote></details>

Done.

---

*[src/ai/smach_buoy.py, line 175 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-KtdenXQxmZhUfm7OxcO:-KthD_cqTyWf4X7TEM8F:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L175)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This time should be made configurable at some point
</blockquote></details>

Done.

---

*[src/ai/smach_buoy.py, line 202 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-Ktdf1Dfj0Kc7rl-oUWw:-KthDaHPQXoTJF93fP-W:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/bc0447b2c5922d22aa2c40e2c7559a8b48464f8d/src/ai/smach_buoy.py#L202)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Another candidate for configuring. I mention these because I know that a given amount of time in the simulator will probably not be enough in the real world and we'll be modifying these a lot.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/293)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/293#-:-KthECXW8GTLZJ062SFu:bnfp4nl)*

**Pull request merged**
