### PR TITLE
Lance/paramfiles

### PR DESCRIPTION
**Pull request by neprotalis**
Peter and I worked to create a common launch file for ease of use. I split up our general cobalt param file to a few that more closely match what we are launching. These will be further updated as more systems are fleshed out such as AI.
**Since I modified the param files, the simulator will not launch without the updated gazebo.launch, so that will need to be merged as well.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/314)

### CODE REVIEW

**Comment by Sindorman** [comment]
Travis is crashing while trying to load some parameters from `cobalt.yaml`, and `ironman.yaml`(why such name? :/ ). @irwineffect or @skallaher need to take a look if it's okay.

**Comment by skallaher** [comment]
This is to be expected as the simulator currently does not reflect the changes in this PR.

**Comment by skallaher** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[launch/ai.launch, line 6 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/314#-KwNC72-oZW12D4si56Q:-KwNC72-oZW12D4si56R:b6b24lr) ([raw file](https://github.com/palouserobosub/robosub/blob/6ee63296eda8e1f86fbcea34060a77aaa4728622/launch/ai.launch#L6)):*
> ```XML
>         <rosparam command="load" file="$(find robosub)/param/ai_manager.yaml"/>
>     </node>
> </launch>
> ```

Why has this file been deleted? It will still be necessary, it is simply outdated.

---

*[launch/core.launch, line 10 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/314#-KwNCGeBLxsByk743VZt:-KwNCGeBLxsByk743VZu:b-9t2qu) ([raw file](https://github.com/palouserobosub/robosub/blob/8dad12f3dcaa96a18c0044ffd2163cd283cbe102/launch/core.launch#L10)):*
> ```XML
>     <include file="$(find robosub)/launch/sensors.launch"/> 
>     <include file="$(find robosub)/launch/cameras.launch"/> 
>     <include file="$(find robosub)/launch/vision.launch"/> 
> ```

The comment is misleading as to how you're using this file.

---

*[launch/movement.launch, line 6 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/314#-KwNCNzVDpCixajm7eU9:-KwNCNzVDpCixajm7eUA:bglbyah) ([raw file](https://github.com/palouserobosub/robosub/blob/8dad12f3dcaa96a18c0044ffd2163cd283cbe102/launch/movement.launch#L6)):*
> ```XML
>     <node name="thruster" pkg="robosub" type="thruster_maestro"/>
>     <node name="control" pkg="robosub" type="control"/>
>     <rosparam command="load" file="$(find robosub)/param/movement.yaml"/>
> ```

You should load parameters first. There isn't a guaranteed order to things in launch files, but you should be explicit by putting the param loads first.

---

*[launch/sensors.launch, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/314#-KwNCWdkbqQBt7lqXbXF:-KwNCWdkbqQBt7lqXbXG:b-1v5qjh) ([raw file](https://github.com/palouserobosub/robosub/blob/8dad12f3dcaa96a18c0044ffd2163cd283cbe102/launch/sensors.launch#L1)):*
> ```XML
> <?xml version="1.0"?>:
> ```

Please remove the colon here.

---

*[param/hydrophones.yaml, line 2 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/314#-KwNCfu79fNi1d1dAmsW:-KwNCfu79fNi1d1dAmsX:b-evf3ix) ([raw file](https://github.com/palouserobosub/robosub/blob/8dad12f3dcaa96a18c0044ffd2163cd283cbe102/param/hydrophones.yaml#L2)):*
> ```YAML
> rate:
>     localization: 30
> ```

This rate parameter is for the localization node, not for the hydrophones.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/314)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[launch/movement.launch, line 6 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/314#-KwNCNzVDpCixajm7eU9:-KwO2D8933NCWpXS-kIO:b-v7rzzk) ([raw file](https://github.com/palouserobosub/robosub/blob/8dad12f3dcaa96a18c0044ffd2163cd283cbe102/launch/movement.launch#L6)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

You should load parameters first. There isn't a guaranteed order to things in launch files, but you should be explicit by putting the param loads first.
</blockquote></details>

Actually launch files are loaded in order. What isn't guaranteed is that a node will have been completely booted before the node in the tag following it. But because both the thruster_maestro and the control nodes use the parameters in the movement.yaml file the rosparam tag should be moved before the attempts to start them. This way the parameters will be guaranteed to be ready by the time the nodes boot up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/314)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[launch/movement.launch, line 6 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/314#-KwNCNzVDpCixajm7eU9:-KwR1MgfEhJe2Ci70L7x:b-eb306q) ([raw file](https://github.com/palouserobosub/robosub/blob/8dad12f3dcaa96a18c0044ffd2163cd283cbe102/launch/movement.launch#L6)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Actually launch files are loaded in order. What isn't guaranteed is that a node will have been completely booted before the node in the tag following it. But because both the thruster_maestro and the control nodes use the parameters in the movement.yaml file the rosparam tag should be moved before the attempts to start them. This way the parameters will be guaranteed to be ready by the time the nodes boot up.
</blockquote></details>

In addition, it is generally easier to read and understand if the parameter loading is done first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/314)*

**Comment by Sindorman** [comment]
Reviewed 11 of 12 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[launch/ai.launch, line 6 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/314#-KwNC72-oZW12D4si56Q:-KyyueO67wf_T4LZGZ1W:ba9xcpv) ([raw file](https://github.com/palouserobosub/robosub/blob/6ee63296eda8e1f86fbcea34060a77aaa4728622/launch/ai.launch#L6)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why has this file been deleted? It will still be necessary, it is simply outdated.
</blockquote></details>

Hmm.. True.

---

*[param/sensors.yaml, line 13 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/314#-Kyyv7ss_yJWfASir2ID:-Kyyv7ss_yJWfASir2IE:b-mkcdoj) ([raw file](https://github.com/palouserobosub/robosub/blob/8dad12f3dcaa96a18c0044ffd2163cd283cbe102/param/sensors.yaml#L13)):*
> ```YAML
>         z: 3
> bno055_right:
>     port: "/dev/bno055_right"
> ```

FYI - do we even need bno055_right/left there? We are using trax mainly. Hmm...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/314)*

**Comment by ryan-summers** [comment]
Closing this due to deprecation.

**Pull request closed without merging**
