### PR TITLE
Fix for the Sabertooth Test

### PR DESCRIPTION
**Pull request by bkallaher**
Wait for port parameter to be available

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/229)

### CODE REVIEW

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by irwineffect** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/229#-:-KgREEnvQ3y9-83dgIlC:bnfp4nl)*

**Pull request merged**
