### PR TITLE
Addition of linear acceleration to Bno055

### PR DESCRIPTION
**Pull request by ryan-summers**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/160)

### CODE REVIEW

**Comment by bkallaher** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/Bno055.cpp, line 144 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/160#-Kb2DpIadsCyZXqVxfgJ:-Kb2DpIadsCyZXqVxfgK:bewjdrz) ([raw file](https://github.com/palouserobosub/robosub/blob/c9dcbe9c696bd0dfb7e4e97edd5dd3896916d252/src/sensors/Bno055.cpp#L144)):*
> ```cpp
>     {
>         vector<uint8_t> data;
>         AbortIf(read_register(Bno055::Register::LIA_Data_X_LSB, data, 6));
> ```

Maybe comment about what the heck LIA_DATA_X_LSB is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160#-:-Kb2Jm-cBYRrwg0YMTek:bnfp4nl)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/Bno055.cpp, line 144 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/160#-Kb2DpIadsCyZXqVxfgJ:-Kb36I5T9L_AxyO8UWru:b-kgqrw2) ([raw file](https://github.com/palouserobosub/robosub/blob/c9dcbe9c696bd0dfb7e4e97edd5dd3896916d252/src/sensors/Bno055.cpp#L144)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Maybe comment about what the heck LIA_DATA_X_LSB is.
</blockquote></details>

I personally think the namespace declaration makes it pretty obvious. It's within the Bno055, it's a register, and its in a function that comments about how you are reading LInear Acceleration. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160)*

**Comment by bkallaher** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/sensors/Bno055.cpp, line 144 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/160#-Kb2DpIadsCyZXqVxfgJ:-Kb3AbDTKvn4mBBhIZRE:b3l1kx8) ([raw file](https://github.com/palouserobosub/robosub/blob/c9dcbe9c696bd0dfb7e4e97edd5dd3896916d252/src/sensors/Bno055.cpp#L144)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I personally think the namespace declaration makes it pretty obvious. It's within the Bno055, it's a register, and its in a function that comments about how you are reading LInear Acceleration. 
</blockquote></details>

A comment would still be nice saying that you are grabbing all linear acceleration values with one `read_register()` call. When I first looked at it I thought you were not getting the y and z accelerations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/Bno055.cpp, line 144 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/160#-Kb2DpIadsCyZXqVxfgJ:-Kb3CspzT4rxH-HW73-x:b-5utlmt) ([raw file](https://github.com/palouserobosub/robosub/blob/c9dcbe9c696bd0dfb7e4e97edd5dd3896916d252/src/sensors/Bno055.cpp#L144)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

A comment would still be nice saying that you are grabbing all linear acceleration values with one `read_register()` call. When I first looked at it I thought you were not getting the y and z accelerations.
</blockquote></details>

This is the same syntax used throughout the file for multi-read of registers as shown on lines 115 and and 167. I don't see why this is any different.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/Bno055.cpp, line 144 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/160#-Kb2DpIadsCyZXqVxfgJ:-Kb3HjmnFIoigzqat6CD:bdkfixp) ([raw file](https://github.com/palouserobosub/robosub/blob/c9dcbe9c696bd0dfb7e4e97edd5dd3896916d252/src/sensors/Bno055.cpp#L144)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

This is the same syntax used throughout the file for multi-read of registers as shown on lines 115 and and 167. I don't see why this is any different.
</blockquote></details>

The only real reason I'm opposed to adding a comment here is that it's pretty much the only thing of import in the whole function. It seems odd to comment when there's nothing else here and it's already commented above the declaration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160)*

**Comment by skallaher** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/Bno055.cpp, line 144 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/160#-Kb2DpIadsCyZXqVxfgJ:-Kb3mdQAaKBYV9P2sFmf:b93s84c) ([raw file](https://github.com/palouserobosub/robosub/blob/c9dcbe9c696bd0dfb7e4e97edd5dd3896916d252/src/sensors/Bno055.cpp#L144)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

The only real reason I'm opposed to adding a comment here is that it's pretty much the only thing of import in the whole function. It seems odd to comment when there's nothing else here and it's already commented above the declaration.
</blockquote></details>

A small note that says, "Grab the X, Y, and Z linear acceleration values" wouldn't really be amiss. Also, below, information on why the values are being scaled by a 1/100th would be useful for future reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160)*

**Comment by ryan-summers** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/Bno055.cpp, line 144 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/160#-Kb2DpIadsCyZXqVxfgJ:-Kb6Y0WiwFVO0yCX-pJe:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/c9dcbe9c696bd0dfb7e4e97edd5dd3896916d252/src/sensors/Bno055.cpp#L144)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

A small note that says, "Grab the X, Y, and Z linear acceleration values" wouldn't really be amiss. Also, below, information on why the values are being scaled by a 1/100th would be useful for future reference.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160#-:-Kb6_KqAYXaSBoX2J-_c:bnfp4nl)*

**Comment by bkallaher** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/160)*

**Pull request merged**
