### PR TITLE
Connor/loc/repair3

### PR DESCRIPTION
**Pull request by connor-wool**
Well, that was ugly but I managed to cherry-pick and avoid the merge commit.

From previous PR attempt:

This pull request contains multiple localization improvements.

While it does not affect the final normalized probability values, the float value 100.0 is now used instead of 1.0 during the update stage as a "default max" probability value. This should help prevent any possibility of overflowing or underflowing the value with intermediate multiplications or divisions.

The number of particles was increased from 2000 to 5000. I observed that having a larger number of particles helped increase the speed at which the particles converged during the starting period where the sub reconciles its true location with the hard-coded "starting position" values. I believe this behavior will help improve how quickly the sub recovers from the point cloud drifting off. The one downside is that it makes the estimate slightly less precise while increasing accuracy.

There is a set of values used as the "sigma" value in assigning probabilities to the points. Having a low sigma value seems to cause very steep tails, while having a value closer to 1 causes a more gradual gradient drop-off. The values were originally 0.001, I have changed them to 0.1. This seemed to help the accuracy of the particle cloud.

Particles are now re-generated in a cloud based on the last estimated point. Previously, the cloud was re-generated based on a random selection of old points with noise added. Now, if there is a current estimated point, that point is used (with fuzzing from normal distribution and std. dev. values from our params file) to generate a new cloud around the sub. If no current estimate exists, the old method is still used.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/340)

### CODE REVIEW

**Comment by connor-wool** [comment]
LGTM

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/340#-:-KzRPvTO4dKLn4jV3JTJ:bb6ywmx)*

**Comment by skallaher** [comment]
@connor-wool, please also do not approve your own PRs. There is no sense in doing so.

**Comment by Sindorman** [comment]
Code-wise changes seems to be legitimate. But I do not know if it works.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/340#-:-KzVwqxkQX_zjJ-ZQRW8:bj2ojez)*

**Comment by connor-wool** [comment]
I ran this on my own simulator copy, and it seemed to be equivalent or better to the previous resampling methods. This still retains the old method of resampling as well, which is used to resample in between estimated positions being calculated.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/340#-:-L-DptNrk-g6yJIRn_1m:bmsxczq)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/340#-:-L3jmqusWNOCyM31_Zox:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/340)*

**Comment by btmoore** [comment]
First off, if you have a localization engine of some sort that gives you accurate enough measurements, then that could be good enough and you could focus on other things.

With that said, you should be made aware that particles being re-sampled from previous particles is an important step in the particle filter, and by removing it you are removing most of the particle filter's functionality.  

What you have now, if I'm understanding it right, should end up working, in that it will converge on a value and adjust itself somewhat to new measurements.  But essentially you've gone and created a computationally less inefficient, mathematically less precise kalman filter.  The purpose of using a Particle filter is that it is able to easily synthesize measurements with non-Gaussian noise (ie all your polar measurements from hydrophone and cameras), and form a hypothesis with non-Gaussian probability distributions.  Furthermore it can track multiple hypotheses in the case of ambiguous measurements and preserve that information into the future until later measurements wipe away the false hypotheses.  In exchange for this, instead of doing calculations purely by tracking the estimate and covariance of that estimate like in a Kalman Filter, you track a point cloud of thousands of multi-dimensional particles.  So memory and computation is more expensive.

By condensing that point cloud down to a mean and std each cycle, you're basically throwing away all that information. And on the next cycle when you do the same thing - you're performing the kalman filter calculation, but instead of doing it analytically with means and variances, you're brute-forcing it by spawning a particle cloud first from those stats, adjusting each particle individually, and re-calculating the stats on the cloud. And since you can't use infinite particles, that brute-force is still going to be less accurate than doing the direct calculation, despite the 100x-1000x computation time.

As a side note - while particles not converging at all would demonstrate a problem, particles converging too much or too quickly is not necessarily a good thing. The variance (the size of the cloud) represents the lack of certainty in your position, and you never want to be more certain about your position that you should be.  Given your sensors, I'd expect you to have a very flat (narrow z-axis) ellipsoid with 1 standard deviation (uncertainty) in the xy plane on the order of tens to hundreds of centimeters.

Anyway, if you have something that works, use what works.  That should always be priority 1.  But this is really defeating the purpose of using such a complex algorithm in the first place.  If this is a final form you might be better off abandoning the particle filter entirely.

**Comment by skallaher** [comment]
As a note, @btmoore, this is a bit of an outdated version. There should be a new PR coming in soon from the team with their work from the last semester. @connor-wool, does this PR still need to exist?

**Comment by connor-wool** [comment]
Ryan asked me to prune out old issues and PR's that have died; this is one such PR. As such, it will now disappear, forever to be relegated to the dark abyss of failed PR's.

**Pull request closed without merging**
