### PR TITLE
Stereo Calibration

### PR DESCRIPTION
**Pull request by skallaher**
Calibration results are decent. Processing of stereo data is still untested.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/187)

### CODE REVIEW

**Comment by bkallaher** [comment]
There's a lot of cleanup that could be done, especially in the StereoCalibrator.cpp file.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vision/calib/stereo_default.xml, line 7 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-Kd7L3Wegjf6cCQvgUtK:-Kd7L3Wegjf6cCQvgUtL:beoneib) ([raw file](https://github.com/palouserobosub/robosub/blob/c6d0839fae8e431757637e939a8ad72c734ba785/src/vision/calib/stereo_default.xml#L7)):*
> ```XML
>     <BoardSize_Width>8</BoardSize_Width>
>     <BoardSize_Height>5</BoardSize_Height>
>          
> ```

There's a lot of blank lines with white space in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-:-Kd7Ms5o0jBrKThNxP9J:b-zprq0)*

**Comment by skallaher** [comment]
Will do. I'm also in the middle of other fixes and updates as well.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-:-Kdb9wYH-yjRz59i0By7:b-bq29oc)*

**Comment by bkallaher** [comment]
Reviewed 10 of 12 files at r2.
Review status: 18 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/vision/Vision.cpp, line 184 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-KdrO49XoMQ0lu-6r2Kd:-KdrO49XoMQ0lu-6r2Ke:bdcndlu) ([raw file](https://github.com/palouserobosub/robosub/blob/beb68abe934be87ad0a0e61d68c738dae9119061/src/vision/Vision.cpp#L184)):*
> ```cpp
>     //Create a stereo processor
>     StereoProcessor stereoProc;
>     
> ```

Whitespace!!!!

---

*[src/vision/calib/stereo_default.xml, line 7 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-Kd7L3Wegjf6cCQvgUtK:-KdrOV99nrrZubE_VV06:b3144yq) ([raw file](https://github.com/palouserobosub/robosub/blob/c6d0839fae8e431757637e939a8ad72c734ba785/src/vision/calib/stereo_default.xml#L7)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

There's a lot of blank lines with white space in this file.
</blockquote></details>

It's still here...

---

*[src/vision/calib/StereoCalibrator.cpp, line 261 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-KdrOxx_nW-8vu9Wrr_U:-KdrOxx_nW-8vu9Wrr_V:b-8th5ks) ([raw file](https://github.com/palouserobosub/robosub/blob/beb68abe934be87ad0a0e61d68c738dae9119061/src/vision/calib/StereoCalibrator.cpp#L261)):*
> ```cpp
>     saveExtrinsics(R, T, R1, R2, P1, P2, F, E, Q);
> 
>     outputFile.release();
> ```

Where is this file opened/is it guaranteed to be open?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187)*

**Comment by bkallaher** [comment]
Reviewed 3 of 5 files at r3.
Review status: 18 of 21 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/vision/FeatureProcessor.cpp, line 2 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-Kdy6D5CXVb_3g23AotP:-Kdy6D5CXVb_3g23AotQ:b-h0m55m) ([raw file](https://github.com/palouserobosub/robosub/blob/abfde7cfc521bf035daef529bb59a69427df3a3f/src/vision/FeatureProcessor.cpp#L2)):*
> ```cpp
> #include "FeatureProcessor.hpp"
> #include <algorithm>
> ```

Is there a reason these are included in both the header and source?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187)*

**Comment by bkallaher** [comment]
Reviewed 1 of 12 files at r2, 2 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/vision/FeatureProcessor.cpp, line 2 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-Kdy6D5CXVb_3g23AotP:-Kdy7nrgmGSCKSm9Gtff:bxpccb) ([raw file](https://github.com/palouserobosub/robosub/blob/abfde7cfc521bf035daef529bb59a69427df3a3f/src/vision/FeatureProcessor.cpp#L2)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Is there a reason these are included in both the header and source?
</blockquote></details>

The linter requires the .cpp to have it (include what you use), but typically the header is the correct place to put this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187)*

**Comment by bkallaher** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-:-Ke5Mw9WSkCjpnVFU21t:bnfp4nl)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vision/calib/stereo_default.xml, line 7 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-Kd7L3Wegjf6cCQvgUtK:-Ke6Ksd9hvQzs14DsglC:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/c6d0839fae8e431757637e939a8ad72c734ba785/src/vision/calib/stereo_default.xml#L7)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

It's still here...
</blockquote></details>

Done.

---

*[src/vision/calib/StereoCalibrator.cpp, line 261 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/187#-KdrOxx_nW-8vu9Wrr_U:-Ke6KpdP9JYVYs4I-tGp:b-nxd782) ([raw file](https://github.com/palouserobosub/robosub/blob/beb68abe934be87ad0a0e61d68c738dae9119061/src/vision/calib/StereoCalibrator.cpp#L261)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Where is this file opened/is it guaranteed to be open?
</blockquote></details>

This is opened in the constructor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187)*

**Comment by bkallaher** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/187)*

**Pull request merged**
