### PR TITLE
Bagging undistorted images.

### PR DESCRIPTION
**Pull request by Sindorman**
Changed record.launch to bag undistorted images, instead of raw.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/389)

### CODE REVIEW

**Comment by ryan-summers** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/389#-:-L51R7IQLZk7MJHhyYtS:bnfp4nl)*

**Comment by irwineffect** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://beta.reviewable.io/reviews/palouserobosub/robosub/389#-L56QPCi1uQ9DHT9IueX:-L56QPCi1uQ9DHT9IueY:b-6xgg4t) (no related file):*
Hey, I ran this change on the sub, for some reason the bags are about 3 times bigger (given the same number of images) when they contain images coming from the undistortion node. I think there's still a bug in our undistortion code, and I propose we try to use the official ROS undistortion node: http://wiki.ros.org/image_proc

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/palouserobosub/robosub/389)*

**Comment by Sindorman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/389#-L56QPCi1uQ9DHT9IueX:-L57cSe3iSIP4dP8DPNA:b6jr4sz) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Hey, I ran this change on the sub, for some reason the bags are about 3 times bigger (given the same number of images) when they contain images coming from the undistortion node. I think there's still a bug in our undistortion code, and I propose we try to use the official ROS undistortion node: http://wiki.ros.org/image_proc
</blockquote></details>

Interesting, but that means that our raw bags that were undistorted manually should also be 3 times bigger than raw. Since we always undistorted them through our node, so in the end they are increased in size?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/389)*

**Comment by brennanpeter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/palouserobosub/robosub/389#-L56QPCi1uQ9DHT9IueX:-L9gGabw7TQQxOOLqDYZ:b9ycmf1) (no related file):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Interesting, but that means that our raw bags that were undistorted manually should also be 3 times bigger than raw. Since we always undistorted them through our node, so in the end they are increased in size?
</blockquote></details>

I'll merge this in when this discussion gets resolved

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/palouserobosub/robosub/389)*

**Comment by Sindorman** [comment]
@irwineffect James, do you think we can merge this?

**Pull request closed without merging**
