### PR TITLE
Addition of sensor calibration node

### PR DESCRIPTION
**Pull request by ryan-summers**
Sensor calibration node can be used for generating a sensor calibration profile to load into the cobalt settings file for power-on-reset sensor configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/191)

### CODE REVIEW

**Comment by irwineffect** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/bno055_calibration.cpp, line 93 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/191#-KdxqY3dRvwHPqINHD1A:-KdxqY3dRvwHPqINHD1B:b-s6ap8s) ([raw file](https://github.com/palouserobosub/robosub/blob/467462fe395a9b449073a0bf795428236d27dedc/src/sensors/bno055_calibration.cpp#L93)):*
> ```cpp
> 
>     cout << "A Offsets: X: " << acc_offset[0] << " Y: " << acc_offset[1]
>             << " Z: " << acc_offset[2] << endl;
> ```

have you tried importing this yaml output? I think you might need {} to group the x,y,z, or put them on indented new lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/191)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sensors/bno055_calibration.cpp, line 41 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/191#-Kdy8aRpqE5_ZtlbKb9s:-Kdy8aRpqE5_ZtlbKb9t:b-n4xjei) ([raw file](https://github.com/palouserobosub/robosub/blob/467462fe395a9b449073a0bf795428236d27dedc/src/sensors/bno055_calibration.cpp#L41)):*
> ```cpp
> {
>     ros::init(argc, argv, "sensor_calibration");
>     ros::Time::init();
> ```

This shouldn't be required as it is called within the ros::init() function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/191)*

**Comment by dcrossman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/191#-:-KdyICgW22PopsvuR3kT:bnfp4nl)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/sensors/bno055_calibration.cpp, line 41 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/191#-Kdy8aRpqE5_ZtlbKb9s:-Ke045LqljCFp9gIMIcK:b3v3pya) ([raw file](https://github.com/palouserobosub/robosub/blob/467462fe395a9b449073a0bf795428236d27dedc/src/sensors/bno055_calibration.cpp#L41)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

This shouldn't be required as it is called within the ros::init() function.
</blockquote></details>

actually,  it's the creation of a nodehandle that initializes time. However, for this particular scenario where the node isn't doing any talking, it is correct to just use ros::time::init() instead of the overhead of creating a nodehandle.

---

*[src/sensors/bno055_calibration.cpp, line 44 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/191#-Ke08j10PJJeNxIJrIeN:-Ke08j10PJJeNxIJrIeO:bt9zu8i) ([raw file](https://github.com/palouserobosub/robosub/blob/467462fe395a9b449073a0bf795428236d27dedc/src/sensors/bno055_calibration.cpp#L44)):*
> ```cpp
>     string port_name;
> 
>     HandleError(ros::param::getCached("/ports/sensor", port_name) == false,
> ```

No need to use the getCached() function here, just use get()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/191)*

**Comment by ryan-summers** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sensors/bno055_calibration.cpp, line 44 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/191#-Ke08j10PJJeNxIJrIeN:-Ke0XB4alBPVJG6aXf2W:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/467462fe395a9b449073a0bf795428236d27dedc/src/sensors/bno055_calibration.cpp#L44)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

No need to use the getCached() function here, just use get()
</blockquote></details>

Done.

---

*[src/sensors/bno055_calibration.cpp, line 93 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/191#-KdxqY3dRvwHPqINHD1A:-Ke0XCpQMlZcwR3Uhmdm:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/467462fe395a9b449073a0bf795428236d27dedc/src/sensors/bno055_calibration.cpp#L93)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

have you tried importing this yaml output? I think you might need {} to group the x,y,z, or put them on indented new lines.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/191)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/191#-:-Ke0_dl8vNhrla06qnN4:bnfp4nl)*

**Pull request merged**
