### PR TITLE
Control test update

### PR DESCRIPTION
**Pull request by bkallaher**
Added rotational control system tests.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/201)

### CODE REVIEW

**Comment by ryan-summers** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/movement/test/test_control_system.cpp, line 52 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-KeQ1rjyhO5Ckl8vk5gA:-KeQ1rjzHJuFMfuMDQek:b-vbkjsl) ([raw file](https://github.com/palouserobosub/robosub/blob/dcec7262a77927115dba182b27ca26a5d406dad0/src/movement/test/test_control_system.cpp#L52)):*
> ```cpp
>     ROS_INFO("rolling to test angle");
>     //wait for 5 secosds for the sub to reach its roll
>     ros::Time exit_time = ros::Time::now() + ros::Duration(10);
> ```

Please correct these copypasta fails

---

*[src/movement/test/test_control_system.cpp, line 61 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-KeQ22IRTcCRn84Ee9sS:-KeQ22IRTcCRn84Ee9sT:b-jhq48r) ([raw file](https://github.com/palouserobosub/robosub/blob/dcec7262a77927115dba182b27ca26a5d406dad0/src/movement/test/test_control_system.cpp#L61)):*
> ```cpp
> 
>     //confirm we didn't roll too far
>     EXPECT_GT(test_roll + overshoot_allowed, analyzer.GetMax());
> ```

Can you switch the arguments and go to EXPECT_LT? It makes more logical sense to see the max is less than the overshoot allowed

---

*[src/movement/test/test_control_system.cpp, line 120 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-KeQ2ecUVHt9cvYu05Um:-KeQ2ecUVHt9cvYu05Un:bqujbyh) ([raw file](https://github.com/palouserobosub/robosub/blob/dcec7262a77927115dba182b27ca26a5d406dad0/src/movement/test/test_control_system.cpp#L120)):*
> ```cpp
>     ROS_INFO("pitching to test angle");
>     //wait for 5 secosds for the sub to reach its pitch
>     ros::Time exit_time = ros::Time::now() + ros::Duration(10);
> ```

Here too

---

*[src/movement/test/test_control_system.cpp, line 129 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-KeQ2ftHrLFx41sJ_eZO:-KeQ2ftIDd5q7y-HsOsv:b-34vmyd) ([raw file](https://github.com/palouserobosub/robosub/blob/dcec7262a77927115dba182b27ca26a5d406dad0/src/movement/test/test_control_system.cpp#L129)):*
> ```cpp
> 
>     //confirm we didn't roll too far
>     EXPECT_GT(test_pitch + overshoot_allowed, analyzer.GetMax());
> ```

See above

---

*[src/movement/test/test_control_system.cpp, line 188 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-KeQ2sMmFmGXkTdff63A:-KeQ2sMmFmGXkTdff63B:bji28bi) ([raw file](https://github.com/palouserobosub/robosub/blob/dcec7262a77927115dba182b27ca26a5d406dad0/src/movement/test/test_control_system.cpp#L188)):*
> ```cpp
>     ROS_INFO("yawing to test angle");
>     //wait for 5 secosds for the sub to reach its yaw
>     ros::Time exit_time = ros::Time::now() + ros::Duration(20);
> ```

and here

---

*[src/movement/test/test_control_system.cpp, line 197 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-KeQ2ti2rCa2_GA-m6Vj:-KeQ2ti2rCa2_GA-m6Vk:b-8a05gs) ([raw file](https://github.com/palouserobosub/robosub/blob/dcec7262a77927115dba182b27ca26a5d406dad0/src/movement/test/test_control_system.cpp#L197)):*
> ```cpp
> 
>     //confirm we didn't yaw too far
>     EXPECT_GT(test_yaw + overshoot_allowed, analyzer.GetMax());
> ```

As above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/201)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-:-KeQ4E4b-tUe53tskA05:bnfp4nl)*

**Comment by irwineffect** [comment]
Reviewed 2 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/201)*

**Comment by ryan-summers** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-:-KeQ9xh45wWgL46b1BOm:bnfp4nl)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-KeQAsajNiM9-PEwtohc:-KeQAsak4oONLJghALQC:b-w89t62) (no related file):*
I noticed that in the initial test the sub gets a depth set at the same time as the roll is done, I think it has the potential to mess up the test, or at the very least it causes your test to test multiple things at once (which I don't think is your intention). I would dive, wait, then set roll. Same for pitch and yaw.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/201)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-:-KeQivNUw4saYMi-stKu:bnfp4nl)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/201#-KeQAsajNiM9-PEwtohc:-KeQjg8bwX-dvtryJPUb:bb6un1j) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

I noticed that in the initial test the sub gets a depth set at the same time as the roll is done, I think it has the potential to mess up the test, or at the very least it causes your test to test multiple things at once (which I don't think is your intention). I would dive, wait, then set roll. Same for pitch and yaw.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/201)*

**Pull request merged**
