### PR TITLE
flipped directions for roll and pitch

### PR DESCRIPTION
**Pull request by irwineffect**
Tested with @ryan-summers on the sub, looks good.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/193)

### CODE REVIEW

**Comment by ryan-summers** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/bno055_sensor.cpp, line 250 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/193#-KdxqIvo0rqctPWDf8Qq:-KdxqIvplgQimJu-C4rF:bg6c8n5) ([raw file](https://github.com/palouserobosub/robosub/blob/5a90401373d12f3bd7552115989007b5a581059f/src/sensors/bno055_sensor.cpp#L250)):*
> ```cpp
> 
>         euler_message.roll = -roll * _180_OVER_PI;
>         euler_message.pitch = -pitch * _180_OVER_PI;
> ```

Please change thee to (-1) * 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/193)*

**Comment by ryan-summers** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/193#-:-KdxtsWrf3ihOnRPtfAT:bnfp4nl)*

**Comment by dcrossman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/193#-:-KdyIPybWMzWw260MqVc:bnfp4nl)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/bno055_sensor.cpp, line 250 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/193#-KdxqIvo0rqctPWDf8Qq:-Ke03ryzfm_lHJCO5Gih:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/5a90401373d12f3bd7552115989007b5a581059f/src/sensors/bno055_sensor.cpp#L250)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Please change thee to (-1) * 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/193)*

**Pull request merged**
