### PR TITLE
Zpratt/start switch

### PR DESCRIPTION
**Pull request by AtomicCharge**
start switch code

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/287)

### CODE REVIEW

**Comment by irwineffect** [comment]
reopening with master branch as base

**Comment by skallaher** [comment]
Needs to be rebased on master and has a few linter errors.

**Comment by bsongras** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/287)*

**Comment by skallaher** [comment]
Needs to me

**Comment by skallaher** [comment]
Needs to be rebased onto master

**Pull request merged**
