### PR TITLE
Easy bag processing and upload script

### PR DESCRIPTION
**Pull request by Sindorman**
- Made a script named `upload_bags.sh` that takes bag as an argument. Took `unbagger.py` and `split_data.sh` from `vision` repo, merged split, and modified `unbagger.py`.

**Note: it does not undistort bags. If required, undistortion can be added to it.**

This will allow to process bag, and upload batches to the server in one command line. Requires user to have user on robosub server.

Script will:

1. Unbag it

2. Split it

3. Add json files to each batch.

4. tar batches.

5. Upload batches to robosub server into `/data/vision/labeling/labeling_todo/current` folder. 

6. Keeps original bag on the sub, so that user decides if it needs to be deleted.

**Currently requires bag to be in the same directory as script.**

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/394)

### CODE REVIEW

**Comment by ryan-summers** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[src/vision/util/unbagger.py, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WIf2qmxuSaBe8Lc-w:-L5WIf2qmxuSaBe8Lc-x:bbmp342) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L1)):*
> ```Python
> #!/usr/bin/python
> ```

Move this into robosub/scripts/ please

---

*[src/vision/util/unbagger.py, line 5 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WJ51cD_EA81R7M0fb:-L5WJ51cD_EA81R7M0fc:b-374i9u) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L5)):*
> ```Python
> # Start up ROS pieces.
> PKG = 'robosub'
> import roslib; roslib.load_manifest(PKG)
> ```

What's this load_manifest do? We normally don't need it.

---

*[src/vision/util/unbagger.py, line 7 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WJRlFDidoJJQqjuyk:-L5WJRlFDidoJJQqjuyl:bs3cpxk) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L7)):*
> ```Python
> import roslib; roslib.load_manifest(PKG)
> import rosbag
> import rospy
> ```

You shouldn't need rospy for this script. It's not a ROS node.

---

*[src/vision/util/unbagger.py, line 8 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WJ8eqEImr1WejE-Gg:-L5WJ8eqEImr1WejE-Gh:botejvy) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L8)):*
> ```Python
> import rosbag
> import rospy
> import cv2 as cv
> ```

Just import it as cv2 and use cv2.(...) to avoid confusion please.

---

*[src/vision/util/unbagger.py, line 14 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WJCiRn3hpiVYweuJo:-L5WJCiRn3hpiVYweuJp:b-11eieh) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L14)):*
> ```Python
> # Reading bag filename from command line or roslaunch parameter.
> import os
> import sys
> ```

You shouldn't need either of these imports

---

*[src/vision/util/unbagger.py, line 20 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WIz6LNmORYhIvOUH9:-L5WIz6LNmORYhIvOUHA:b-vg87ws) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L20)):*
> ```Python
>     def __init__(self):
>         # Get parameters when starting node from a launch file.
>         if len(sys.argv) != 2:
> ```

Do _not_ construct objects like this. Have the construct accept parameters and use argparse to take in system arguments.

---

*[src/vision/util/unbagger.py, line 27 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WJKT6f3xuMABz5PF1:-L5WJKT6f3xuMABz5PF2:bd6yy6h) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L27)):*
> ```Python
>         else:
>             filename = os.path.join(sys.path[0], sys.argv[1] + ".bag")
>             rospy.loginfo("Bag filename = %s", filename)
> ```

Just have the script take in the bag file name

---

*[src/vision/util/unbagger.py, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WJW3LVF0v3zUL-AXN:-L5WJW3LVF0v3zUL-AXO:bqrou76) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L33)):*
> ```Python
> 
>         # Open bag file.
>         with rosbag.Bag(filename, 'r') as bag:
> ```

Move this into a separate process() function please.

---

*[src/vision/util/unbagger.py, line 47 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WJbIW3WV7zpBat9uo:-L5WJbIW3WV7zpBat9up:b-vak2z9) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L47)):*
> ```Python
>                 except CvBridgeError, e:
>                     print (e)
>             for topic, msg, t in bag.read_messages(connection_filter=self.filter_wfov_image):
> ```

We don't have any WFOV messages anymore to my knowledge. Please delete this section

---

*[src/vision/util/unbagger.py, line 67 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WJrrs0OZpoHPy55Vb:-L5WJrrs0OZpoHPy55Vc:br1bqo4) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L67)):*
> ```Python
>     # Allows only WFOVImage messages
>     def filter_wfov_image(self, topic, datatype, md5sum, msg_def, header):
>         return (True if "wfov_camera_msgs/WFOVImage" in datatype else False)
> ```

You don't use these filter_ functions (nor should you, just use list comprehension in-line) Please delete them.

---

*[src/vision/util/unbagger.py, line 72 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WJxQKy9HVToj93eTa:-L5WJxQKy9HVToj93eTb:b-86peaj) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L72)):*
> ```Python
> if __name__ == '__main__':
>     # Initialize the node and name it.
>     rospy.init_node(PKG)
> ```

You don't need to initialize a ROS node - this isn't a node.

---

*[src/vision/util/unbagger.py, line 75 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WIsuWC8WqITEtX7eT:-L5WIsuWC8WqITEtX7eU:b-mowo1t) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/unbagger.py#L75)):*
> ```Python
>     # Go to class functions that do all the heavy lifting. Do error checking.
>     try:
>         image_creator = ImageCreator()
> ```

For the sake of software engineering, please do not process the bar in the constructor... add a process() function that does it all.

---

*[src/vision/util/upload_bags.sh, line 27 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WK66KBp1ScAKS_o0w:-L5WK66KBp1ScAKS_o0x:bsk4rnx) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L27)):*
> ```Shell
> # Unbagging bags.
> echo -n "Unbagging bag."
> ./unbagger.py $DIR
> ```

Please have this take in an actual bag, not a directory.

---

*[src/vision/util/upload_bags.sh, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WKD_oMwakc6xPBYEf:-L5WKD_oMwakc6xPBYEg:b-tpjuqn) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L33)):*
> ```Shell
> 
> # how many files per folder
> fpf=100
> ```

Just name the variable files_per_folder instead of fpf for comprehensibility later.

---

*[src/vision/util/upload_bags.sh, line 59 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WKLVJjZU-tzWD6XpJ:-L5WKLVJjZU-tzWD6XpK:bfa6z28) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L59)):*
> ```Shell
> for d in ${DIR}_sub_* ; do
>     echo "  ${d}_labels.json"
>     sloth appendfiles -u ${d}/${d}_labels.json ${d}/*
> ```

Is sloth installed on the submarine?

---

*[src/vision/util/upload_bags.sh, line 82 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WKSbUGWGBYp-Tn1B1:-L5WKSbUGWGBYp-Tn1B2:bohxkd4) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L82)):*
> ```Shell
> echo
> echo -n "user: "
> read USER
> ```

Use `read -p "User:" USER` for single line print and prompt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/394)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[src/vision/util/upload_bags.sh, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5eJLYpqoiXS55X3fc5:-L5eJLYpqoiXS55X3fc6:bjezg8g) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

After some discussions with james, we would prefer the following changes:
1) Plese use the /tmp/ folder for the temporary files so that all users can read/write (e.g. I can unbag and upload Lance's bag file)
2) Please allow the uploader to access an arbitrary path to a bag.
3) Please convert this script to python for maintainability (it will also make it a lot more comprehensible)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/394)*

**Comment by Sindorman** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[src/vision/util/upload_bags.sh, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5eJLYpqoiXS55X3fc5:-L5fRYy7n1MZjssCldUM:b-mrtjl8) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L1)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

After some discussions with james, we would prefer the following changes:
1) Plese use the /tmp/ folder for the temporary files so that all users can read/write (e.g. I can unbag and upload Lance's bag file)
2) Please allow the uploader to access an arbitrary path to a bag.
3) Please convert this script to python for maintainability (it will also make it a lot more comprehensible)
</blockquote></details>

Alright, I will start working on using SFTP. And make other changes that you mentioned before

---

*[src/vision/util/upload_bags.sh, line 27 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WK66KBp1ScAKS_o0w:-L5fRn93NsGmBcgesOQw:byl6zco) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L27)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Please have this take in an actual bag, not a directory.
</blockquote></details>

Will be changed as script will be written in python

---

*[src/vision/util/upload_bags.sh, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WKD_oMwakc6xPBYEf:-L5fRm6X4qAfo4hdQzEF:bebrt1w) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L33)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Just name the variable files_per_folder instead of fpf for comprehensibility later.
</blockquote></details>

Will do

---

*[src/vision/util/upload_bags.sh, line 59 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WKLVJjZU-tzWD6XpJ:-L5fRrSOIM5NWiXJ8xiR:bjn7cp6) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L59)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Is sloth installed on the submarine?
</blockquote></details>

I think it is not, that would explain why tars had no jsons

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/394)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[src/vision/util/upload_bags.sh, line 59 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/394#-L5WKLVJjZU-tzWD6XpJ:-L5j-noCbhb7TBmAOsEH:b4erls5) ([raw file](https://github.com/palouserobosub/robosub/blob/2ebe05d32dcf188786ee42f142c8c477b809badb/src/vision/util/upload_bags.sh#L59)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

I think it is not, that would explain why tars had no jsons
</blockquote></details>

Update: I installed it, so don't worry. Also, we won't be able to use sloth for generating the annotation files, we'll have to use native python instead (using the JSON library, this is trivial). Sloth encodes all pathnames as absolute, which we can't use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/394)*

**Comment by Sindorman** [comment]
No longer required, replaced by rslabel

**Pull request closed without merging**
