### PR TITLE
Fixed hydrophone bridge unit conversions

### PR DESCRIPTION
**Pull request by ryan-summers**
The bridge was accidentally supplying nanoseconds to the ros time function as seconds. This fixes that conversion.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/411)

### CODE REVIEW

**Review by Sindorman — APPROVED** [review]
Hmm, okay! Changes seem good. Good for merge after we fix Travis. :lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/411#-:-LGqoQNYD5RqfszNgjcp:bf006ps)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by daymare — CHANGES_REQUESTED** [review]
According to the rospy wiki we should be using rospy.Duration.from_sec(float seconds) to get the duration. Blocking for now, let me know if I am missing something.
http://wiki.ros.org/rospy/Overview/Time

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/411#-:-LGvTKC46XpGgRiiG2oK:b2mi7cf)* status: all files reviewed, 1 unresolved discussion (waiting on @ryan-summers)

___
*[src/sensors/hydrophone_bridge.py, line 204 at r1](https://reviewable.io/reviews/palouserobosub/robosub/411#-LGvSiKq0IGpzyTohj1b:-LGvSiKq0IGpzyTohj1c:bpjx4p7) ([raw file](https://github.com/palouserobosub/robosub/blob/411f6e47371d369c21b269db5a31042c27812d3e/src/sensors/hydrophone_bridge.py#L204)):*
> ```Python
>             msg.xDelta = rospy.Duration(deltas.x)
>             msg.yDelta = rospy.Duration(deltas.y)
>             msg.zDelta = rospy.Duration(deltas.z)
> ```

I think these should be rospy.Duration.from_secs(deltas.xyz)
according to the wiki the rospy.Duration constructor takes (int32 seconds, int32 nanoseconds)

**Review by daymare — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/411#-:-LGxlMhZEDIkjCSO7vNK:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/sensors/hydrophone_bridge.py, line 204 at r1](https://reviewable.io/reviews/palouserobosub/robosub/411#-LGvSiKq0IGpzyTohj1b:-LGxlIAl7k9KKycOr7Br:b32w1t) ([raw file](https://github.com/palouserobosub/robosub/blob/411f6e47371d369c21b269db5a31042c27812d3e/src/sensors/hydrophone_bridge.py#L204)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

I think these should be rospy.Duration.from_secs(deltas.xyz)
according to the wiki the rospy.Duration constructor takes (int32 seconds, int32 nanoseconds)
</blockquote></details>

Ok

**Comment by Sindorman** [comment]
Still have to fix Travis. But I think we can bypass it and merge. Travis is screwed for now.

**Review by Sindorman — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/411)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
