### PR TITLE
11/5/17 Pool test changes

### PR DESCRIPTION
**Pull request by irwineffect**
- buoy ai parameter tuning
- fixed buoyancy offset _(finally!)_
- added initial depth for searching for buoys

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/333)

### CODE REVIEW

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/333#-:-KyEydthRD1cxX9BXa1A:bnfp4nl)*

**Comment by Sindorman** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[param/ai_pool.yaml, line 8 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/333#-KyF6ypRQTtHQczbicU8:-KyF6ypRQTtHQczbicU9:b-7wbftt) ([raw file](https://github.com/palouserobosub/robosub/blob/4ef3d9ab03d61b180fb6f5d247eb2e2ae4f87086/param/ai_pool.yaml#L8)):*
> ```YAML
>             yaw_speed_factor: -35.0
>             dive_speed_factor: -1.0
>             center_offset: -0.25
> ```

That was causing it to have buoys on left, not right?

---

:lgtm:


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/333)*

**Comment by Sindorman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/333#-:-KyF77PoYO4lzyEgybm4:bnfp4nl)*

**Comment by Sindorman** [comment]
Sorry, I didn't add FYI. I changed it to resolved discussion.

**Comment by irwineffect** [comment]
@Sindorman Yeah that's correct. I think previously we must have been using the right camera for centering on the buoys.

**Pull request merged**
