### PR TITLE
Adds in Dice AI Task

### PR DESCRIPTION
**Pull request by ryan-summers**
The Dice AI task has configurable dice targets and will attempt to find dice that add up to 7 or 11.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/364)

### CODE REVIEW

**Comment by Sindorman** [comment]
FYI: I will check this branch.

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-:-L4NzOi4fH1aqDGlLUTG:b5ptof6)*

**Comment by skallaher** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[src/ai/smach_dice_complete.py, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-L47PWYyyrEZWO5_XY73:-L47PWYyyrEZWO5_XY74:b-87s2zt) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L1)):*
> ```Python
> #!/usr/bin/python
> ```

Why does this file have `complete` in the name?

---

*[src/ai/smach_dice_complete.py, line 48 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-L47RFEcD59LVBMXQxdq:-L47RFEdNu0yDbWemlr5:bje4s5t) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L48)):*
> ```Python
>         """ROS callback for relative obstacle positions."""
>         dice_detections = [obstacle for obstacle in obstacle_position_msg.data
>                            if obstacle.name.endswith('_dice')]
> ```

See PalouseRobosub/vision_dev#10 for the labels used. Either that or we should change the labels used which is just a refactor.

---

*[src/ai/smach_dice_complete.py, line 136 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-L47Tj0YkkxAoJN0luG_:-L47Tj0YkkxAoJN0luGa:b-tqhl0n) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L136)):*
> ```Python
>         # Find the target in the list of detections.
>         target = None
>         for detection in obstacle_position_msg.data:
> ```

I would recommend using the utility functions `getNMostProbable` and `filterByLabel` here. The first one more so as you don't take into account the case of multiple detections, some of which may be false positives that should have a lower confidence.

---

*[src/ai/smach_dice_complete.py, line 142 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-L47UJYAGICJvH9CCfKM:-L47UJYAGICJvH9CCfKN:bblctpn) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L142)):*
> ```Python
> 
>         if target is None:
>             return
> ```

Is not seeing the target you want to center on a failure for this state?

---

*[src/ai/smach_dice_complete.py, line 174 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-L47VZczSgscWoOe0wyr:-L47VZczSgscWoOe0wys:bhw72iu) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L174)):*
> ```Python
>             rospy.loginfo('Ramming {} -> Next Targets: {}'.format(
>                         user_data.target, new_targets))
>             self.exit('success')
> ```

Why do you do this after you publish the control message?

---

*[src/ai/smach_dice_complete.py, line 218 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-L47W1nWoqLsuq9UdB6a:-L47W1nWoqLsuq9UdB6b:b-1i74au) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L218)):*
> ```Python
>             error: The maximum error off nominal distance in meters.
>             speed: The desired correction movement speed.
>             max_duration: The maximum duration of the state in meters.
> ```

Duration usually implies time. Based upon how it's used, doesn't the SubscribeState use it as time, not meters?

---

*[src/ai/smach_dice_complete.py, line 242 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-L4SIbv2L4VxPVOk3Eyg:-L4SIbv2L4VxPVOk3Eyh:bp0zx57) ([raw file](https://github.com/palouserobosub/robosub/blob/ab6524db5826380f9aaef020b6537c7cd6c1e5b5/src/ai/smach_dice_complete.py#L242)):*
> ```Python
> 
>         # Find the closest dice position.
>         closest_distance = 5000
> ```

To initialize this, just use the first detection's distance. That way you don't end up accidentally deciding it is 5000.

---

*[src/ai/util.py, line 33 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-L4SLD2NhiSOw0EhJFfx:-L4SLD2NhiSOw0EhJFfy:b-y44hj7) ([raw file](https://github.com/palouserobosub/robosub/blob/ab6524db5826380f9aaef020b6537c7cd6c1e5b5/src/ai/util.py#L33)):*
> ```Python
>     return detections
> 
> def wrap_yaw(yaw):
> ```

I don't believe this wraps yaw correctly. For example, 181 would be "wrapped" to 1 when it should be -179. Unless I'm missing something here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/364)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/ai/smach_dice_complete.py, line 1 at r1](https://beta.reviewable.io/reviews/palouserobosub/robosub/364#-L47PWYyyrEZWO5_XY73:-L4TVry85y1-1P-yqNhk:b-f036m4) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why does this file have `complete` in the name?
</blockquote></details>

Because there was an initial file that was just smach_dice.py that I initially wrote that just hit the closest die and returned success. Unfortunately, I deleted the file. Do you want me to change this to smach_dice.py?

---

*[src/ai/smach_dice_complete.py, line 136 at r1](https://beta.reviewable.io/reviews/palouserobosub/robosub/364#-L47Tj0YkkxAoJN0luG_:-L4TWX5b8C6Alumj-tA1:b9zbj7p) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L136)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I would recommend using the utility functions `getNMostProbable` and `filterByLabel` here. The first one more so as you don't take into account the case of multiple detections, some of which may be false positives that should have a lower confidence.
</blockquote></details>

This isn't using a DetectionArray data type as it is behind the stereo node. There is no probability associated with detections at this level, so you can't use those functions.

---

*[src/ai/smach_dice_complete.py, line 142 at r1](https://beta.reviewable.io/reviews/palouserobosub/robosub/364#-L47UJYAGICJvH9CCfKM:-L4TWfj1EaQxKG-LjwXF:bnu7195) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L142)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Is not seeing the target you want to center on a failure for this state?
</blockquote></details>

No, the state will time out. Otherwise, if we get a single random vision callback where the dice isn't seen for a split second, the state would fail.

---

*[src/ai/smach_dice_complete.py, line 174 at r1](https://beta.reviewable.io/reviews/palouserobosub/robosub/364#-L47VZczSgscWoOe0wyr:-L4TWstH87zP-jhFP3Dw:b-n14ahw) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L174)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why do you do this after you publish the control message?
</blockquote></details>

Why would I do it before publishing the control message? It doesn't make any difference in the code.

---

*[src/ai/smach_dice_complete.py, line 218 at r1](https://beta.reviewable.io/reviews/palouserobosub/robosub/364#-L47W1nWoqLsuq9UdB6a:-L4TWzwm2YJyZaZWYzpu:b-ymssct) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L218)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Duration usually implies time. Based upon how it's used, doesn't the SubscribeState use it as time, not meters?
</blockquote></details>

Yep, that should definitely say meters.

---

*[src/ai/smach_dice_complete.py, line 242 at r2](https://beta.reviewable.io/reviews/palouserobosub/robosub/364#-L4SIbv2L4VxPVOk3Eyg:-L4TX3QQBYs1IkDa50m9:bhphy6m) ([raw file](https://github.com/palouserobosub/robosub/blob/cc58fb24089e94486a147115b350961f21c1385a/src/ai/smach_dice_complete.py#L242)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

To initialize this, just use the first detection's distance. That way you don't end up accidentally deciding it is 5000.
</blockquote></details>

You can't actually do that because the detection may be invalid (e.g. less than 0).

---

*[src/ai/util.py, line 33 at r2](https://beta.reviewable.io/reviews/palouserobosub/robosub/364#-L4SLD2NhiSOw0EhJFfx:-L4TXDE18saClcP8f2VC:b-va5um6) ([raw file](https://github.com/palouserobosub/robosub/blob/cc58fb24089e94486a147115b350961f21c1385a/src/ai/util.py#L33)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I don't believe this wraps yaw correctly. For example, 181 would be "wrapped" to 1 when it should be -179. Unless I'm missing something here.
</blockquote></details>

Yeah you're right. It needs to wrap by 360, not 180.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/palouserobosub/robosub/364)*

**Comment by ryan-summers** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/ai/smach_dice_complete.py, line 48 at r1](https://beta.reviewable.io/reviews/palouserobosub/robosub/364#-L47RFEcD59LVBMXQxdq:-L4TY44X573vZ7Gd51Zt:b-so5gjg) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L48)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

See PalouseRobosub/vision_dev#10 for the labels used. Either that or we should change the labels used which is just a refactor.
</blockquote></details>

I fixed them

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/palouserobosub/robosub/364)*

**Comment by skallaher** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ai/smach_dice_complete.py, line 1 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/364#-L47PWYyyrEZWO5_XY73:-L4TZjyLjuuQ2gJZE7Xx:b73r06q) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L1)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Because there was an initial file that was just smach_dice.py that I initially wrote that just hit the closest die and returned success. Unfortunately, I deleted the file. Do you want me to change this to smach_dice.py?
</blockquote></details>

Yes, please. To keep it consistent across the rest of the files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/364)*

**Comment by ryan-summers** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ai/smach_dice_complete.py, line 1 at r1](https://beta.reviewable.io/reviews/palouserobosub/robosub/364#-L47PWYyyrEZWO5_XY73:-L4Tdnif9A-g7O8IS5Eo:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/d56d283b98971cfe264eff0c7a67d0be01609059/src/ai/smach_dice_complete.py#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Yes, please. To keep it consistent across the rest of the files.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/palouserobosub/robosub/364)*

**Comment by skallaher** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/364)*

**Pull request merged**
