### PR TITLE
Added in stereo vision calculations

### PR DESCRIPTION
**Pull request by ryan-summers**
This node calculates the relative position of objects detected on both the left and right cameras.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/351)

### CODE REVIEW

**Comment by skallaher** [comment]
Looks pretty solid. I do have a few concerns with using something like this in the real world, though. For one, I don't think that the detections will be as accurate or as consistent as would be needed for them to be completely relied upon. By properly gathering a rectification of the cameras, we could gain a mathematical model of the disparity and not need to run the vision network on both front cameras. This would reduce calculation overhead for the portion of our system which is arguably our biggest bottleneck.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[scripts/stereo_node.py, line 13 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g7rhAX3uF43C2fSBg:-L2g7rhBnEK7za37JHFf:b6ih931) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L13)):*
> ```Python
> 
> # The distance between the two cameras (in meters).
> camera_separation = 0.40
> ```

I think I should show you the glory of TF. This value would be calculated from a tree model and would then be automatically updated if the cameras are moved around as long as the TF tree is updated which, given we use it as much as I think we should, it will be.

---

*[scripts/stereo_node.py, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g8DcL0XCpwR-A9GEw:-L2g8DcL0XCpwR-A9GEx:boz8u3l) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L16)):*
> ```Python
> 
> # The focal distance of the camera.
> camera_focal_distance = 442
> ```

What unit is this in and how did you acquire this value?

---

*[scripts/stereo_node.py, line 89 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g8kPk_6lXq0pwV00q:-L2g8kPk_6lXq0pwV00r:b-pulz1n) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L89)):*
> ```Python
>     # Synchronize messages from the left and right vision networks for stereo
>     # detection.
>     ts = message_filters.TimeSynchronizer([left_sub, right_sub], 10)
> ```

I would use an [ApproximateTime](http://wiki.ros.org/message_filters/ApproximateTime) filter as it doesn't assume that the timestamps are identical as is done by TimeSynchronizer. In practice our detections are going to be off enough to cause you some issues with TimeSynchronizer.

---

*[scripts/stereo_node.py, line 92 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g9AJwUS6fAZgadlkv:-L2g9AJwUS6fAZgadlkw:b-s093h6) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L92)):*
> ```Python
>     ts.registerCallback(callback)
> 
>     pub = rospy.Publisher('vision/relative', ObstaclePosArray, queue_size=10)
> ```

`vision/distance` might be a better topic name. `relative` isn't very descriptive for what you're doing here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-:-L2g9fA2wzsAfkPe8Nwt:b6zzk3v)*

**Comment by ryan-summers** [comment]
Yeah, I'm curious to play around with it at the pool test to see how well it functions in the real world. Even if the detections are slightly off, it may not actually affect the distance calculation that much. Even if we get something that is accurate to a foot or so will be good enough.
I'm not sure what you mean by a 'rectification' of the cameras. To my knowledge, we don't actually have any computational bottlenecks, so I don't think that's something we need to worry about yet (premature optimization can be dangerous imo).

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[scripts/stereo_node.py, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g8DcL0XCpwR-A9GEw:-L2gJPhNFQr3EPdgmrQU:b6td8d1) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L16)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

What unit is this in and how did you acquire this value?
</blockquote></details>

I'm not entirely sure. I believe it's pixels. It was taken from the camera matrix calibrations of OpenCV - an average of f_x and f_y. It needs to be set on a per-camera basis.

---

*[scripts/stereo_node.py, line 89 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g8kPk_6lXq0pwV00q:-L2gJdVrmidGaxiEJVvT:bhy9ost) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L89)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I would use an [ApproximateTime](http://wiki.ros.org/message_filters/ApproximateTime) filter as it doesn't assume that the timestamps are identical as is done by TimeSynchronizer. In practice our detections are going to be off enough to cause you some issues with TimeSynchronizer.
</blockquote></details>

Will do!

---

*[scripts/stereo_node.py, line 92 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g9AJwUS6fAZgadlkv:-L2gJeVog2n2g4vH57Ex:b81tf8w) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L92)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

`vision/distance` might be a better topic name. `relative` isn't very descriptive for what you're doing here.
</blockquote></details>

It's named ```vision/relative``` because this node calculates objects relative position to the front of the submarine, not the distance of the objects. It actually calculates new X and Y coordinates as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-:-L2gJprv0K-MQ_7_MoU6:bphjevb)*

**Comment by skallaher** [comment]
I guess what I meant was that using the typical method for stereo rectification, which will output a series of useful matrices, will require fewer images to be piped through the neural net. This means that the AI can be twice as responsive. I'm not certain at the moment if it is a huge issue, but something that I would like to keep an eye on.

---

Reviewed 1 of 4 files at r2.
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[scripts/stereo_node.py, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g8DcL0XCpwR-A9GEw:-L2gk9vEJJHUYSNdkB9g:bm3sybt) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L16)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I'm not entirely sure. I believe it's pixels. It was taken from the camera matrix calibrations of OpenCV - an average of f_x and f_y. It needs to be set on a per-camera basis.
</blockquote></details>

My best guess would be either mm or nm. It should be the focal length, from what you've said the average of the x and y focal lengths, of the camera.

---

*[scripts/stereo_node.py, line 92 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g9AJwUS6fAZgadlkv:-L2gkPp1gjI_56RaN6Mc:b6hvl3s) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L92)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

It's named ```vision/relative``` because this node calculates objects relative position to the front of the submarine, not the distance of the objects. It actually calculates new X and Y coordinates as well.
</blockquote></details>

I think what would make more sense is to use the TF tree here. Is there a good time for me to give you a talk on it?

---

*[src/ai/basic_states.py, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2gk_h2yjhCgRcZiU_p:-L2gk_h2yjhCgRcZiU_q:b-vzz2d) ([raw file](https://github.com/palouserobosub/robosub/blob/fe2cfe7a0b1df64a30018d9be2a421edbb9abfe1/src/ai/basic_states.py#L1)):*
> ```Python
> """
> ```

Why are this file and the below files in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-:-L2gjCOrFKnBZ-ZtxXvc:bgkynhf)*

**Comment by Sindorman** [comment]
This must be a thing, it will allow crap ton of AI changes, for one to have dynamic speed calculation based on distance.

**Comment by ryan-summers** [comment]
Agreed, Sean, but we have seen so far that the traditional method of stereo vision is a lot more complex than we have given it credit for. The idea it uses is block matching to find two similar pixels in the images. However, the idea here is that we can avoid the complexity of traditional stereo because we already _know_ two pixels that point at the same thing.

---

Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[scripts/stereo_node.py, line 13 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g7rhAX3uF43C2fSBg:-L33uucfQRtrFt2VYt_N:b-ug6f13) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L13)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I think I should show you the glory of TF. This value would be calculated from a tree model and would then be automatically updated if the cameras are moved around as long as the TF tree is updated which, given we use it as much as I think we should, it will be.
</blockquote></details>

Alright, when will you be around to show me it?

---

*[scripts/stereo_node.py, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g8DcL0XCpwR-A9GEw:-L33uyp35CpNBx5k6HFZ:b-7ogk7a) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L16)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

My best guess would be either mm or nm. It should be the focal length, from what you've said the average of the x and y focal lengths, of the camera.
</blockquote></details>

I set this for the submarine as 0.014 (or 0.012) as the focal distance of our current lenses is 12 or 14mm respectively and it worked well. It should be displayed in meters. Our lenses on the simulator just have a really long focal distance apparently.

---

*[src/ai/basic_states.py, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2gk_h2yjhCgRcZiU_p:-L33vF2UL7DWvU21hWqj:bc5aw3e) ([raw file](https://github.com/palouserobosub/robosub/blob/fe2cfe7a0b1df64a30018d9be2a421edbb9abfe1/src/ai/basic_states.py#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why are this file and the below files in this PR?
</blockquote></details>

That's a really good question.... This should be in the AI PR. I'll yank this out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-:-L33ubVC-fT-wDajwTrw:b-8om2lf)*

**Comment by skallaher** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[scripts/stereo_node.py, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g8DcL0XCpwR-A9GEw:-L35hs7P3sUG0zSI5weE:bst9q71) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L16)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I set this for the submarine as 0.014 (or 0.012) as the focal distance of our current lenses is 12 or 14mm respectively and it worked well. It should be displayed in meters. Our lenses on the simulator just have a really long focal distance apparently.
</blockquote></details>

I can see that. Would you put a note here stating it is in meters?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351)*

**Comment by ryan-summers** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[scripts/stereo_node.py, line 16 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2g8DcL0XCpwR-A9GEw:-L36ou14NO3H655-GSRj:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/b77255986824952cefa2f6dd7c91e8a2667f366f/scripts/stereo_node.py#L16)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I can see that. Would you put a note here stating it is in meters?
</blockquote></details>

Done.

---

*[src/ai/basic_states.py, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L2gk_h2yjhCgRcZiU_p:-L36qIfPkfTA85e8GJXU:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/8aa8a0afb0b19613561ec5cff9086eb8438b9e81/src/ai/basic_states.py#L1)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

That's a really good question.... This should be in the AI PR. I'll yank this out.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351)*

**Comment by skallaher** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351)*

**Comment by skallaher** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351)*

**Comment by Sindorman** [comment]
Linter complained about one line having 86 characters. Test build also failed - but that was because it couldn't fetch some dependencies.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-:-L3Z0bjC82FmDPe3Glqx:b5enkxf)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/vision/stereo_node.py, line 8 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L3qXOxjUas_aeMoPMCg:-L3qXOxjUas_aeMoPMCh:b-781pko) ([raw file](https://github.com/palouserobosub/robosub/blob/809bac05b46e23bd60a7e49c1583700a046a8ca4/src/vision/stereo_node.py#L8)):*
> ```Python
> import rospy
> import tf
> import tf2_ros
> ```

These two are unused imports.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351)*

**Comment by ryan-summers** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/vision/stereo_node.py, line 8 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/351#-L3qXOxjUas_aeMoPMCg:-L3set24OaVzob9KGqxw:b-tlj0hw) ([raw file](https://github.com/palouserobosub/robosub/blob/809bac05b46e23bd60a7e49c1583700a046a8ca4/src/vision/stereo_node.py#L8)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

These two are unused imports.
</blockquote></details>

There was actually a lot more unused imports :P I removed them all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/351)*

**Pull request merged**
