### PR TITLE
added pneumatics status service type

### PR DESCRIPTION
**Pull request by irwineffect**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/236)

### CODE REVIEW

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
Run CI Build

**Comment by bkallaher** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/236#-:-KhPB-SpV4xEX_QSm-Pg:bnfp4nl)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[srv/pneumatic_status.srv, line 6 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/236#-KhP_R49VPVgBunOsQvL:-KhP_R4ACLhFny2gGheP:b-osz7ek) ([raw file](https://github.com/palouserobosub/robosub/blob/9d98b4576d61fbbc9e7dd32c2f73fd8c4a9ba9f8/srv/pneumatic_status.srv#L6)):*
> ```
> #various possible statuses of the pnematics
> uint8 FIRED=0
> uint8 READY=1
> ```

Perhaps a FAULT code? In case something is detected to have failed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/236)*

**Comment by irwineffect** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[srv/pneumatic_status.srv, line 6 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/236#-KhP_R49VPVgBunOsQvL:-KhZ5XrmQvUtoZk_HPUy:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/9d98b4576d61fbbc9e7dd32c2f73fd8c4a9ba9f8/srv/pneumatic_status.srv#L6)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Perhaps a FAULT code? In case something is detected to have failed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/236)*

**Comment by skallaher** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/236#-:-KhZ5zxm46EGbO6QOQzd:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/236)*

**Pull request merged**
