### PR TITLE
Fixes roll and pitch errors when yawing more than 90 degrees relative

### LINKED ISSUE #165: Control System - problem with pitch at >90 yaw error
There is a potential issue with the control system. I believe I have a fix - I need somebody to add it to the control system and test it in the simulator.

The problem is that for relative orientation goals (from current orientation, not absolute) with yaws greater than +/- 90 degrees, any pitch error is going to have positive feedback.

Test 1: 
-set yaw P = very small, I = 0, D = 0 so that yaw rotation is slow.
-set submarine to hold orientation [Roll Pitch Yaw ] = [0 0 0]
-Once there, set goal to [0 5 180]. 
--Observe results - see if submarine begins to pitch excessively.  If possible, track pitch error and see if it grows.

This should confirm the problem exists.

To fix, the pitch error needs to be multiplied by the cosine of the yaw error.

ePitch = ePitch * cosd(eYaw);

To fix, add the following code at line 392:

389>        Vector3d rotation_error = ir3D(
390>               r3D(state_vector.segment<3>(3)).transpose() *
391>               r3D(rotation_goals));
392>

    //            rotation_error.segment<1>(1) *= cosd(rotation_error.segment<1>(2));    //

393>        /*
394>        * Update the current error vector with the calculated errors.
395>        */
396>        current_error = Vector6d::Zero();
397>       current_error << translation_error, rotation_error;
398>

Test 2:
-set yaw P = very small, I = 0, D = 0 so that yaw rotation is slow.
-set submarine to hold orientation [Roll Pitch Yaw ] = [0 0 0]
-Once there, set goal to [0 30 180]. 
--Observe results - see if submarine begins to pitch up or down. If possible, observe pitch error and see if it goes towards zero.

Test 3:
-set yaw PID to normal so that rotation is normal.
-set submarine to hold orientation [Roll Pitch Yaw ] = [0 0 0]
-Once there, set goal to [0 30 180]. 
--Observe results - see if submarine begins to pitch up or down initially.  See if it properly starts going up once yaw<90. If possible, observe pitch error and see if it goes towards zero.

This should hopefully solve the problem.

There is a second problem, which is that the submarine is unlikely to acomplish exotic rotations like [180, 45, 160] very elegantly. It may even fight itself.  scaling Pitch error by cos(Yaw) should help. But there is something else that must be done.

I'm less certain about this change than the other one, so it needs good testing.  I think I can declare the problem to exist when the yaw and roll error are both greater than +/- 90.  If they are, the fix seems to be making the yaw parameter pursue the supplement angle to the goal.

if(abs(eYaw) > 90 && abs(eRoll) > 90)
{ eYaw = rollover(eYaw-180);
 eRoll = rollover(eRoll-180); }

The syntax of which I believe would be:
>
392>if( (fabs(rotation_error.segment<1>(2) >90) && (fabs(rotation_error.segment<1>(0) >90)){
393>{
>    if(rotation_error.segment<1>(2) > 0)
>    {
>        rotation_error.segment<1>(2) -= 180;
>    }else
>    {
>        rotation_error.segment<1>(2) += 180;
>    }
>    if(rotation_error.segment<1>(0) > 0)
>    {
>        rotation_error.segment<1>(0) -= 180;
>    }else
>    {
>        rotation_error.segment<1>(0) += 180;
>    }
>}
>
> rotation_error.segment<1>(1) *= cosd(rotation_error.segment<1>(2)); //first change// 
>
 or some equivalent.  A rollover function in the rotation_engine.cpp might be useful.

Test 4:
-set yaw,pitch,roll PID regular.
-set submarine to hold orientation [Roll Pitch Yaw ] = [0 0 0]
-Once there, set goal to [180 45 180]. 
--Observe results - see if submarine appropriately flips over on its back.

Test 5:
-set yaw,pitch,roll PID regular.
-set submarine to hold orientation [Roll Pitch Yaw ] = [0 0 0]
-Once there, set goal to [180 45 135]. 
--Observe results - See how submarine behaves.  Does its motion look fluid and efficient?

Test 6:
-set yaw,pitch,roll PID regular.
-set submarine to hold orientation [Roll Pitch Yaw ] = [0 0 0]
-Once there, set goal to [-135 -45 100]. 
--Observe results - See how submarine behaves.  Does its motion look fluid and efficient?

### PR DESCRIPTION
**Pull request by skallaher**
Closes #165.

Before, when yawing any angle greater than 90 degrees, the sub would become unstable. However, at around 130 degrees, the sub still becomes unstable.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/173)

### CODE REVIEW

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/173#-KbrH4nytxW4idf4b7qF:-KbrH4nzlKljKf_IAZAK:b-tefx4n) (no related file):*
This PR doesn't fix this issue, and actually makes it worse. Here are the results of yawing from 0 to 180 degrees

Dev Branch:
dev

This Branch:
sean/controlFix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/173)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/173#-KbrH4nytxW4idf4b7qF:-KbrKIwFHY7AO1SLU0aS:b32ot9w) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

This PR doesn't fix this issue, and actually makes it worse. Here are the results of yawing from 0 to 180 degrees

Dev Branch:
dev

This Branch:
sean/controlFix

</blockquote></details>

It doesn't really make 130 degrees or above better, but 90 degrees to 130 is much smoother.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/173)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/173#-KbrH4nytxW4idf4b7qF:-KbrThZx8mpRwEJgm2On:bh8ptfg) (no related file):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

It doesn't really make 130 degrees or above better, but 90 degrees to 130 is much smoother.
</blockquote></details>

A guess as to what's happening is the set of if statements is trying to move the sub to the complimentary angle and flip over pitch and roll 180 but isn't able to do so for some reason. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/173)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/173#-KbrH4nytxW4idf4b7qF:-KbrUBPLctGbh59anuvu:b-bgclqx) (no related file):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

A guess as to what's happening is the set of if statements is trying to move the sub to the complimentary angle and flip over pitch and roll 180 but isn't able to do so for some reason. 
</blockquote></details>

Sorry, supplementary angle. In other words, the opposite side.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/173)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/173#-KbrH4nytxW4idf4b7qF:-KbrTMxnknOUa_tm22ZN:b-15zhiu) (no related file):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Sorry, supplementary angle. In other words, the opposite side.
</blockquote></details>

What I'm getting at is that I don't think this change is the proper way to fix the problem if it doesn't fully solve the problem, ya know? It complexifies the control code without really making a big difference to the smoothness of control. I would vote to leave this problem unsolved until we find the proper fix, instead of having this code in that claims to fix the problem, but really doesn't. Or if you're really interested, you could keep working on this problem lol, but remember it's pretty low priority right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/173)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/173#-KbrH4nytxW4idf4b7qF:-KbrUuvy0Q3-xZMxG7I3:br24dyp) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

What I'm getting at is that I don't think this change is the proper way to fix the problem if it doesn't fully solve the problem, ya know? It complexifies the control code without really making a big difference to the smoothness of control. I would vote to leave this problem unsolved until we find the proper fix, instead of having this code in that claims to fix the problem, but really doesn't. Or if you're really interested, you could keep working on this problem lol, but remember it's pretty low priority right now.
</blockquote></details>

Seems fair. I didn't notice the serious instability with 180 degree changes. I'll close the PR and maybe see if I can find a different solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/173)*

**Comment by skallaher** [comment]
Doesn't completely solve the problem.

**Pull request closed without merging**
