### PR TITLE
Corrected baud rate on sensor

### PR DESCRIPTION
**Pull request by ryan-summers**
Turns out the errors we were having was because we were setting the baud to 115200 and not B115200. We should add checking into serial class.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/196)

### CODE REVIEW

**Comment by skallaher** [comment]
Which errors is this fixing besides incorrect baud?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/bno055_sensor.cpp, line 223 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/196#-KeGbuEFZUGm8Hl01KHR:-KeGbuEFZUGm8Hl01KHS:b-5hg1gk) ([raw file](https://github.com/palouserobosub/robosub/blob/7a33c1f802fa2dc561707ea9be3960a25640bf33/src/sensors/bno055_sensor.cpp#L223)):*
> ```cpp
>     }
>     ros::Rate r(rate);
>     ROS_INFO("Sensor is now running.");
> ```

Could you make this say BNO055 Sensor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/196#-:-KeGbmobsdh2GufT2Q6H:b-31ekob)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/196#-:-KeGe6wMPE-wJI4xED9d:bnfp4nl)*

**Comment by ryan-summers** [comment]
That's all this does. It also adds in more informative messages so you know when the sensor is working.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/196#-:-KeGiywTY0sNJoQa0reG:b-6ytkoa)*

**Comment by ryan-summers** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/bno055_sensor.cpp, line 223 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/196#-KeGbuEFZUGm8Hl01KHR:-KeGj4Y63CPLeUSVvKt-:b8fxona) ([raw file](https://github.com/palouserobosub/robosub/blob/7a33c1f802fa2dc561707ea9be3960a25640bf33/src/sensors/bno055_sensor.cpp#L223)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Could you make this say BNO055 Sensor?
</blockquote></details>

Good point for roslaunch files!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/196)*

**Comment by ryan-summers** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/bno055_sensor.cpp, line 223 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/196#-KeGbuEFZUGm8Hl01KHR:-KeGj_B2lG5jDZ102YsX:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/7a33c1f802fa2dc561707ea9be3960a25640bf33/src/sensors/bno055_sensor.cpp#L223)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Good point for roslaunch files!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/196)*

**Comment by skallaher** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/196#-:-KeGjbVLLP7w5KHjZvB4:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/196)*

**Comment by ryan-summers** [comment]
Correction: the addition of usleep ensures that the sensor does not fail a register read on reset.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/196#-:-KeGlYtqmPptVhMoTRG7:b-dd5lk4)*

**Pull request merged**
