### PR TITLE
added buoyancy compensation to the control system

### PR DESCRIPTION
**Pull request by irwineffect**
This allows us to use much smaller PID values for depth control, making it behave much nicer. Requires PalouseRobosub/robosub_simulator#32 for the control system test to pass.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/133)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/movement/control_system.cpp, line 471 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/133#-K_reXI4qZXgW5HX-V7P:-K_reXI4qZXgW5HX-V7Q:b-bku1iw) ([raw file](https://github.com/palouserobosub/robosub/blob/339c2abfff1cbf7901d5adf2794b58dc90428deb/src/movement/control_system.cpp#L471)):*
> ```cpp
>          * behave much nicer.
>          */
>         m_force[2] += buoyancy_offset;
> ```

The units for this value are Newtons, correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/133)*

**Comment by skallaher** [comment]
:lgtm: and seems to be pretty smooth in the simulator!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/133#-:-K_rfNOO2Z1pSAgos4Ij:bbxesh4)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/movement/control_system.cpp, line 471 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/133#-K_reXI4qZXgW5HX-V7P:-K_vUuwC25RiiGrnDUUN:b-7xt51e) ([raw file](https://github.com/palouserobosub/robosub/blob/339c2abfff1cbf7901d5adf2794b58dc90428deb/src/movement/control_system.cpp#L471)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

The units for this value are Newtons, correct?
</blockquote></details>

Yep!`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/133)*

**Comment by bkallaher** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/133)*

**Review by bkallaher — APPROVED** [review]

**Pull request merged**
