### PR TITLE
Roulette AI Refinement

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR refines the roulette AI to use synchronous subscribers to mask in only the roulette detection. Additionally, it adds a visualization node that allows real-time testing of the RouletteWheel color processing.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/388)

### CODE REVIEW

**Comment by Sindorman** [comment]
Synchronous state are very useful. :lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/388#-:-L51iBnU_-hyh-ss4Cki:bboqkmx)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/ai/smach_roulette.py, line 141 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/388#-L55gRiPWDJBaa4hj06D:-L55gRiPWDJBaa4hj06E:b-t6ehbz) ([raw file](https://github.com/palouserobosub/robosub/blob/dec98e8005586f5df784d5cb8218a98cc501ec65/src/ai/smach_roulette.py#L141)):*
> ```Python
>             if self.tries >= self.retry_count:
>                 self.exit('fail')
>             tries = self.tries + 1
> ```

This is a bug. Should be self.tries = self.tries + 1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/388)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/ai/smach_roulette.py, line 269 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/388#-L55hvW8vXJ52o0WZHYV:-L55hvW8vXJ52o0WZHYW:b8by6md) ([raw file](https://github.com/palouserobosub/robosub/blob/dec98e8005586f5df784d5cb8218a98cc501ec65/src/ai/smach_roulette.py#L269)):*
> ```Python
> 
>         rospy.loginfo('{}, l:{} h:{}'.format(origin, length, height))
>         rospy.loginfo('{} {}'.format(upper_left, lower_right))
> ```

These loginfo's don't need to be in the code.

---

*[src/ai/smach_roulette.py, line 279 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/388#-L55i0_OAfRS4wW9Int9:-L55i0_OAfRS4wW9IntA:b-kqhc9u) ([raw file](https://github.com/palouserobosub/robosub/blob/dec98e8005586f5df784d5cb8218a98cc501ec65/src/ai/smach_roulette.py#L279)):*
> ```Python
> 
>         if len(wheel.slices) == 0:
>             self.exit('fail')
> ```

There should be a return here.

---

*[src/ai/smach_roulette.py, line 348 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/388#-L55i5cJczF9phFYfIZF:-L55i5cJczF9phFYfIZG:b-7l3xdk) ([raw file](https://github.com/palouserobosub/robosub/blob/dec98e8005586f5df784d5cb8218a98cc501ec65/src/ai/smach_roulette.py#L348)):*
> ```Python
>         with self:
>             # First, dive to a certain depth and search for the pinger.
>             smach.StateMachine.add('DIVE_PINGER', basic_states.GoToDepth(0.75),
> ```

After initial discovery, we will want this to be approximately 1 meter at least.

---

*[src/ai/SubscribeState.py, line 98 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/388#-L55iVaZUNZkl-MlUpu7:-L55iVaZUNZkl-MlUpu8:b-fu8i5x) ([raw file](https://github.com/palouserobosub/robosub/blob/dec98e8005586f5df784d5cb8218a98cc501ec65/src/ai/SubscribeState.py#L98)):*
> ```Python
> 
>     def execute(self, user_data):
>         rospy.logdebug('SubscribeState base class "execute" running')
> ```

This should say SynchronousSubscribeState

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/388)*

**Comment by Sindorman** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/388#-:-L5W33ATHxOc8xdyzf15:bg7igkv)*

**Comment by Sindorman** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/388)*

**Pull request merged**
