### PR TITLE
Mike/gate task

### PR DESCRIPTION
**Pull request by Sindorman**
Fully implemented, and tested Gate_task State Machine. Uses parameters in ros/scr/robosub/param/ai.yaml for tweaking settings.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/304)

### CODE REVIEW

**Comment by daymare** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/ai/smach_gate.py, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKcXrybB5DQQlD1dzg:-KvKcXrybB5DQQlD1dzh:bd73lml) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L40)):*
> ```Python
>         return 'success'
> 
> # Lost state for when AI feels lost
> ```

Please be more descriptive

---

*[src/ai/smach_gate.py, line 76 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKcgodKKIwLnM33rRj:-KvKcgodKKIwLnM33rRk:b-95slqu) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L76)):*
> ```Python
>             self.exit('2 posts')
> ```

Add comment for what this state does

---

*[src/ai/smach_gate.py, line 88 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKcm3X5vh8PC_uki72:-KvKcm3X5vh8PC_uki73:b5cyrh7) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L88)):*
> ```Python
>             search_direction = 'right'
>         return 'success'
> ```

Add comment

---

*[src/ai/smach_gate.py, line 95 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKeLww5NFcARvHLkqO:-KvKe2udCAhegJn-UCWp:bf355v6) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L95)):*
> ```Python
>         with self:
>             smach.StateMachine.add("LOST", lost('start_gate'),
>                 transitions={'1 post': 'SEARCH', 'none':'LOST',
> ```

Change transition of 2 posts : SEARCH

---

*[src/ai/smach_gate.py, line 104 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKco7YduBb80jhufJ_:-KvKco7YduBb80jhufJa:b48mlr9) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L104)):*
> ```Python
>                 '1 post': 'SEARCH'})
> 
> #  State for searching gate posts
> ```

Describe how this  state is for finding the second post after we have found the first one

---

*[src/ai/smach_gate.py, line 217 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKeSsX4fr7LzOZ3_ot:-KvKeSsX4fr7LzOZ3_ou:b-gpb9jj) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L217)):*
> ```Python
> 
> 
> # TODO High state machine of gate task
> ```

# High level state machine of gate task

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-:-KvKfBTBAVgRSHDD4c7j:bnfp4nl)*

**Comment by skallaher** [comment]
Check the output of the linter.

---

Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[param/ai.yaml, line 30 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKfp-60K9Juv0SMQCj:-KvKfp-60K9Juv0SMQCk:b-rvzily) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/param/ai.yaml#L30)):*
> ```YAML
>         errorGoal: 0.01
>         distanceGoal: 0.01
>         forward_speed: 0.4
> ```

BTW, we should add comments to this param file

---

*[src/ai/smach_gate.py, line 17 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKdORdTgW0O6GCbdA-:-KvKdORdTgW0O6GCbdA0:bn6lzue) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L17)):*
> ```Python
>     def __init__(self, vision_label, poll_rate=10):
>         SubscribeState.__init__(self, "vision", DetectionArray, self.callback,
>             outcomes=['success'])
> ```

When indenting on a new line, please line up the new line with the parenthesis in this case. This helps preserve an idea of the scope of the code. i.e.
```
SubscribeState.__init__(self, "vision", DetectionArray, self.callback,
                        outcomes=['success'])
```

---

*[src/ai/smach_gate.py, line 33 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKf3SZwlhqWyLRnN-R:-KvKf3S_k9q6n-FP6WpK:bv4l8xb) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L33)):*
> ```Python
>         normalize(vision_result)
>         #move while forward until we see a gate post
>         if vision_result == 0:
> ```

`vision_result` is a list, why are you comparing it to 0? If you're checking length, use `len(vision_result)`.

---

*[src/ai/smach_gate.py, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKcXrybB5DQQlD1dzg:-KvKfa8fP38QTxqLcCtB:bb49lm8) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L40)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

Please be more descriptive
</blockquote></details>

I agree. What does it mean to be lost?

---

*[src/ai/smach_gate.py, line 67 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKgGwNfGSt7yaKd0uQ:-KvKgGwNfGSt7yaKd0uR:b-oeyps1) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L67)):*
> ```Python
>         if len(vision_result) == 0:
>             print(search_direction)
>             print("yaw: {}".format(currentYaw))
> ```

These should be `rospy.loginfo` or `rospy.logdebug` calls

---

*[src/ai/smach_gate.py, line 89 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKgWc1S6E85AEN0koS:-KvKgWc1S6E85AEN0koT:b-dz7fjd) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L89)):*
> ```Python
>         return 'success'
> 
> class Search(smach.StateMachine):
> ```

Search what? This should specify it is for searching for the gate unless it is made more generic.

---

*[src/ai/smach_gate.py, line 95 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKeLww5NFcARvHLkqO:-KvKgl4uWuA8R5zmfBpD:b-152sfk) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L95)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

Change transition of 2 posts : SEARCH
</blockquote></details>

This may not be the intended behavior. If the sub magically finds both posts, we see the gate

---

*[src/ai/smach_gate.py, line 105 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKh1TLckz2PkilZQxO:-KvKh1TMvzsythKF-lnG:b-e5c2lb) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L105)):*
> ```Python
> 
> #  State for searching gate posts
> class search(SubscribeState):
> ```

You have two classes with the same name, but different meanings. This will be confusing.

---

*[src/ai/smach_gate.py, line 114 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKhYUXBmkg3ABe5iT1:-KvKhYUXBmkg3ABe5iT2:bqfs16e) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L114)):*
> ```Python
> 
>     def callback(self, detectionArray):
>         global search_direction
> ```

FYI, this will need to be fixed to not be a global variable. They are scary.

---

*[src/ai/smach_gate.py, line 122 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKhKd2Gs6Siat-hPUA:-KvKhKd2Gs6Siat-hPUB:buqkm3f) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L122)):*
> ```Python
>         vision_result = getNMostProbable(detections, 2, thresh=0.5)
> 
>         print("results: {}".format(len(vision_result)))
> ```

Please remove any prints. If they are useful debugging tools, make them `rospy.logdebug` if they are important outputs, make them `rospy.loginfo`, if they are neither, remove them entirely.

---

*[src/ai/smach_gate.py, line 231 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKiCaL-_LvZqGyGCzT:-KvKiCaL-_LvZqGyGCzU:bfr6q2m) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L231)):*
> ```Python
>                 transitions={'centered': 'FORWARD','lost': 'SEARCH_MACHINE'})
> 
>             smach.StateMachine.add('SEARCH_MACHINE', Search(),
> ```

Rename this to something more descriptive than `SEARCH_MACHINE`. What are you searching for/what will it do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-:-KvKdz6oF1_TB4Ov3Jzf:bn7yvsp)*

**Comment by Sindorman** [comment]
Review status: 1 of 3 files reviewed at latest revision, 15 unresolved discussions.

---

*[src/ai/smach_gate.py, line 114 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKhYUXBmkg3ABe5iT1:-KvKnb7VJn1S1xK1Gg3i:btas7r6) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L114)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

FYI, this will need to be fixed to not be a global variable. They are scary.
</blockquote></details>

I spent a lot of time trying to make it work without using global variable. It might be possible, but would require some tricks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304)*

**Comment by Sindorman** [comment]
Review status: 1 of 3 files reviewed at latest revision, 15 unresolved discussions.

---

*[param/ai.yaml, line 30 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKfp-60K9Juv0SMQCj:-KvKnuSDsF28Jufg5AXJ:b-fe488e) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/param/ai.yaml#L30)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

BTW, we should add comments to this param file
</blockquote></details>

We should, but half of them were made by James.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304)*

**Comment by Sindorman** [comment]
Review status: 1 of 3 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[src/ai/smach_gate.py, line 17 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKdORdTgW0O6GCbdA-:-KvKvqCx1q9haNVGUshK:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L17)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

When indenting on a new line, please line up the new line with the parenthesis in this case. This helps preserve an idea of the scope of the code. i.e.
```
SubscribeState.__init__(self, "vision", DetectionArray, self.callback,
                        outcomes=['success'])
```
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 40 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKcXrybB5DQQlD1dzg:-KvKvsFhOxXxAkrVpgpm:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L40)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I agree. What does it mean to be lost?
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 67 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKgGwNfGSt7yaKd0uQ:-KvKvsuRHUoksKfv6K-l:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L67)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

These should be `rospy.loginfo` or `rospy.logdebug` calls
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 76 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKcgodKKIwLnM33rRj:-KvKvtnBfa5b8ALqXEk6:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L76)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

Add comment for what this state does
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 88 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKcm3X5vh8PC_uki72:-KvKvtSgXQVZHHOAhmp5:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L88)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

Add comment
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 89 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKgWc1S6E85AEN0koS:-KvKvv3JQyeDEmUkoxCZ:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L89)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Search what? This should specify it is for searching for the gate unless it is made more generic.
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 95 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKeLww5NFcARvHLkqO:-KvKvuj4ELXu6rmxDSwC:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L95)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This may not be the intended behavior. If the sub magically finds both posts, we see the gate
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 104 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKco7YduBb80jhufJ_:-KvKvvdJZggDi6aDt0om:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L104)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

Describe how this  state is for finding the second post after we have found the first one
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 105 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKh1TLckz2PkilZQxO:-KvKvwQK4C9S2USsjcQk:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L105)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

You have two classes with the same name, but different meanings. This will be confusing.
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 122 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKhKd2Gs6Siat-hPUA:-KvKvx0oQyWXrN10Ys7e:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L122)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Please remove any prints. If they are useful debugging tools, make them `rospy.logdebug` if they are important outputs, make them `rospy.loginfo`, if they are neither, remove them entirely.
</blockquote></details>

Done.

---

*[src/ai/smach_gate.py, line 217 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKeSsX4fr7LzOZ3_ot:-KvKvyltB9BhQLPM-TMA:bb7f2mf) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L217)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

# High level state machine of gate task
</blockquote></details>

done

---

*[src/ai/smach_gate.py, line 231 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKiCaL-_LvZqGyGCzT:-KvKvyWnY4D0OkDM2rEO:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L231)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Rename this to something more descriptive than `SEARCH_MACHINE`. What are you searching for/what will it do?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[param/ai.yaml, line 30 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKfp-60K9Juv0SMQCj:-KvKxtsksr7u-qDIaLok:bfq69au) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/param/ai.yaml#L30)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

We should, but half of them were made by James.
</blockquote></details>

That doesn't mean that you shouldn't comment yours

---

*[src/ai/smach_gate.py, line 17 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKdORdTgW0O6GCbdA-:-KvKy-VFo3Cg0sTid6nd:b-401jyx) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L17)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not according to the diff here.

---

*[src/ai/smach_gate.py, line 89 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKgWc1S6E85AEN0koS:-KvKyEfnNk67Me1KLsCe:b-i2a) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L89)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant to change the name of the class

---

*[src/ai/smach_gate.py, line 105 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKh1TLckz2PkilZQxO:-KvKySN39lLPKYVGdheo:b-suv666) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L105)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is not done. You should not have to rely upon comments. Class names should give an intuitive sense of what they do.

---

*[src/ai/smach_gate.py, line 114 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKhYUXBmkg3ABe5iT1:-KvKy_yJrqgoB2wqO2-4:bwz187s) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L114)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

I spent a lot of time trying to make it work without using global variable. It might be possible, but would require some tricks.
</blockquote></details>

When using FYI or BTW in Reviewable, it does not prevent the review from being completed. This is just meant as a note.

---

*[src/ai/smach_gate.py, line 231 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKiCaL-_LvZqGyGCzT:-KvKyma-WbjYttp7MXzr:b9vgwox) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L231)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Mike, you need to complete and push changes before claiming they are done. Half of the things in this review that you said you fixed are still wrong.

---

*[src/ai/smach_nav_channel.py, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKyyiY9h4gEcDR27V_:-KvKyyiY9h4gEcDR27Va:b-f0n2uj) ([raw file](https://github.com/palouserobosub/robosub/blob/8da392c069bb8ff309b52b3a4abf262b1af0cfc0/src/ai/smach_nav_channel.py#L1)):*
> ```Python
> #!/usr/bin/python
> ```

Rather than copying and pasting, make the states reusable and just pass in a different label. This file should be much, much shorter than it is. Please also rename things to have meaningful variable names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304)*

**Comment by Sindorman** [comment]
Review status: 2 of 3 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[src/ai/smach_gate.py, line 89 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKgWc1S6E85AEN0koS:-KvLEL55eBU8Alujxub1:bhiz7bc) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L89)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I meant to change the name of the class
</blockquote></details>

Changed the name to Search_for_gate

---

*[src/ai/smach_gate.py, line 105 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKh1TLckz2PkilZQxO:-KvLESwQMgjAIzfVJyb0:b-gygyqz) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L105)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This is not done. You should not have to rely upon comments. Class names should give an intuitive sense of what they do.
</blockquote></details>

Changed State machine class name, so no confusion comes. One is Search_for_gates other is search.

---

*[src/ai/smach_gate.py, line 231 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKiCaL-_LvZqGyGCzT:-KvLEf-2rpHVciFe8Ziq:b-e6spip) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L231)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Mike, you need to complete and push changes before claiming they are done. Half of the things in this review that you said you fixed are still wrong.
</blockquote></details>

I am sorry, but I was working on it so much, I am braindead. Changes made, please review them.

---

*[src/ai/smach_nav_channel.py, line 1 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKyyiY9h4gEcDR27V_:-KvLEnm0hzQVZrYwLIIl:b5b88zu) ([raw file](https://github.com/palouserobosub/robosub/blob/8da392c069bb8ff309b52b3a4abf262b1af0cfc0/src/ai/smach_nav_channel.py#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Rather than copying and pasting, make the states reusable and just pass in a different label. This file should be much, much shorter than it is. Please also rename things to have meaningful variable names.
</blockquote></details>

They are already reusable, I can just build new state machine within navigation channel. Which variables do not make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/ai/smach_gate.py, line 231 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvKiCaL-_LvZqGyGCzT:-KvLH3VVpn5oR00LB2RM:b8h5ypa) ([raw file](https://github.com/palouserobosub/robosub/blob/347d2e4fe55c90428545eaaa12b5e3376ba06aa1/src/ai/smach_gate.py#L231)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

I am sorry, but I was working on it so much, I am braindead. Changes made, please review them.
</blockquote></details>

This is still not done.

---

*[src/ai/smach_gate.py, line 250 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-KvLH5wUag8r9DN7ESna:-KvLH5wUag8r9DN7ESnb:bowr2mz) ([raw file](https://github.com/palouserobosub/robosub/blob/8da392c069bb8ff309b52b3a4abf262b1af0cfc0/src/ai/smach_gate.py#L250)):*
> ```Python
> 
> if __name__ == '__main__':
>     rospy.init_node('gate task')
> ```

Node names should not have spaces in them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304)*

**Comment by skallaher** [comment]
Last thing is to satisfy the linter.

---

Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-:-KvLMrqHwiRb4rPNpZLm:b-7opnlg)*

**Comment by Sindorman** [comment]
linter did not crash on my file.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-:-KvLMx10a1IarZcVgEBi:b-6q3ar7)*

**Comment by skallaher** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304#-:-KvLPU66wFn3ZA5stECf:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/304)*

**Pull request merged**
