### PR TITLE
Adds in Casino Gate AI

### PR DESCRIPTION
**Pull request by ryan-summers**
This AI allows the submarine to target either color or side of the Casino gate. It searches right until the gate is fully in view and then gets close enough for a blind ram.

This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/363)

### CODE REVIEW

**Comment by Sindorman** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ai/basic_states.py, line 76 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/363#-L42tLXoYWNfQlaDBEn7:-L42tLXoYWNfQlaDBEn8:b-m4vvy1) ([raw file](https://github.com/palouserobosub/robosub/blob/05aef9405b76e3795b97f1e3fe9b1d4f0036f352/src/ai/basic_states.py#L76)):*
> ```Python
> 
> 
> class BlindRam(smach.State):
> ```

There is a state in `blind_movement.py` called `move_forward` that has exact same functionality.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/363)*

**Comment by ryan-summers** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ai/basic_states.py, line 76 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/363#-L42tLXoYWNfQlaDBEn7:-L43bArZOtINjJBFvrRp:biycjft) ([raw file](https://github.com/palouserobosub/robosub/blob/05aef9405b76e3795b97f1e3fe9b1d4f0036f352/src/ai/basic_states.py#L76)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

There is a state in `blind_movement.py` called `move_forward` that has exact same functionality.
</blockquote></details>

After some discussion with james, we have thought that it makes more sense to get rid of blind_movement.py in favor of basic_states.py

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/363)*

**Comment by skallaher** [comment]
Reviewed 7 of 8 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/ai/smach_casino_gate.py, line 59 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/363#-L4SMSGfHIwfDr7cDCtU:-L4SMSGfHIwfDr7cDCtV:by1m49w) ([raw file](https://github.com/palouserobosub/robosub/blob/af3507b88cfabc76b5514124504ade209d1d01f3/src/ai/smach_casino_gate.py#L59)):*
> ```Python
>         c.forwardError(0)
>         c.strafeLeftError(0)
>         c.yawLeftError(0)
> ```

What do you think about a `halt` call for the `control_wrapper` that does this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/363)*

**Comment by ryan-summers** [comment]
This is going to need some heavy rework before the PR is ready. Closing for now.

**Pull request closed without merging**
