### PR TITLE
Fixed the strings used in the control status message

### PR DESCRIPTION
**Pull request by bkallaher**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/195)

### CODE REVIEW

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/195#-:-KeC2sqZbKfXVvlApBQi:bnfp4nl)*

**Comment by skallaher** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/195#-:-KeGQvGzLBGRzO_9MIfb:bnfp4nl)*

**Comment by dcrossman** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/195#-:-KeLFt_7vZGyFR9G49d1:bnfp4nl)*

**Comment by irwineffect** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/195)*

**Comment by irwineffect** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/195)*

**Pull request merged**
