### PR TITLE
Adds in Roulette AI Task

### PR DESCRIPTION
**Pull request by ryan-summers**
Before this is merged in, the casino prop update should be merged in and downward camera calibration data should be taken.

This task is capable of targeting any three of the roulette wheel color slices.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/348)

### CODE REVIEW

**Comment by Sindorman** [comment]
BTW. I like this AI, it uses SMACH. What if we mix `basic_states.py` and `RouletteWheel.py` into one file, what do you think?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ai/control_wrapper.py, line 134 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L1uCpzve92rgq6bCavP:-L1uCpzve92rgq6bCavQ:b-9v00a7) ([raw file](https://github.com/palouserobosub/robosub/blob/fdfa01dd2e8e82032912a8fb2becb2ec29408262/src/ai/control_wrapper.py#L134)):*
> ```Python
>     def setDive(self, state, value):
>         self._control_msg.dive_state = state
>         self._control_msg.dive = -1 * abs(value)
> ```

Hmm. I think this fixes it? But I never seen problem yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-:-L1uD6KyO_ZLpZVjzyWA:bao3s64)*

**Comment by ryan-summers** [comment]
basic_states.py is a file that contains some fundamental SMACH states, but RouletteWheel.py describes the roulette wheel image. They're different things, and are thus put into different files.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ai/control_wrapper.py, line 134 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L1uCpzve92rgq6bCavP:-L1uXrd1jW1DD-tO-V2d:b-vfa8n6) ([raw file](https://github.com/palouserobosub/robosub/blob/fdfa01dd2e8e82032912a8fb2becb2ec29408262/src/ai/control_wrapper.py#L134)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Hmm. I think this fixes it? But I never seen problem yet.
</blockquote></details>

This was actually intended to allow you to be arbitrary in depth measurements, but this is actually a bug because you can't do relative positive signals. Let me revert it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-:-L1uXe-ofa06QPciwfEd:bd8bs0t)*

**Comment by Sindorman** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-:-L26MnQDF5kfChPG1hMD:bnfp4nl)*

**Comment by Sindorman** [comment]
FYI: you can always replace print statements into ros debug messages, if you would need them in future. Thought debug mode in ROS prints too much information, could be overload of human.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-:-L26MtVbdwmm29a5Mk_G:bqioyyd)*

**Comment by skallaher** [comment]
Reviewed 1 of 4 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[src/ai/basic_states.py, line 181 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HYinq2f6-LfQRCWMs:-L2HYinq2f6-LfQRCWMt:b-unzxnu) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/basic_states.py#L181)):*
> ```Python
>         """Initializes the state."""
>         smach.State.__init__(self,
>                              outcomes=outcomes,
> ```

Why have you decided here to have this list passed in here rather than defined in the constructor as in the above states?

---

*[src/ai/basic_states.py, line 195 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HYzeUw1ifoX5_cQ4R:-L2HYzeUw1ifoX5_cQ4S:b-qgtote) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/basic_states.py#L195)):*
> ```Python
>         rospy.loginfo('Firing torpedo.')
>         service()
>         return self.outcomes[0]
> ```

Looking ahead, this state (and the one below) could return failure if we have fired both torpedoes/markers.

---

*[src/ai/RouletteWheel.py, line 24 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HZQnUJtSICjHnRrwU:-L2HZQnUJtSICjHnRrwV:b1tabng) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/RouletteWheel.py#L24)):*
> ```Python
> 
>         Args:
>             origin: The origin tuple point of the slice in (x, y) form.
> ```

What is the origin relative to?

---

*[src/ai/smach_roulette.py, line 30 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HZgaX73J4_YP8kxSN:-L2HZgaX73J4_YP8kxSO:bd9onay) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/smach_roulette.py#L30)):*
> ```Python
> 
> 
> class MoveToPinger(SubscribeState):
> ```

This state could also be used for other tasks such as the square. Probably fits better in a utility file. I think we should also discuss possible uses of TF and the localization engine here for the future.

---

*[src/ai/smach_roulette.py, line 46 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2H_J9S4mACnwAZ5_5U:-L2H_J9S4mACnwAZ5_5V:b-s0r6k3) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/smach_roulette.py#L46)):*
> ```Python
>             forward_speed: The speed at which to move forward.
>             successful_angle: The downward angle that the pinger must lie in for
>                 success.
> ```

I assume this is degrees, just for clarity and posterity, please specify here.

---

*[src/ai/smach_roulette.py, line 72 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HfaR4eZ3-1ukev8CI:-L2HfaR4eZ3-1ukev8CJ:b9ft0ji) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/smach_roulette.py#L72)):*
> ```Python
> 
>         # Calculate the downward angle to the pinger.
>         theta_z = 180 / np.pi * np.arctan2(np.sqrt(bearing.x**2 + bearing.y**2),
> ```

Here's an example of using tf2 to convert a quaternion to euler angles:
https://answers.ros.org/question/239689/quaternion-to-euler-angle-convention-in-tf/

---

*[src/ai/smach_roulette.py, line 93 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HjgEJfAGcTMq8BQQ9:-L2HjgEJfAGcTMq8BQQA:bf2pma9) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/smach_roulette.py#L93)):*
> ```Python
> 
> 
> class CenterDownward(SubscribeState):
> ```

This name in combination with "CenterAbove" can be confusing.

---

*[src/ai/smach_roulette.py, line 194 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HlHENtuYGT19P19p5:-L2HlHENtuYGT19P19p6:b-ifps14) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/smach_roulette.py#L194)):*
> ```Python
> 
> 
> class TargetColor(SubscribeState):
> ```

How does this handle a moving roulette wheel? My first instinct is to use it concurrently.

---

*[src/ai/smach_roulette.py, line 220 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2Hlp-RAlIpqsUp4tUr:-L2Hlp-RAlIpqsUp4tUs:b-ii0beb) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/smach_roulette.py#L220)):*
> ```Python
>                                 timeout=max_duration)
>         self.color = color
>         self.speed = 1.3
> ```

Any reason this is 1.3? We still haven't found a good solution for centralizing these kinds of parameters in a meaningful and non-messy way.

---

*[src/ai/smach_roulette.py, line 302 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2JYp5TsGRsQ-y2G2_i:-L2JYp5TsGRsQ-y2G2_j:b-ffxveg) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/smach_roulette.py#L302)):*
> ```Python
>                     transitions={'success': 'FIND_PINGER',
>                                  'fail': 'fail',
>                                  'timeout': 'fail'})
> ```

`timeout` is not a registered outcome of GoToDepth, and I don't think for any states.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348)*

**Comment by Sindorman** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[src/ai/smach_roulette.py, line 147 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L324IayZAY-tZlJyKXJ:-L324IayZAY-tZlJyKXK:bqutic6) ([raw file](https://github.com/palouserobosub/robosub/blob/0f785a81ee998e834c54342fda2e7242f55405a9/src/ai/smach_roulette.py#L147)):*
> ```Python
>         if not x_good:
>             c.strafeLeftError(-1 * x_error * self.speed)
>             rospy.loginfo('Centering X by strafing left {}'.format(-1 *
> ```

Please change this, and ***every*** other from `loginfo` to `logdebug`. So it would be `rospy.logdebug`, otherwise it is too much of information, every AI has these statements as debug mode only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/ai/basic_states.py, line 181 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HYinq2f6-LfQRCWMs:-L42DV6j-ObJNmdeAvBs:ba7qqij) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/basic_states.py#L181)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why have you decided here to have this list passed in here rather than defined in the constructor as in the above states?
</blockquote></details>

I'm not sure what you mean. The FireTorpedo class is a smach.State, whereas all of the above classes are SubscribeState derivatives. They're different objects so they have different constructors.

---

*[src/ai/basic_states.py, line 195 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HYzeUw1ifoX5_cQ4R:-L42DciZm8UevdhQZPMn:bw9tnzj) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/basic_states.py#L195)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Looking ahead, this state (and the one below) could return failure if we have fired both torpedoes/markers.
</blockquote></details>

They currently cannot because the service call is an empty type that doesn't return success or fail. It's not possible yet to know the success status of the service call.

---

*[src/ai/RouletteWheel.py, line 24 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HZQnUJtSICjHnRrwU:-L42ENgHsDpLlvHbgcyx:b-dxrjog) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/RouletteWheel.py#L24)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

What is the origin relative to?
</blockquote></details>

The origin is in OpenCV pixel coordinates. I added a comment.

---

*[src/ai/smach_roulette.py, line 30 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HZgaX73J4_YP8kxSN:-L42EvhcDGw5QbNfrLQq:bjnxm7p) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L30)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This state could also be used for other tasks such as the square. Probably fits better in a utility file. I think we should also discuss possible uses of TF and the localization engine here for the future.
</blockquote></details>

As of now, the pinger bearing is published to hydrophones/bearing - Therefore, we are only publishing the bearing to a singular pinger frequency and this can only be used with a singular AI. We need to update the pinger_bearing node to publish bearings for all frequencies.

---

*[src/ai/smach_roulette.py, line 46 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2H_J9S4mACnwAZ5_5U:-L42FXukTGd2aW5F6hMR:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L46)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I assume this is degrees, just for clarity and posterity, please specify here.
</blockquote></details>

Done.

---

*[src/ai/smach_roulette.py, line 72 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HfaR4eZ3-1ukev8CI:-L42FdV0kTaez4qo5vqW:bj4xkhv) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L72)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Here's an example of using tf2 to convert a quaternion to euler angles:
https://answers.ros.org/question/239689/quaternion-to-euler-angle-convention-in-tf/
</blockquote></details>

I don't see how that is really relevant here as I'm not converting a quaternion to an euler angle...? I'm projecting a unit vector onto the vertical plane formed by the X/Y components.

---

*[src/ai/smach_roulette.py, line 93 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HjgEJfAGcTMq8BQQ9:-L42G0RpRZmrnFX2uDo6:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L93)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This name in combination with "CenterAbove" can be confusing.
</blockquote></details>

Done.

---

*[src/ai/smach_roulette.py, line 147 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L324IayZAY-tZlJyKXJ:-L42GCsm4NNedkUPYZqi:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L147)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Please change this, and *every* other from `loginfo` to `logdebug`. So it would be `rospy.logdebug`, otherwise it is too much of information, every AI has these statements for debug mode.
</blockquote></details>

Done.

---

*[src/ai/smach_roulette.py, line 194 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HlHENtuYGT19P19p5:-L42GHGxMLspAL8612qT:b4loipa) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L194)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

How does this handle a moving roulette wheel? My first instinct is to use it concurrently.
</blockquote></details>

It uses planar movements to center on the color of choice. Hence, if the color of choice is moving, it will follow it. I don't know what you mean about concurrency.

---

*[src/ai/smach_roulette.py, line 220 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2Hlp-RAlIpqsUp4tUr:-L42GZpYHLuD1la4_sex:b2n3xx7) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L220)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Any reason this is 1.3? We still haven't found a good solution for centralizing these kinds of parameters in a meaningful and non-messy way.
</blockquote></details>

This is one of the few parameters that probably requires tuning. It needs to be slightly above 1 so that it moves fast enough to track the roulette wheel, but it needs to be low enough so that it moves relatively slowly and doesn't give the golf ball any X/Y velocity.

---

*[src/ai/smach_roulette.py, line 302 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2JYp5TsGRsQ-y2G2_i:-L42GlYzNqSkn43TNRdc:b-171bz3) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L302)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

`timeout` is not a registered outcome of GoToDepth, and I don't think for any states.
</blockquote></details>

Timeout is a registered outcome of all SubscribeState derivatives that pass in a timeout parameter. Just an FYI: SMACH will automatically verify that transitions and outcomes of states are valid during runtime, so if timeout was not a registered outcome, the AI wouldn't work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348)*

**Comment by skallaher** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ai/basic_states.py, line 181 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HYinq2f6-LfQRCWMs:-L43Z7zz0W78xfBMjzZc:b3n3uot) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/basic_states.py#L181)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I'm not sure what you mean. The FireTorpedo class is a smach.State, whereas all of the above classes are SubscribeState derivatives. They're different objects so they have different constructors.
</blockquote></details>

My note is more of that you are exposing the outcomes list in the FireTorpedo constructor here, whereas the others do not expose the outcomes list to the outside.

---

*[src/ai/smach_roulette.py, line 194 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HlHENtuYGT19P19p5:-L43_62FUqxepQcZrw0v:b-wk33j2) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L194)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

It uses planar movements to center on the color of choice. Hence, if the color of choice is moving, it will follow it. I don't know what you mean about concurrency.
</blockquote></details>

Given how long it has been since I first reviewed this, I don't either. Is there a risk of missing the target by dropping the marker while rotating to follow the slice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ai/basic_states.py, line 181 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HYinq2f6-LfQRCWMs:-L44398gLDMstIP1gE2y:b1nkwqn) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/basic_states.py#L181)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

My note is more of that you are exposing the outcomes list in the FireTorpedo constructor here, whereas the others do not expose the outcomes list to the outside.
</blockquote></details>

I expose the outcomes list because you _have_ to expose it. You need to provide a way for the state machine to transition. I could hardcode a single outcome, but then a user would have to know what that outcome was. This allows a user to utilize any outcome they desire.

---

*[src/ai/smach_roulette.py, line 194 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HlHENtuYGT19P19p5:-L443KS4SM3sESLxYsYO:bab3d2j) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/smach_roulette.py#L194)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Given how long it has been since I first reviewed this, I don't either. Is there a risk of missing the target by dropping the marker while rotating to follow the slice?
</blockquote></details>

The submarine doesn't rotate to follow the slice. The submarine only translates. There's always a risk of missing the target due to movements. Movement is velocity on the marker, which will cause it to not drop straight down.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ai/basic_states.py, line 181 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HYinq2f6-LfQRCWMs:-L449XircOaM7OvaSISe:blv3iqb) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/basic_states.py#L181)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I expose the outcomes list because you _have_ to expose it. You need to provide a way for the state machine to transition. I could hardcode a single outcome, but then a user would have to know what that outcome was. This allows a user to utilize any outcome they desire.
</blockquote></details>

By that argument, GoToDepth should do the same. If this is true, then every state should expose its outcomes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348)*

**Comment by ryan-summers** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ai/basic_states.py, line 181 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-L2HYinq2f6-LfQRCWMs:-L46q43Z1nvKKKBTZgTg:b-bw8e14) ([raw file](https://github.com/palouserobosub/robosub/blob/a588ff00b8979e738e4e43802f4f100f17eccfea/src/ai/basic_states.py#L181)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

By that argument, GoToDepth should do the same. If this is true, then every state should expose its outcomes.
</blockquote></details>

Updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348)*

**Comment by ryan-summers** [comment]
This PR requires https://github.com/PalouseRobosub/robosub/pull/372 (Vision purge) to be included and downward camera undistortion added to the simulator before merging.

**Comment by skallaher** [comment]
:lgtm: @Sindorman, waiting on you to complete this PR.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-:-L47QO_wE9GFlozTIJc1:b-cga1ub)*

**Comment by Sindorman** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/348#-:-L48guvnbTxX2B42Tzdl:bnfp4nl)*

**Pull request merged**
