### PR TITLE
Added pinger bearing node

### PR DESCRIPTION
**Pull request by irwineffect**
Removed old trilateration code and added pinger bearing node. Calculating the bearing is a more reliable way to interpret the hydrophone data. The `/hydrophones/bearing` topic gives a 3-dimensional vector pointing at the pinger.

Associated with PalouseRobosub/robosub_simulator#98

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/299)

### CODE REVIEW

**Comment by skallaher** [comment]
Would like at least one more review, but :lgtm:! Great job @rsummers and @irwineffect! Looks like this may involve a force merge due to simulator updates. Is this correct?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/sensors/pinger_bearing.cpp, line 22 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/299#-KtoVcuImnbM8JPp-D-C:-KtoVcuJul07q0-aXi3n:bb6xlqr) ([raw file](https://github.com/palouserobosub/robosub/blob/05a67518e67041c8790f205df7a33d8aaadbe89a/src/sensors/pinger_bearing.cpp#L22)):*
> ```cpp
> 
> // callback for incoming ping time deltas from the hydrophones
> // principle of operation: JFM
> ```

JFM?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/299#-:-KtoWcPTxqbTB4PIAHvT:b-592y6l)*

**Comment by skallaher** [comment]
Should not that the old hydrophone node still shows up as runnable unless the `devel` folder is deleted and remade.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/299#-:-KtoaD0K-Ho0kiVnEpFM:b-ocgf1z)*

**Comment by irwineffect** [comment]
Yeah, I think it's stupid that catkin's clean command just removes the intermediate build outputs, not the binaries. It will require a force merge, but tests pass if you're on my hydrophone branch in both repos

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sensors/pinger_bearing.cpp, line 22 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/299#-KtoVcuImnbM8JPp-D-C:-KtrU_aUD7FvSSvWoW3D:b-547yl5) ([raw file](https://github.com/palouserobosub/robosub/blob/05a67518e67041c8790f205df7a33d8aaadbe89a/src/sensors/pinger_bearing.cpp#L22)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

JFM?
</blockquote></details>

Just fucking magic haha. I can remove if you'd like, or have a link to the wiki writeup I plan on doing. Or better yet:
```C
// principle of operation: JFM (see wiki page http://robosub.eecs.wsu.edu/wiki/cs/pinger_bearing/start for more details)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/299#-:-KtrToKLWWI59mDFET-Q:bdgrb2n)*

**Comment by skallaher** [comment]
@ryan-summers, please review.

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/299#-:-KtxKv5-k_kWAXu9duXc:bnfp4nl)*

**Pull request merged**
