### PR TITLE
Trice/localization hz tests

### PR DESCRIPTION
**Pull request by trice9595**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/346)

### CODE REVIEW

**Comment by hmmwhatsthisdo** [comment]
@trice9595 You will need to rebase your branch - it appears you're a few commits behind `master`.

**Comment by Sindorman** [comment]
Seems like your PR contains my commits that have been merged to master, you can do interactive rebase and remove commits.

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/ai/control_wrapper.py, line 88 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/346#-L2laY9RMQgTLjUWhlDA:-L2laY9RMQgTLjUWhlDB:b-4whpwg) ([raw file](https://github.com/palouserobosub/robosub/blob/c339f4226df0325663e3fd56bc5a5725fcf8ea2e/src/ai/control_wrapper.py#L88)):*
> ```Python
>     # Set the pitch state to none and clear out the value
>     def pitchDownNone(self):
>         self.setPitchDown(control.STATE_NONE, 0)
> ```

These commits do not belong in this PR.

---

*[src/localization/test/localizationHz.test, line 5 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/346#-L2lae5t-yM4JKfN5fEo:-L2lae5t-yM4JKfN5fEp:bp9meud) ([raw file](https://github.com/palouserobosub/robosub/blob/c339f4226df0325663e3fd56bc5a5725fcf8ea2e/src/localization/test/localizationHz.test#L5)):*
> ```
>   <include file="$(find robosub_simulator)/launch/gazebo.launch"/>
>   <include file="$(find robosub)/launch/localization.launch"/>
>   
> ```

There is trailing whitespace here, please remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/346)*

**Comment by trice9595** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/ai/control_wrapper.py, line 88 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/346#-L2laY9RMQgTLjUWhlDA:-L48U39aVlyC7k9FGREg:b-a5aj3y) ([raw file](https://github.com/palouserobosub/robosub/blob/c339f4226df0325663e3fd56bc5a5725fcf8ea2e/src/ai/control_wrapper.py#L88)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

These commits do not belong in this PR.
</blockquote></details>

Did I fix this by doing an interactive rebase?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/346)*

**Comment by trice9595** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/localization/test/localizationHz.test, line 5 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/346#-L2lae5t-yM4JKfN5fEo:-L48UIg8qJpzgBTHWjx9:bb7f2mf) ([raw file](https://github.com/palouserobosub/robosub/blob/c339f4226df0325663e3fd56bc5a5725fcf8ea2e/src/localization/test/localizationHz.test#L5)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

There is trailing whitespace here, please remove it.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/346)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/localization/test/localizationHz.test, line 5 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/346#-L2lae5t-yM4JKfN5fEo:-L48hCPzXDMAK8jBnevI:b7m2nz3) ([raw file](https://github.com/palouserobosub/robosub/blob/c339f4226df0325663e3fd56bc5a5725fcf8ea2e/src/localization/test/localizationHz.test#L5)):*
<details><summary><i>Previously, trice9595 wrote…</i></summary><blockquote>

done
</blockquote></details>

Please clear trailing whitespace on the rest of the file as well and on all files.

---

*[src/ai/control_wrapper.py, line 88 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/346#-L2laY9RMQgTLjUWhlDA:-L48hM0F10zOVJBXuEoM:b-4j79xa) ([raw file](https://github.com/palouserobosub/robosub/blob/c339f4226df0325663e3fd56bc5a5725fcf8ea2e/src/ai/control_wrapper.py#L88)):*
<details><summary><i>Previously, trice9595 wrote…</i></summary><blockquote>

Did I fix this by doing an interactive rebase?
</blockquote></details>

That is how you can fix this. If you need a hand, let me know on Slack and we can figure something out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/346)*

**Comment by trice9595** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/ai/control_wrapper.py, line 88 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/346#-L2laY9RMQgTLjUWhlDA:-L4I7oFXwUEmscvEmvK4:bph06x9) ([raw file](https://github.com/palouserobosub/robosub/blob/c339f4226df0325663e3fd56bc5a5725fcf8ea2e/src/ai/control_wrapper.py#L88)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

That is how you can fix this. If you need a hand, let me know on Slack and we can figure something out.
</blockquote></details>

I believe the problem is fixed. I removed the commits from my branch and rebased on top of master which now includes these commits.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/346)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/346)*

**Pull request merged**
