### PR TITLE
added launchfile for recording data

### PR DESCRIPTION
**Pull request by irwineffect**
Launchfile will put rosbags in your current working directory, or can be modified using the `outdir` argument. Let me know if there are any other topics that should be recorded, wasn't sure if I should record the raw or undistorted vision data, I'd rather not record both for space reasons.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/278)

### CODE REVIEW

**Comment by irwineffect** [comment]
fixes #271

**Comment by ryan-summers** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[launch/record.launch, line 18 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/278#-Kq-e4G2xRO3iN0pEIfr:-Kq-e4G2xRO3iN0pEIfs:blj2vxe) ([raw file](https://github.com/palouserobosub/robosub/blob/9dcf33e9dfe7d075483af7f6c2bc4ab44fc1628a/launch/record.launch#L18)):*
> ```XML
>                  /depth
>                  /power/ups
>                  /(.*)/temps"/>
> ```

please make this /temperatures/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/278)*

**Comment by irwineffect** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[launch/record.launch, line 18 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/278#-Kq-e4G2xRO3iN0pEIfr:-Kq-f67NsaSCqluo1iic:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/9dcf33e9dfe7d075483af7f6c2bc4ab44fc1628a/launch/record.launch#L18)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

please make this /temperatures/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/278)*

**Comment by ryan-summers** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/278#-:-Kq-hTKYYh37vQzBOFio:bnfp4nl)*

**Pull request merged**
