### PR TITLE
Sensor and Camera Launchfiles

### PR DESCRIPTION
**Pull request by irwineffect**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/269)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/269)*

**Comment by dcrossman** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/269#-:-KprSNQOww87jCuvhdtF:bnfp4nl)*

**Comment by dcrossman** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/269)*

**Comment by ryan-summers** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/269#-:-KpuXXrWgdfmLf8GqR0a:bnfp4nl)*

**Pull request merged**
