### PR TITLE
added trim and sensor mode service calls

### PR DESCRIPTION
**Pull request by irwineffect**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/210)

### CODE REVIEW

**Comment by ryan-summers** [comment]
Reviewed 3 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/sensors/Bno055.cpp, line 9 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-KeV-SqaGJbxeFiXsRpD:-KeV-SqaGJbxeFiXsRpE:bz2iynt) ([raw file](https://github.com/palouserobosub/robosub/blob/11156e41957a542580fa99a15517ac951107cbed/src/sensors/Bno055.cpp#L9)):*
> ```cpp
>     /**
>      * Initialize the Bno to a default configuration state.
>      *
> ```

Add @param port_name comment

---

*[src/sensors/bno055_sensor.cpp, line 11 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-KeV-aQ4j4-cfU-gBUJh:-KeV-aQ4j4-cfU-gBUJi:bl5eku5) ([raw file](https://github.com/palouserobosub/robosub/blob/11156e41957a542580fa99a15517ac951107cbed/src/sensors/bno055_sensor.cpp#L11)):*
> ```cpp
> #include "geometry_msgs/Vector3Stamped.h"
> #include "std_srvs/Empty.h"
> #include "robosub/bno_mode.h"
> ```

Run these through !sort please

---

*[src/sensors/bno055_sensor.cpp, line 112 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-KeV-xYs9cpL_qSr5rT_:-KeV-xYs9cpL_qSr5rTa:b321w9) ([raw file](https://github.com/palouserobosub/robosub/blob/11156e41957a542580fa99a15517ac951107cbed/src/sensors/bno055_sensor.cpp#L112)):*
> ```cpp
>             ROS_INFO("Setting the mode to Ndof.");
>             break;
> ```

Please add newlines after each break.

---

*[src/sensors/bno055_sensor.cpp, line 147 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-KeV04dCXzHlSbRLGgY7:-KeV04dCXzHlSbRLGgY8:b-qnbt29) ([raw file](https://github.com/palouserobosub/robosub/blob/11156e41957a542580fa99a15517ac951107cbed/src/sensors/bno055_sensor.cpp#L147)):*
> ```cpp
>     /*
>      * Advertise the stamped quaternion and acceleration sensor
>      * data to the software, and the trim service call.
> ```

Remove the comma.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/210)*

**Comment by bkallaher** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/210)*

**Comment by irwineffect** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/sensors/Bno055.cpp, line 9 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-KeV-SqaGJbxeFiXsRpD:-KeV0uimzqMb3KWQIRek:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/11156e41957a542580fa99a15517ac951107cbed/src/sensors/Bno055.cpp#L9)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Add @param port_name comment
</blockquote></details>

Done.

---

*[src/sensors/bno055_sensor.cpp, line 11 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-KeV-aQ4j4-cfU-gBUJh:-KeV0Y-o2BpIq_9VSDeX:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/11156e41957a542580fa99a15517ac951107cbed/src/sensors/bno055_sensor.cpp#L11)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Run these through !sort please
</blockquote></details>

Done.

---

*[src/sensors/bno055_sensor.cpp, line 112 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-KeV-xYs9cpL_qSr5rT_:-KeV0eKAngAGZeADfy9L:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/11156e41957a542580fa99a15517ac951107cbed/src/sensors/bno055_sensor.cpp#L112)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Please add newlines after each break.
</blockquote></details>

Done.

---

*[src/sensors/bno055_sensor.cpp, line 147 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-KeV04dCXzHlSbRLGgY7:-KeV0hUczUotScMgv7BG:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/11156e41957a542580fa99a15517ac951107cbed/src/sensors/bno055_sensor.cpp#L147)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Remove the comma.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/210)*

**Comment by ryan-summers** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-:-KeV1colulh3eIKmk7qe:bnfp4nl)*

**Comment by bkallaher** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/210#-:-KeV1eTfI0VALm_kE9Pz:bnfp4nl)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/210)*

**Pull request merged**
