### PR TITLE
Update Localization Algorithm [SD End-of-Semester Demo]

### LINKED ISSUE #358: Create Pull Request for MVP Particle Filter Code
Create a pull request that moves the current particle filter code to master

### PR DESCRIPTION
**Pull request by hmmwhatsthisdo**
This is the code demoed to NAVSEA by the CS Senior Design at the end of last semester (after some rebases and such).

Main changes are:
 - Change uncertainty values in pinger bearing/point cloud
 - Recalculate weights more often
 - Remove add'l noise in `ParticleFilter::update_particle_weights()`

Resolves #358.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/370)

### CODE REVIEW

**Comment by skallaher** [comment]
@irwineffect, would like your review on this one.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L44CTy_T2zwKL1eCY-e:-L44CTy_T2zwKL1eCY-f:b-gjwb0h) (no related file):*
Does this PR replace or add onto #340?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-:-L44Ca0-Jd2Tmh8F04Xt:b-wy31iz)*

**Comment by hmmwhatsthisdo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L44CTy_T2zwKL1eCY-e:-L48Sq9YcyqTGsPPhUuy:b-plxnei) (no related file):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Does this PR replace or add onto #340?
</blockquote></details>

I wasn't using that branch - I'm not 100% sure if there's anything we specifically want to save out of that PR (maybe particle counts/stddev values as appropriate).

@connor-wool, would you like to weigh in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/localization/particle_filter.cpp, line 294 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48guWuqid2RF4ndkyu:-L48guWvVPKJSs65diMO:b-rkjtz5) ([raw file](https://github.com/palouserobosub/robosub/blob/218adacfb577a710b84b3cc8dd36c72e89b7d578/src/localization/particle_filter.cpp#L294)):*
> ```cpp
>         particle_states[n] = system_update_model * last_particle_states[n] +
>             control_update_model * control_input +
>             system_update_stddev * noise;
> ```

Is there any particular reason for printing the noise for every particle like this?

---

*[src/localization/particle_filter.cpp, line 300 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48h2DneccqOAVcIm91:-L48h2DneccqOAVcIm92:bmpi1iq) ([raw file](https://github.com/palouserobosub/robosub/blob/218adacfb577a710b84b3cc8dd36c72e89b7d578/src/localization/particle_filter.cpp#L300)):*
> ```cpp
> void ParticleFilter::update_particle_weights()
> {
>     // TODO: Change to use unit-vector scalar angle as primary measurement
> ```

I have absolutely no idea what this means. What is a 'scalar angle'? What primary measurement?

---

*[src/localization/particle_filter.cpp, line 304 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48hLwsCXVC1TnsSwMs:-L48hLwsCXVC1TnsSwMt:bw3tzvl) ([raw file](https://github.com/palouserobosub/robosub/blob/f38b40463f8fd4e77837b7d3ff84f735dda60ef6/src/localization/particle_filter.cpp#L304)):*
> ```cpp
>         // Add noise to predicted observation.
>         particle_obs += (observation_stddev *
>                 randn_mat(particle_obs.rows(), 1));
> ```

Why are we removing the noise here? What was its original purpose?

---

*[src/localization/particle_filter.cpp, line 412 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48inhFsieQ9LK-25fj:-L48inhFsieQ9LK-25fk:bkv6wgh) ([raw file](https://github.com/palouserobosub/robosub/blob/218adacfb577a710b84b3cc8dd36c72e89b7d578/src/localization/particle_filter.cpp#L412)):*
> ```cpp
>     update_particle_states();
> 
>     update_particle_weights();
> ```

Why are you updating the particle weights here? Don't we only want to update particle weights whenever new data arrives?

---

*[src/localization/particle_filter.cpp, line 432 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48hciM23m_4f4qV2mI:-L48hciM23m_4f4qV2mJ:b-q206sa) ([raw file](https://github.com/palouserobosub/robosub/blob/f38b40463f8fd4e77837b7d3ff84f735dda60ef6/src/localization/particle_filter.cpp#L432)):*
> ```cpp
>     estimate_state();
> 
>     publish_point_cloud();
> ```

Is this ordering significant? If it is, please add a comment about why it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by hmmwhatsthisdo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/localization/particle_filter.cpp, line 294 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48guWuqid2RF4ndkyu:-L48ojdDzsOY22RPD6H_:b-e5bcc9) ([raw file](https://github.com/palouserobosub/robosub/blob/218adacfb577a710b84b3cc8dd36c72e89b7d578/src/localization/particle_filter.cpp#L294)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Is there any particular reason for printing the noise for every particle like this?
</blockquote></details>

We were originally having some issues with particle noise - IIRC, particles were all getting the same noise offset (or something of the like). It can probably be removed at this point - I'll test it out when I'm back at my desk.

---

*[src/localization/particle_filter.cpp, line 300 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48h2DneccqOAVcIm91:-L48lqTngmx4l4rlYdev:ba0zerk) ([raw file](https://github.com/palouserobosub/robosub/blob/218adacfb577a710b84b3cc8dd36c72e89b7d578/src/localization/particle_filter.cpp#L300)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I have absolutely no idea what this means. What is a 'scalar angle'? What primary measurement?
</blockquote></details>

It was meant to refer to the dot/scalar product between a vector from the particle to the pinger and a vector from the sub to the pinger. 
Instead of considering the X/Y/Z components as their own individual data sources (each with a Gaussian distribution), we would have a single data-point for each particle, indicating how "far off" (in angular terms) that particle's associated vector would be.

Admittedly, that comment should probably be elaborated on a tad - once I'm back in range of my VM, I'll change that comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/localization/particle_filter.cpp, line 294 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48guWuqid2RF4ndkyu:-L49vtdxwmJgsoQRgo2v:b-7qkiyw) ([raw file](https://github.com/palouserobosub/robosub/blob/218adacfb577a710b84b3cc8dd36c72e89b7d578/src/localization/particle_filter.cpp#L294)):*
<details><summary><i>Previously, hmmwhatsthisdo wrote…</i></summary><blockquote>

We were originally having some issues with particle noise - IIRC, particles were all getting the same noise offset (or something of the like). It can probably be removed at this point - I'll test it out when I'm back at my desk.
</blockquote></details>

I would recommend removing it at this point. That's only useful for intensive debugging and doesn't need to be included in the final code imho.

---

*[src/localization/particle_filter.cpp, line 300 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48h2DneccqOAVcIm91:-L49w1L59nG9UOPbKDZ2:b-ogfhiq) ([raw file](https://github.com/palouserobosub/robosub/blob/218adacfb577a710b84b3cc8dd36c72e89b7d578/src/localization/particle_filter.cpp#L300)):*
<details><summary><i>Previously, hmmwhatsthisdo wrote…</i></summary><blockquote>

It was meant to refer to the dot/scalar product between a vector from the particle to the pinger and a vector from the sub to the pinger. 
Instead of considering the X/Y/Z components as their own individual data sources (each with a Gaussian distribution), we would have a single data-point for each particle, indicating how "far off" (in angular terms) that particle's associated vector would be.

Admittedly, that comment should probably be elaborated on a tad - once I'm back in range of my VM, I'll change that comment.
</blockquote></details>

If you could elaborate that into the comment, it would be greatly appreciated (otherwise this is going to sit here without anyone having any clue what it means, like a few in the control system ;) )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by hmmwhatsthisdo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/localization/particle_filter.cpp, line 294 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48guWuqid2RF4ndkyu:-L4JcznPENG6tMb8aS7U:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/0b8e0d6863183e2213e32df8254f9bfce8c01d19/src/localization/particle_filter.cpp#L294)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I would recommend removing it at this point. That's only useful for intensive debugging and doesn't need to be included in the final code imho.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by hmmwhatsthisdo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/localization/particle_filter.cpp, line 300 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48h2DneccqOAVcIm91:-L4Jif-gNY8BcrIu8xKG:b-jebsd9) ([raw file](https://github.com/palouserobosub/robosub/blob/0b8e0d6863183e2213e32df8254f9bfce8c01d19/src/localization/particle_filter.cpp#L300)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

If you could elaborate that into the comment, it would be greatly appreciated (otherwise this is going to sit here without anyone having any clue what it means, like a few in the control system ;) )
</blockquote></details>

Done. I've elaborated (heavily) on what I meant here - let me know if it makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by hmmwhatsthisdo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/localization/particle_filter.cpp, line 304 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48hLwsCXVC1TnsSwMs:-L4rMir4_tp6aPP2OQVk:b-cnqa4l) ([raw file](https://github.com/palouserobosub/robosub/blob/594737a07a4912644d81deeae02d0ae2063ba1d6/src/localization/particle_filter.cpp#L304)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Why are we removing the noise here? What was its original purpose?
</blockquote></details>

When I was speaking with @btmoore last semester, it sounded like the observations themselves shouldn't be receiving additional noise here (in lieu of "noise" being applied to particle positions in the form of resampling w/ noise).

---

*[src/localization/particle_filter.cpp, line 412 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48inhFsieQ9LK-25fj:-L4rWKxu6AeARFPbZPxj:b-1vdbh) ([raw file](https://github.com/palouserobosub/robosub/blob/0b8e0d6863183e2213e32df8254f9bfce8c01d19/src/localization/particle_filter.cpp#L412)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Why are you updating the particle weights here? Don't we only want to update particle weights whenever new data arrives?
</blockquote></details>

In essence, not updating the weights during intermediate update periods causes the point-cloud weights to quickly (i.e. within one or two frames) become inaccurate (to the point of losing clarity) due to the particles drifting. We found that updating the particle weights here (even if the data is not guaranteed to be brand-new) provided a much more cohesive probability distribution inside of the point-cloud.

Eventually, as we work on modularizing the point-cloud weight calculator, we'll have the ability to individually consider each source of location data (hydrophones/IMU, depth sensor, stereo vision, bottom-facing camera, etc.) with its own age/expiration logic - as such, updating the particle weights between hydrophone pings won't cause problems.

---

*[src/localization/particle_filter.cpp, line 432 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48hciM23m_4f4qV2mI:-L4rVLo9PFlHIQD-WwSy:b-oimb5f) ([raw file](https://github.com/palouserobosub/robosub/blob/594737a07a4912644d81deeae02d0ae2063ba1d6/src/localization/particle_filter.cpp#L432)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Is this ordering significant? If it is, please add a comment about why it is.
</blockquote></details>

I've added a comment explaining why the publish call was moved. (TL;DR: Weights are inaccurate immediately after resampling)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by btmoore** [comment]
I can take a look at the code tomorrow and try to figure out the flow again - see if anything looks off.  But as a guideline, the process for the particle filter should be:

1 ) Have particle cloud with all particles of equal/non-existent weight.
2.a ) Move all particles according to predictive/kinematic model.
2.b ) Each particle is also individually shifted by a normal-random amount based on the noise (standard deviation that reflects process noise of the model). 
3.a ) Evaluate each individual particle's state against a measurement
3.b ) The likelihood of fitting that measurement becomes the particle's weight. For multiple measurements, use the product of the likelihoods for the weight (assuming statistical independence of measurements).
4 ) Generate a new cloud of particles by randomly sampling from the old set of particles based on their weights.  High-weight particles will have a greater chance to 'reproduce'.  It's a stochastic evolutionary model.

Repeat.

If you've got that working, that should do fine.

**Comment by hmmwhatsthisdo** [comment]
@btmoore Right - the previous algorithm was adding noise between steps 3 and 4 (after the likelihood-of-truth was calculated, but before both the final location estimate calculation and the _actual_ resampling process)

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-:-L5GsCSzCsM0MAFnbaAt:b-jzgkkk)*

**Comment by ryan-summers** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/localization/particle_filter.cpp, line 412 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48inhFsieQ9LK-25fj:-L5WLHaMjRr8kbykQHd8:bna6gvt) ([raw file](https://github.com/palouserobosub/robosub/blob/0b8e0d6863183e2213e32df8254f9bfce8c01d19/src/localization/particle_filter.cpp#L412)):*
<details><summary><i>Previously, hmmwhatsthisdo wrote…</i></summary><blockquote>

In essence, not updating the weights during intermediate update periods causes the point-cloud weights to quickly (i.e. within one or two frames) become inaccurate (to the point of losing clarity) due to the particles drifting. We found that updating the particle weights here (even if the data is not guaranteed to be brand-new) provided a much more cohesive probability distribution inside of the point-cloud.

Eventually, as we work on modularizing the point-cloud weight calculator, we'll have the ability to individually consider each source of location data (hydrophones/IMU, depth sensor, stereo vision, bottom-facing camera, etc.) with its own age/expiration logic - as such, updating the particle weights between hydrophone pings won't cause problems.
</blockquote></details>

Please add a comment here as to why you update the weights here for posterity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by hmmwhatsthisdo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/localization/particle_filter.cpp, line 412 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48inhFsieQ9LK-25fj:-L5WureJRQmboD3iTf_J:byljv42) ([raw file](https://github.com/palouserobosub/robosub/blob/0b8e0d6863183e2213e32df8254f9bfce8c01d19/src/localization/particle_filter.cpp#L412)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Please add a comment here as to why you update the weights here for posterity.
</blockquote></details>

OK, adding a comment now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by hmmwhatsthisdo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/localization/particle_filter.cpp, line 412 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-L48inhFsieQ9LK-25fj:-L5Wxgexn1l3hod9b1R1:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/0b8e0d6863183e2213e32df8254f9bfce8c01d19/src/localization/particle_filter.cpp#L412)):*
<details><summary><i>Previously, hmmwhatsthisdo wrote…</i></summary><blockquote>

OK, adding a comment now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Comment by ryan-summers** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370#-:-L5X4piTmMtymTHt_TjK:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/370)*

**Pull request merged**
