### PR TITLE
Added in fisheye calibration script

### PR DESCRIPTION
**Pull request by ryan-summers**
This script can be used on a directory of images to generate a camera and distortion matrix for OpenCV. The matrices are then stored in a JSON format for simple loading into other scripts.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/350)

### CODE REVIEW

**Comment by skallaher** [comment]
This already exists for live calibration. What's new here besides using a directory of images?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/350#-:-L2Jb5sOy4lGFp83piVO:b-cwgpm7)*

**Comment by ryan-summers** [comment]
I was trying to use the original calibration for a while, and I was finding that using live calibration data was making it difficult for me to get good calibration data. By using a directory of images, you can capture as many images of the checkerboard as are needed at any different angles you want and then select specific images to use for calibration. It simplified and sped up the process for me because I only ever needed to record footage of the checkerboard once and then could tune the data set to get me a good calibration.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/350#-:-L2LkvQ4UPHYHUxQWX_c:b-3pl8ze)*

**Comment by skallaher** [comment]
:lgtm: I would just request that this go in the vision directory rather than scripts so "calibrate" is more meaningful. The vision directory needs to be cleaned up as well...

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/350#-:-L2g7P7Ka_Er3tSADlUE:b-f5x631)*

**Comment by ryan-summers** [comment]
I moved it for you - I totally agree and just placed it into the wrong spot.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/350#-:-L2gLRj_q7tvyn9jTJr4:b-59aqne)*

**Comment by skallaher** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/350)*

**Pull request merged**
