### PR TITLE
Organized Buoy AI

### PR DESCRIPTION
**Pull request by irwineffect**
Note that the current values do not work very well in the simulator, they were
tuned for the real world. The logic could also be improved, this is just a
direct conversion of the logic we had at the pool test but now using helper
classes and is better organized.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/300)

### CODE REVIEW

**Comment by skallaher** [comment]
In reference to the tuned values, could we make them parameters so that the simulator can override them?

**Comment by skallaher** [comment]
Also, milestone! We're at 300!

**Comment by irwineffect** [comment]
For tunable params, how should they be organized in the parameter tree? Something like `/ai/buoy/tracking_speed`?

**Comment by skallaher** [comment]
@Sindorman, could you review this code to help you get a better understanding of it?

**Comment by skallaher** [comment]
Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ai/smach_buoy.py, line 189 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/300#-KuWQiP0R9dwLH2VsItK:-KuWQiP0R9dwLH2VsItL:b-2lcl8q) ([raw file](https://github.com/palouserobosub/robosub/blob/df1ae7a28d1fb04d75bb10c8bc3842d71b7b946a/src/ai/smach_buoy.py#L189)):*
> ```Python
>         smach.StateMachine.add('BACKUP',
>                                move_forward(time=reset_time, value=reset_speed),
>                                transitions={'success': 'success'})
> ```

Please put these into a StateMachine for reusability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/300)*

**Comment by irwineffect** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ai/smach_buoy.py, line 189 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub/300#-KuWQiP0R9dwLH2VsItK:-Ku_qazzf0nICqIM7mne:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/df1ae7a28d1fb04d75bb10c8bc3842d71b7b946a/src/ai/smach_buoy.py#L189)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Please put these into a StateMachine for reusability.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/300)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/300#-:-Ku_shR3_1691e8X4rOZ:bnfp4nl)*

**Pull request merged**
