### PR TITLE
Added local git config

### PR DESCRIPTION
**Pull request by irwineffect**
Note that to to make this settings file active, you need to run
```
git config --local include.path ../.gitconfig
```

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/194)

### CODE REVIEW

**Comment by ryan-summers** [comment]
Why are you trying to add this into the repo? Surely theres a better way to get the desired functionality here.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-:-Ke1jxciTDkpu5WLur3Q:b-citim9)*

**Comment by irwineffect** [comment]
I've been searching for months, believe it or not this is actually the cleanest solution. You can't directly push the repo's local gitconfig, the creators of git decided that could be a bad security vulnerability (imagine remapping "git fetch" to "upload my home folder to server x"). If I want everyone to have specific settings for the repo, they would need to run all the commands themselves, at least with this solution it only needs to be run once and then we can make changes to this file and they will benefit from the updates.

Or are you asking why I've set those particular settings?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-:-Ke1p5Wb_Uc6j_6m0Wg1:b-sxbio8)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194)*

**Comment by skallaher** [comment]
Those two settings seem very useful indeed.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[.gitconfig, line 2 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-KeGRHS8BYrESKvSuz2a:-KeGRHS8BYrESKvSuz2b:bare9tu) ([raw file](https://github.com/palouserobosub/robosub/blob/cd118fd97ee860c7fe92db31853127472210573f/.gitconfig#L2)):*
> ```
> #note: to make this settings file active, you need to run
> #git config --local include.path ../.gitconfig
> ```

Does this need to be run from a specific directory?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-:-KeGROPa4kTOXGs053Mz:btluvg4)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.gitconfig, line 2 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-KeGRHS8BYrESKvSuz2a:-KeHBJOjxnMvgqoP3UQ7:bhsn1tl) ([raw file](https://github.com/palouserobosub/robosub/blob/cd118fd97ee860c7fe92db31853127472210573f/.gitconfig#L2)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Does this need to be run from a specific directory?
</blockquote></details>

Technically yeah, the --local flag causes modifications to the gitconfig that exists inside the .git directory inside the repo you are currently in. But you can run it from anywhere inside the repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.gitconfig, line 2 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-KeGRHS8BYrESKvSuz2a:-KeHEDxc7ztvz-qYhRr6:btvc04c) ([raw file](https://github.com/palouserobosub/robosub/blob/cd118fd97ee860c7fe92db31853127472210573f/.gitconfig#L2)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Technically yeah, the --local flag causes modifications to the gitconfig that exists inside the .git directory inside the repo you are currently in. But you can run it from anywhere inside the repo.
</blockquote></details>

Could you add to your note specifying where you can run it from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194)*

**Comment by irwineffect** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitconfig, line 2 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-KeGRHS8BYrESKvSuz2a:-KeQ0pbc4DBJvbZxcoPo:b-896fja) ([raw file](https://github.com/palouserobosub/robosub/blob/0a407a9056a3848971e4e91f95bfe05f3e586c7f/.gitconfig#L2)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Could you add to your note specifying where you can run it from?
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194)*

**Comment by bkallaher** [comment]
Maybe also add the tab->spaces filter as well in this PR.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-:-KeQUC-Fv-oud7sqx4Dr:bf904j4)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194)*

**Comment by irwineffect** [comment]
Done!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-:-KeVO6l9dye_bnSL6gKA:b-896fja)*

**Comment by bkallaher** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitconfig, line 16 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-KeVOwWr4bUfAFkNNMj0:-KeVOwWr4bUfAFkNNMj1:bscs0l7) ([raw file](https://github.com/palouserobosub/robosub/blob/30aa95e9c5b6fa4944f2155915b373f61a4d5734/.gitconfig#L16)):*
> ```
> #convert tabs to spaces when files are added to the repo
> [filter "tab2space"]
>     clean = expand --tabs=4 --initial
> ```

change to tab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194)*

**Comment by irwineffect** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.gitconfig, line 16 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/194#-KeVOwWr4bUfAFkNNMj0:-KeWMHiDIbLylRdv9T8K:b-896fix) ([raw file](https://github.com/palouserobosub/robosub/blob/30aa95e9c5b6fa4944f2155915b373f61a4d5734/.gitconfig#L16)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

change to tab
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194)*

**Comment by bkallaher** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/194)*

**Pull request merged**
