### PR TITLE
Addition of Launchfile System

### PR DESCRIPTION
**Pull request by ryan-summers**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/242)

### CODE REVIEW

**Comment by irwineffect** [comment]
For other people looking at this PR, note that the organization scheme we're doing is different from what we've done in the past, and not necessarily what we're going to do in the future. We're just trying something new. 

---

Reviewed 2 of 13 files at r1, 12 of 16 files at r3.
Review status: 14 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[firmware/depth/src/depth.ino, line 95 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-KhpEEK_TmIKkWQYSue1:-KhpEEKaq2Q_xpqgwoPM:ba6f5ph) ([raw file](https://github.com/palouserobosub/robosub/blob/eeada289550cfb1e86c49e952c0bf935b17ebcf0/firmware/depth/src/depth.ino#L95)):*
> ```Arduino
>      */
>     int rate;
>     if (n.getParam("/rate/depth", &rate, 1) == false)
> ```

Why absolute namespacing here? 

---

*[launch/calibrate_imu.launch, line 6 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-KhpEoJ--Osg9SEhXvFz:-KhpEoJ--Osg9SEhXvG-:b-ky7vhb) ([raw file](https://github.com/palouserobosub/robosub/blob/eeada289550cfb1e86c49e952c0bf935b17ebcf0/launch/calibrate_imu.launch#L6)):*
> ```XML
> <launch>
>     <arg name="name" default="bno055_stern" />
>     <arg name="remapped" default="False" />
> ```

It doesn't look like the "remapped" argument is used here 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-:-KhpH2T56VmK06mjWGZk:b1d5v2t)*

**Comment by ryan-summers** [comment]
Review status: 14 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[firmware/depth/src/depth.ino, line 95 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-KhpEEK_TmIKkWQYSue1:-KhpW-BdcyZtvyL_QrOQ:b-tmbqls) ([raw file](https://github.com/palouserobosub/robosub/blob/eeada289550cfb1e86c49e952c0bf935b17ebcf0/firmware/depth/src/depth.ino#L95)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Why absolute namespacing here? 
</blockquote></details>

We discussed that rate namespaces will always be absolute.

---

*[launch/calibrate_imu.launch, line 6 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-KhpEoJ--Osg9SEhXvFz:-KhpW62Bv44rJqh00jPQ:b-wlgud6) ([raw file](https://github.com/palouserobosub/robosub/blob/eeada289550cfb1e86c49e952c0bf935b17ebcf0/launch/calibrate_imu.launch#L6)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

It doesn't look like the "remapped" argument is used here 
</blockquote></details>

Woops, copy-pasta error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/242)*

**Comment by skallaher** [comment]
Review status: 13 of 17 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[firmware/depth/src/depth.ino, line 95 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-KhpEEK_TmIKkWQYSue1:-Khre5ZUFFqOAa-Ji2mL:boasenc) ([raw file](https://github.com/palouserobosub/robosub/blob/eeada289550cfb1e86c49e952c0bf935b17ebcf0/firmware/depth/src/depth.ino#L95)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

We discussed that rate namespaces will always be absolute.
</blockquote></details>

This is not necessarily true, if the sub is pushed down into another namespace (for instance, if we ran two subs at once), then the rate parameters will not be absolute.

---

*[firmware/depth/src/depth.ino, line 116 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-Khred4IAtoRB12p9J9g:-Khred4IAtoRB12p9J9h:bjy87o0) ([raw file](https://github.com/palouserobosub/robosub/blob/afc6553d1fe3b7b2c0a82aaf30a846d50bad7c83/firmware/depth/src/depth.ino#L116)):*
> ```Arduino
>     int id = 0;
>     if (n.getParam("~id", &id, 1) == false)
>     {
> ```

This is not the correct way to access private parameters. You should have a private nodehandle.

---

*[firmware/depth/src/depth.ino, line 120 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-Khrf-obP_Rkd6p8aaDX:-Khrf-obP_Rkd6p8aaDY:b-puxuum) ([raw file](https://github.com/palouserobosub/robosub/blob/afc6553d1fe3b7b2c0a82aaf30a846d50bad7c83/firmware/depth/src/depth.ino#L120)):*
> ```Arduino
>     }
> 
>     char param_string[50];
> ```

Why not use a std::string here and use the + operator for concatenation?

---

*[launch/calibrate_imu.launch, line 7 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-KhrfibcfPXtDNf9armi:-Khrfibdq0Z8HQZWTnTE:b8tdosk) ([raw file](https://github.com/palouserobosub/robosub/blob/afc6553d1fe3b7b2c0a82aaf30a846d50bad7c83/launch/calibrate_imu.launch#L7)):*
> ```XML
>     <arg name="name" default="bno055_stern" />
>     <arg name="port" default="/dev/$(arg name)" />
>     <rosparam file="$(find robosub)/param/$(arg name).yaml" />
> ```

These parameter files could put in their own directory for cleanliness.

---

*[launch/core.launch, line 3 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-KhrgnWyLoOcUrgdsvgt:-KhrgnWzg-ZPgerIjw01:b-jvvcx9) ([raw file](https://github.com/palouserobosub/robosub/blob/040501e6186126a44708e59132fd3df42f3e9feb/launch/core.launch#L3)):*
> ```XML
> <?xml version="1.0"?>
> <launch>
>

**Comment by skallaher** [comment]
Review status: 3 of 21 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-Khx4SY_yfOq52z93Sis:-Khx3pOD1pNPBCJ8AHlF:b-nizx55) (no related file):*
This PR should be split up. You have changes here to the IMU that should be separate. There is no reason for this to also include additional features, it should only be directly related to the launch system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/242)*

**Comment by ryan-summers** [comment]
Review status: 3 of 21 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[firmware/depth/src/depth.ino, line 116 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-Khred4IAtoRB12p9J9g:-KhxADLYjAMsxmUmmOPh:bn50wzm) ([raw file](https://github.com/palouserobosub/robosub/blob/afc6553d1fe3b7b2c0a82aaf30a846d50bad7c83/firmware/depth/src/depth.ino#L116)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This is not the correct way to access private parameters. You should have a private nodehandle.
</blockquote></details>

This is the semantic used for rosserial

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/242)*

**Comment by ryan-summers** [comment]
Review status: 3 of 21 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[firmware/depth/src/depth.ino, line 120 at r4](https://reviewable.io:443/reviews/palouserobosub/robosub/242#-Khrf-obP_Rkd6p8aaDX:-KhxAJbc87IOAvkVo_vT:b7uixc7) ([raw file](https://github.com/palouserobosub/robosub/blob/afc6553d1fe3b7b2c0a82aaf30a846d50bad7c83/firmware/depth/src/depth.ino#L120)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why not use a std::string here and use the + operator for concatenation?
</blockquote></details>

This is microcontroller code. You cant used std::string because it does memory allocation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub/242)*

**Comment by ryan-summers** [comment]
Closing this pull request and breaking it into multiple parts.

**Pull request closed without merging**
